### ISSUE TITLE
Email internal address when users update Bitcoin addresses

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#10]
when the user enters a Bitcoin address, send an email to the support email (defined in [config/secrets.yml](https://github.com/brave/publishers/blob/master/config/secrets.yml) indicating that.

just the publisherID (e.g. example.com) and the fact they’ve done that.

**Comment by ayumi** [comment]
implemented with https://github.com/brave/publishers/commit/8d75e1b2841a62c9db5a2bf6d8cfaa160092380a

**Comment by mrose17** [comment]
OBE now that uphold is in place for BAT Mercury
