### ISSUE TITLE
Show referral promos after they've been generated

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1048]
I don't believe this is possible, but a user needs to see the referral promos after it's been generated.

**Comment by nvonpentz** [comment]
Promo codes are shown on the dashboard along with the links to their promo pages.  Additionally, an email is sent with this information upon promo activation.

![image](https://user-images.githubusercontent.com/12549658/42128223-62eee20a-7c74-11e8-98d3-4b8edfd7c0fb.png)

I suggest you try out all of the flows on the site, there are only a couple..

**Comment by yachtcaptain23** [comment]
IMO this might be a discovery problem + poor OOBE. I don't think from a
mental model perspective that it makes sense for 1 panel to enable creation
of all promos and then in a different panel, there's a list of referral
links hidden under `Referral Link` that's colored gray rather than red, nor
is it obvious that sharing via Twitter + Facebook makes BAT. I'm aware the
emails are sent out, but assuming the publisher doesn't remember, we should
be designing for ease of use.

**Comment by yachtcaptain23** [comment]
FWIW I have setup Twitch, Youtube, a personal domain and a github.io page.
