### ISSUE TITLE
Verify email changes

### ISSUE THREAD

**Issue by dgeb** [brave-intl/publishers#110]
Emails can now be edited from the dashboard (see #109). Before these changes become effective, we should verify that the new email address is valid.

**Comment by dgeb** [comment]
I'm guessing that we'll want to send two emails:

* one to the current address - notifying the user that an email change has been requested.

* one to the new address - requesting that the user follow a link to verify their new address.

@mrose17 @alexwykoff does that sound right? If so, I'll need text for both (although I can improvise for now).

**Comment by mrose17** [comment]
yes, both addresses. @alexwykoff - please provide the copy. i suggest that the text for the initial  verification email be used as a starting point.

**Comment by dgeb** [comment]
Resolved by #114

**Comment by mrose17** [comment]
Fixed by #114
