### ISSUE TITLE
Update exclusion list

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1106]
The exclusion list located [here](https://github.com/brave-intl/publishers/blob/staging/config/excluded_site_channels.yml) needs to be updated per @mandar-brave.

**Comment by mandar-brave** [comment]
No changes to exclusion list. Please close issue.

If possible, can we pull new Alexa lists every 90 days. The exclusion list was created by using alexa top sites for government, commerce, etc. listings. Ryan L. had originally crawled the list - looks fairly constant.

Thanks!

**Comment by dlipeles** [comment]
Noted! @yachtcaptain23, perhaps you'd like to formalize that into a new issue. 
Thanks for checking this out @mandar-brave
