### ISSUE TITLE
Add exclude_from_payout flag to PromoRegistration

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1114]
Action Items:
- [ ] Be able to turn ON/OFF payments for conversion.
- [ ] Expose an endpoint to show if the payments for conversion is on or off

**Comment by nvonpentz** [comment]
@mandar-brave Will this be set by admins or by the publisher?

**Comment by nvonpentz** [comment]
@yachtcaptain23 @mandar-brave Is this issue covered by https://github.com/brave-intl/publishers/issues/1113?

**Comment by mandar-brave** [comment]
By the Admins; the Publishers should have no access to any controls for their own personalization; not at this point. Thanks

cc @nvonpentz

**Comment by corymcdonald** [comment]
Closing this as no longer relevant
