### ISSUE TITLE
Detailed stats on admin/publisher#show

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1115]
Mandar and Jenn will provide more details. We might copy the same UI to publishers#home

**Comment by nvonpentz** [comment]
@mandar-brave Is this still an active ask?

**Comment by mandar-brave** [comment]
Yes @nvonpentz ; we can move it to a lower priority till we spec the next phase of the roadmap. The stats for the entirety of Pubs, Promo, etc. is still an ask. Needs @aekeus and @evq to start working on data centralization before issue gets fully resolved.

**Comment by yachtcaptain23** [comment]
All done on Metabase with the Potential Payments table.
