### ISSUE TITLE
Expose referral stats 

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1116]
Action Items:
- [ ] Expose retention per download per code

(Albert): Will follow up with M. Origer

**Comment by yachtcaptain23** [comment]
Per conversation with Aubrey, @yachtcaptain23  to follow up December 9.

**Comment by yachtcaptain23** [comment]
Spoke with @aekeus this is not likely relevant. Please re-open if it becomes relevant.

**Comment by corymcdonald** [comment]
Going to use this to display retention, we'll likely expose this to publishers eventually
