### ISSUE TITLE
Suspicious pub owners aggregation (Feature Request)

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1146]
This is a feature request to allow for all information that is generated via the suspicious accounts work-stream.

- Allow filter for suspicious accounts so we can review those accounts on admin console
- For these publishers, pull the gordon file and make it available
- For these publishers, put commentary from fraud team re: contributions
- Please allow for a permanent place for comments from fraud team.

For suspended accounts, we need a place for discussions so a single thread can be utilized to capture email flow and #suspicious-pubs conversations related to them. Ideally publisher support teams should be able to capture conversations in there.

Longer term, we want to use email communication via this login to allow for 100% of communication to happen from here.

@evq @yachtcaptain23

**Comment by yachtcaptain23** [comment]
This is tackled by the Suspended publishers filter and the API supports changing of a publisher's status. Fraud team also posts comments as to why someone gets suspended.
