### ISSUE TITLE
Login emails display images as attachments in new gmail

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1159]
Using the new gmail update, the log in emails (and probably others as well) display the images as attachments.  Ideally we include these in a such a way that images aren't displayed this way.

![image](https://user-images.githubusercontent.com/12549658/45324924-88498a00-b51d-11e8-994e-575d05a71686.png)

**Comment by yachtcaptain23** [comment]
So how Amazon does it is they embed an href with the image hosted elsewhere rather than including the image as part of the email.

**Comment by yachtcaptain23** [comment]
In a discussion with product, we're tabling this as Publishers might dislike us storing on CDNs. This issue hasn't caused problems before.

**Comment by yachtcaptain23** [comment]
Re-opening as @nvonpentz suggests there might be ways to render images as attachments without flagging them as downloadable by Gmail.

**Comment by tsmartt** [comment]
Closing as stale.
