### ISSUE TITLE
Notify admins when users' emails change

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#116]
came up in https://github.com/brave/publishers/pull/114#pullrequestreview-64451991

it doesn't include an internal email notification when users change their emails. @mrose17 @alex do admins need to be notified when users have changed their email addresses?

**Comment by jenn-rhim** [comment]
Yes, correct @ayumi the emails need to go out to both old and new email address.

**Comment by alexwykoff** [comment]
<img width="598" alt="screen shot 2017-11-10 at 1 34 45 pm" src="https://user-images.githubusercontent.com/1434040/32675276-f3b2ed0a-c61b-11e7-88a8-84d96ad45309.png">

We currently are sending to both, but the subject has square brackets 😸

**Comment by jenn-rhim** [comment]
ok. let's add this case to your g-doc as well. :)
