### ISSUE TITLE
Conversion and piwik metrics for brave.com/publishers and publishers.basicattentiontoken.org

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1173]
I want to know how many visitors we get to brave.com/publishers and visitors to publishers.basicattentiontoken.org

Additionally, if we can get Piwik numbers on the `Become a Verified Publisher` button.

**Comment by dlipeles** [comment]
Monthly visits added, can you point out which API we want to get channels created from ?
