### ISSUE TITLE
Use WebAuthn for publishers login

### ISSUE THREAD

**Issue by tomlowenthal** [brave-intl/publishers#1175]
WebAuthn gives us a robust passwordless login experience without the friction of checking for an email.

**Comment by corymcdonald** [comment]
I looked into this a little bit and I had some concerns around implementation. [Paragon reveals cryptographic weaknesses in WebAuthn](https://www.biometricupdate.com/201809/paragon-reveals-cryptographic-weaknesses-in-webauthn)

This is a relatively new feature and the demo doesn't seem to even work in Brave - https://webauthn.org 🤔

**Comment by tomlowenthal** [comment]
I think those concerns are a little overblown, though the take-away advice is pretty sensible. WebAuthn is basically the only thing going for passwordless auth any time soon.

We should probably fix whatever is broken with the demo. The feature is in Chrome, so not sure why it doesn't work for us.

**Comment by tsmartt** [comment]
Closing as stale.
