### ISSUE TITLE
Use the Publisher preferred currency for Brave Rewards donation banner

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1196]
cc @dlipeles 

Dan - filing the issue after the currency chat.

Requirement#1
Please use the preferred (default) currency set by the Publisher to show the BAT choices to help Publisher understand computation.
If default currency is set as BAT, please use USD for those Publishers (it would add no value to show a BAT to BAT conversion).

Requirement#2
Please use current (or daily) trading values to show conversion.

**Comment by yachtcaptain23** [comment]
This was done as part of https://github.com/brave-intl/publishers/pull/1203
