### ISSUE TITLE
Donation Banner: Need to FYI Publishers re: delay

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1213]
ON "submit/save" for any changes to the banner, the Publisher widget needs to provide the publisher a FYI that the Brave browser ecosystem will need 2 hours to pick up the changes.

A small confirmation note that the Publisher can acknowledge with a "button" that says do not show again would be OK.

**Comment by dlipeles** [comment]
Closed in #1316 , on save we render a display that FYI's the 2 hour delay. 

However I'll create a lower priority item for the `do not show again` button, as this will require setting a cookie.
