### ISSUE TITLE
Need to update the Referral Promo banner on the Dashboard

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#1215]
Referral promo started out as a limited time offer, but it has evolved to be one of the persistent ways for the publisher users to earn BAT. We needed to reflect this on the banner content:
1. Removed 'Limited Time Promo' label
2. Made 'Refer' as a title copy for users to notice the banner easily
3. Updated the CTA to 'Get Started'
4. Other minor tweaks: button text color and the background graphic. The file is in Abstract.

<img width="594" alt="screen shot 2018-10-09 at 6 11 31 pm" src="https://user-images.githubusercontent.com/4369856/46714611-375aad80-cc11-11e8-99de-419bbbfa7f3a.png">

**Comment by nvonpentz** [comment]
It looks like this needs to be updated in multiple places.
![image](https://user-images.githubusercontent.com/12549658/48030450-18bbd980-e11f-11e8-9de5-5c3d8f864b07.png)
