### ISSUE TITLE
Need to update the product branding for Brave Payments for Advertisers

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#1217]
![image](https://user-images.githubusercontent.com/4369856/46715234-06c84300-cc14-11e8-8321-55c52bc5326b.png)

@mandar-brave i don't see @amir here. assigning it to you for now.

**Comment by amirsaber** [comment]
@jenn-rhim this is my account on github.

**Comment by nvonpentz** [comment]
Closing because this is meant for a different repo
