### ISSUE TITLE
I switched phones and can't 2FA into  publishers.basicattentiontoken.org

### ISSUE THREAD

**Issue by aligneddev** [brave-intl/publishers#1222]
If there aren't too big of security ramifications, I request a feature to be able to reset this. I think you'd be able to do this with a few personal identifiers or even an email address link request?

I'm really not wanting to use a different email account and then have to re-spread my referral link that I've shared over the last year.

Thanks!

I was told "If you have lost access to your 2FA authentication method for Brave Payments, you will not be able to log back into your account at any time.
However, you can transfer your previous channels (along with their respective balances) into a new Payments account.
Simply open a new Payments account under a new email address and re-add your old channels (follow the same steps you did to set them up in the first place). Your channels will transfer to your new account within 10 days.
Keep in mind that you will also have to re-register with our referral program and your referral link will also have to be regenerated.
Don't hesitate to zip an email over to support+publishers@basicattentiontoken.org if you are having problems or have any questions.
Best,
Brave Publisher Support"

**Comment by corymcdonald** [comment]
Hey there @aligneddev, thanks for the feature request! We agree that using a separate email is really inconvenient and being able to recover the original is important. 

We've been discussing the security ramifications and the best course of action on this and going to be tackling this soon. You can track the progress of this on the [2FA Removal Milestone](https://github.com/brave-intl/publishers/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A"2FA+Removal+Feature")

**Comment by aligneddev** [comment]
Thank you. I was able to transfer to a new email address, so I'm glad that worked
It just took about 10 days for the waiting period allowing someone to stop that transfer.
