### ISSUE TITLE
H1 413200 — possible spam

### ISSUE THREAD

**Issue by tomlowenthal** [brave-intl/publishers#1266]
We've received a report about potentially-unwanted emails sent via the publishers app. https://hackerone.com/reports/413200

**Comment by nvonpentz** [comment]
This is also being tracked internally https://github.com/brave/internal/issues/427.

I believe this is resolved by https://github.com/brave-intl/publishers/pull/1194.

**Comment by yachtcaptain23** [comment]
@tomlowenthal we already have a spam filter in place: It's just not as well tightly configured for normal usage vs non-normal usage. I updated the values in PR #1194 to be more aggressive to prevent more spam emails from going out.
