### ISSUE TITLE
Pubs error page displays "Brave Payments" text in logo

### ISSUE THREAD

**Issue by atsyed87** [brave-intl/publishers#1274]
<img width="707" alt="screen shot 2018-10-25 at 3 06 10 pm" src="https://user-images.githubusercontent.com/243423/47533153-876b7e00-d867-11e8-948c-6ea25ff8209a.png">

Should say "Brave Rewards"

**Comment by nvonpentz** [comment]
Replaced by https://github.com/brave-intl/publishers/issues/1290
