### ISSUE TITLE
Cleanup unused i18n localization strings

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#128]
Cleanup unused localization strings from `en.yml`.

We could add a development gem such as [i18n-tasks](https://github.com/glebm/i18n-tasks) to assist with finding/removing the unused strings. It also offers other features, such as google translation service integration, that might be useful.

**Comment by amitkumarj441** [comment]
@lgebhardt Sounds interesting.
I'm willing to take up this task.
Do we need to create another repo for this task to start?

**Comment by lgebhardt** [comment]
@amitkumarj441 I added #163 which contains my initial work on this. It simply adds the [i18n-tasks](https://github.com/glebm/i18n-tasks) gem. The documentation at https://glebm.github.io/i18n-tasks/ should get you started on removing unused keys, as well as finding any keys with missing translations.

**Comment by mixonic** [comment]
I've started some work on this as a long-hanging item while issues are still being assigned/prioritized.

**Comment by nvonpentz** [comment]
This was resolved in #314.
