### ISSUE TITLE
Integrate new Publishers Landing Page

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1282]
- Don't need `support` and `get started`

![image](https://user-images.githubusercontent.com/8647607/47582786-39f41d00-d90a-11e8-94d4-0f6a6e0ba0e0.png)

**Comment by yachtcaptain23** [comment]
Relevant: https://github.com/brave-intl/publishers/issues/1079

**Comment by dlipeles** [comment]
Will own this feature outright

**Comment by dlipeles** [comment]
`Blocked` , will resume dev when product team reaches consensus and gives the green light.

**Comment by yachtcaptain23** [comment]
Issue will be tracked in https://github.com/brave-intl/publishers/issues/1592
