### ISSUE TITLE
Brave Payments strong needs to be ported to Brave Rewards prior to 11/7

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1290]
On all product branding
On all email communication

@nvonpentz

**Comment by nvonpentz** [comment]
We also need to update all the OAuth applications: Uphold, Google, Twitch.

**Comment by nvonpentz** [comment]
Blocked until have replacements for _logo_white_svg.html and _logo_wordmark_white_svg.html in app/views/application cc @jenn-rhim

**Comment by mandar-brave** [comment]
@bradleyrichter can you please help with the asks from @nvonpentz

**Comment by mandar-brave** [comment]
We also need to change all branding on site for bat.org to reflect Brave Rewards. Tracking here as an additional ask.

**Comment by corymcdonald** [comment]
@bradleyrichter The files are here
