### ISSUE TITLE
Allow Uphold accounts to be disconnected / changed

### ISSUE THREAD

**Issue by dgeb** [brave-intl/publishers#133]
After an Uphold account has been associated with a publisher, it seems desirable to allow a publisher to switch to using a different Uphold account.

Similarly, it may also be desirable to allow publishers to disconnect from Uphold entirely for a time, thereby allowing balances to accrue without being transferred.

/cc @alexwykoff @mrose17

**Comment by mrose17** [comment]
let us defer this until after october 6th...

**Comment by mrose17** [comment]
to implement this, we need to have a button that takes the user to `https://uphold.com/dashboard/profile/applications/authorized/{UPHOLD_CLIENT_ID}` where they can click on `[REMOVE]`. we should also have the dashboard refresh so as to make another call to `GET /v2/publishers/{publisher}/wallet` and see that `status.action` is now set.

**Comment by jenn-rhim** [comment]
Here is the UI for this scenario.

1. Display the connection status below the title of the box, Your Uphold Wallet, and provide the action that allows user to disconnect next to it.  

![4-dash-walletyes](https://user-images.githubusercontent.com/4369856/34235919-b74d826e-e5a9-11e7-97f4-c87f0a045b54.png)

2. Get confirmation from the user
![5-dash-disconnect](https://user-images.githubusercontent.com/4369856/34235962-f557bb56-e5a9-11e7-824e-91cb2244d915.png)


3. Once the user confirms it, the dashboard goes back to 'No Wallet' state.
![1-dash-nowallet](https://user-images.githubusercontent.com/4369856/34235980-0e2fdd66-e5aa-11e7-8820-233a3336c43b.png)

**Comment by mrose17** [comment]
one comment on the second diagram: if someone does click the button to disconnect the uphold account. it should open up a tab to the uphold site, preferrably to https://uphold.com/dashboard/profile/applications/authorized/{UPHOLD_CLIENT_ID}/edit where they will see something like this:

<img width="1094" alt="z" src="https://user-images.githubusercontent.com/400552/34281816-283e9be4-e676-11e7-8964-c556e9f1d031.png">

so we might want some messaging here telling folks to click the remove option...

**Comment by duaneking** [comment]
I was bit by this bug today. Really want a fix asap as currently, my profile is linked to a non-existent account on uphold that I don't control and can not access, and I have no way to remove it.

**Comment by mrose17** [comment]
@duaneking - sorry about that. if you login to the publishers site now, you should see a connect to uphold button!

**Comment by mrose17** [comment]
i suggest that a new choice be added under the account drop-down (current choices are home, security, and logout) that includes "Disconnect Uphold"

**Comment by duaneking** [comment]
Thank you for that fix.

This only happened because the email you use for uphold isnt validated as correct before its passed on to the third party; You should have users enter it twice so you can at least use javascript to require they both match.

**Comment by mrose17** [comment]
i suspect that the email capture at that point is done by uphold. i will discuss the situation with them!

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/changing-which-uphold-account-is-attached-to-brave-publisher-account/17914?u=eljuno

**Comment by gnimmelf** [comment]
I'm at version 1.21.76 Chromium: 89.0.4389.86, and have been "locked" to my initial, unauthorized Uphold account for months because Uphold can't / won't authorize it. So ended up with a new account at Uphold, and now I need to link Brave to that new Uphold account...

Is there a dev-fix to this? Some file or DB entry to edit or delete?
