### ISSUE TITLE
Private file uploads

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1330]
Allow users to upload their own attachments only accessible by admins. The current ActiveStorage setup is set to Brave Rewards, so a custom configuration must be setup to point to a private S3 bucket:

Action Items:
- [ ] Setup a helper method using this [class](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/s3_service.rb) to create a specialized service for reading/downloading files on S3. You'll need to work with devops to get a private S3 bucket setup

**Comment by nvonpentz** [comment]
ActiveStorage only allows one bucket per application (see https://stackoverflow.com/questions/49160670/using-multiple-buckets-with-activestorage and https://github.com/rails/rails/issues/32790).

So I think the best bet here is to use paperclip and follow this guide https://gist.github.com/belgoros/b289a0b57b52d16b99d436ca9b80417f.

This would leave us using two different methods to upload files to S3, so we might want to consider moving to paperclip for brave rewards as well.
