### ISSUE TITLE
Add correlation between contributions and alexa rank

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1336]
Feature Request from Alex: He suggests we add Alexa Rank to top contributors as a way to motivate publishers to join us. 

Alternatively, if we estimate contributions per 1000 page views, that would be beneficial internally.

**Comment by nvonpentz** [comment]
We already regularly save the stats e.g. video count, subscriber count, and view count for both twitch and youtube channels here:

https://github.com/brave-intl/publishers/blob/staging/app/jobs/sync_channel_stats_job.rb

Ideally we just add on to the existing set up and create a ChannelStatsServices::SiteChannelStatsService service and call it for every site channel in SyncChannelStatsJob.

**Comment by yachtcaptain23** [comment]
Update: We can reference https://github.com/brave/alexa-url-list-fetcher

**Comment by yachtcaptain23** [comment]
Spoke with nick. He has his own way to get this info. Closing.
