### ISSUE TITLE
Crash upon clicking login link

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1340]
Reproducibility: Sometimes (<50%)
Severity: Low

Details in https://sentry.io/brave-software/publishers-production-t2/issues/646540792/?query=is:unresolved

**Comment by yachtcaptain23** [comment]
Seems like it's a regression from rack-attack. I'll address this to be less aggressive to allow more attempts in the same time frame.

**Comment by corymcdonald** [comment]
This was resolved in this PR
https://github.com/brave-intl/publishers/pull/1370
