### ISSUE TITLE
Upgrade to Ruby 2.4.5

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1342]
Upgrading to Ruby 2.4.x will allow us to consume an updated version of the OpenSSL library and therefore us to detect deprecated certificates such as https://rc4.badssl.com/

**Comment by yachtcaptain23** [comment]
This is the issue I had ran into when attempting to upgrade to 2.4: https://github.com/attr-encrypted/encryptor/issues/26

**Comment by corymcdonald** [comment]
https://github.com/brave-intl/publishers/pull/1458
