### ISSUE TITLE
Update to the Dashboard style

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#137]
Instead of having a column of text, the information should be moved into discreet boxes.

General note : styles displayed should not override https://github.com/brave-intl/publishers/issues/125

Landing and login screens:
1. Landing screen covered in https://github.com/brave-intl/publishers/issues/125

2. Login screen
<img width="482" alt="screen shot 2017-09-29 at 3 03 02 pm" src="https://user-images.githubusercontent.com/1434040/31033868-5277f120-a527-11e7-80c3-032c0eee83a0.png">

3. Check email screen
<img width="481" alt="screen shot 2017-09-29 at 3 03 36 pm" src="https://user-images.githubusercontent.com/1434040/31033921-87f69ee6-a527-11e7-8155-fc59e5c3f0c6.png">

4.a. Verified Publisher Dashboard - no errors 
<img width="482" alt="screen shot 2017-09-29 at 2 58 12 pm" src="https://user-images.githubusercontent.com/1434040/31033970-b4b112d6-a527-11e7-8343-e84f3eb889e8.png">

4.b. Verified Publisher Dashboard - wallet not found
<img width="481" alt="screen shot 2017-09-29 at 2 59 45 pm" src="https://user-images.githubusercontent.com/1434040/31033998-ca04f846-a527-11e7-8c6c-73c60d966566.png">

5.i. Edit Contact Information - Edit mode
<img width="482" alt="screen shot 2017-09-29 at 2 58 25 pm" src="https://user-images.githubusercontent.com/1434040/31034018-e44d9186-a527-11e7-86c9-0be9b1f7049b.png">

5.ii. Edit Contact Information - Saved Changes
<img width="482" alt="screen shot 2017-09-29 at 2 58 33 pm" src="https://user-images.githubusercontent.com/1434040/31034057-0f7fc388-a528-11e7-9cb7-fc5613683847.png">

6.i. Verified Publisher Dashboard - Exclusion Contention Flow
<img width="480" alt="screen shot 2017-09-29 at 2 58 53 pm" src="https://user-images.githubusercontent.com/1434040/31034090-2dfd670c-a528-11e7-8484-15d569dc0086.png">

6.ii. Verified Publisher Dashboard - Exclusion Contention Flow - Contention Form
<img width="480" alt="screen shot 2017-09-29 at 2 59 29 pm" src="https://user-images.githubusercontent.com/1434040/31034116-3fb5388a-a528-11e7-8013-458056947e42.png">

6.iii. Verified Publisher Dashboard - Exclusion Contention Flow - Under Review Status
<img width="480" alt="screen shot 2017-09-29 at 2 59 38 pm" src="https://user-images.githubusercontent.com/1434040/31034130-4f159216-a528-11e7-8d84-096ddf15fb95.png">

7.i. Verified Publisher Dashboard - Statement Download
<img width="481" alt="screen shot 2017-09-29 at 3 11 28 pm" src="https://user-images.githubusercontent.com/1434040/31034167-814d8e50-a528-11e7-9cd2-24b682efaff4.png">

**Comment by ayumi** [comment]
2 thoughts:

1) I feel the UI design isn't ready yet. My main feedback is that gray is a dull color, and kind of depressing.
I'm not sure the best solution, but maybe we can just do transparent boxes?

2) Given 1) if the design isn't polished yet, and the understanding that we're all working tirelessly to make BAT Mercury happen on time: Maybe we should postpone this issue for after Mercury?

Here's the current state of this page, and while it's not a work of art I'd say it's clean and functional:

<img width="773" alt="screen shot 2017-10-05 at 22 50 14" src="https://user-images.githubusercontent.com/521861/31256232-bfd8f496-aa20-11e7-8341-72e190490aac.png">

**Comment by alexwykoff** [comment]
The boxes give each section a purpose and the contrast is purposeful.  Perhaps @jenn-rhim has an update given the branding work?

Leaving the current state as-is just leaves text hanging aimlessly in space.

**Comment by jenn-rhim** [comment]
I'm proposing the changes to the dashboard and the verify steps (template below).  More details to come...


![dashboard](https://user-images.githubusercontent.com/4369856/31301426-b343caa6-aaae-11e7-8348-1598254ac8d9.png)


![verify-temp](https://user-images.githubusercontent.com/4369856/31301447-dbd10970-aaae-11e7-9dfe-3cb7d9815b5e.png)

**Comment by lgebhardt** [comment]
For the Uphold section we have two states, connected and unconnected. When the publisher is unconnected we show the Connect button and redirect to the the `uphold_authorization_endpoint` (which then redirects back with the code).  Once the publisher is connected  to Uphold what is the desired behavior?

In the above proposal what do the `Check Balance` and `Update your tax or BAT info` links do?

**Comment by mrose17** [comment]
for the "Check Balance" button above, the link should go to https://uphold.com/dashboard

for the "Update ..." link, it should go to https://uphold.com/dashboard/profile/personal-information

if we don't think the publisher has an uphold account, the button should be whatever a publisher sees when we want them to oath.

@lgebhardt - does all this make sense?

**Comment by mrose17** [comment]
also, i will provide an API all so that you can report summary information on the page.

**Comment by jenn-rhim** [comment]
Updated dashboard: attempt to clarify the difference between the current BAT balance and the settled balance in user's Uphold wallet (not overtly but indicating that deposit is made only periodically). @mrose17 confirmed that we can display the last settlement amount and date.

![dashboard-1](https://user-images.githubusercontent.com/4369856/31366107-40a0bb9e-ad24-11e7-8c29-a156f496c85c.png)

**Comment by jenn-rhim** [comment]
@lgebhardt --
here is the universal background gradient values for Pub Verif process as well as the dashboard:
-webkit-linear-gradient(-75deg, #f1f3f6, #f1f3f6, #e4e7eb, #e6d8d9, #e8cacc, #f7ada7, #e48290, #ca3884, #c7297b)

**Comment by jenn-rhim** [comment]
@lgebhardt : indeterminate progress indicator
(let's do this if we have time)

Html:

<div class="cssload-container">
<div class="cssload-loading"><i></i><i></i></div>
</div>

Css:
(background rectangle)
box: 120px x 120px
border-radius: 8px;
background: #EAEDEF;
opacity: 0.8;


.cssload-container{
	display: block;
	margin:29px auto;
	width:57px;
}

.cssload-loading i{
	width: 29px;
	height: 29px;
	display: inline-block;
	background: rgb(255,63,63);
	border-radius: 50%;
}
.cssload-loading i:nth-child(1){
	animation:cssload-loading-ani1 1.15s ease-in-out infinite;
		-o-animation:cssload-loading-ani1 1.15s ease-in-out infinite;
		-ms-animation:cssload-loading-ani1 1.15s ease-in-out infinite;
		-webkit-animation:cssload-loading-ani1 1.15s ease-in-out infinite;
		-moz-animation:cssload-loading-ani1 1.15s ease-in-out infinite;

}
.cssload-loading i:nth-child(2){
	background: rgb(0,189,214);
	margin-left: -6px;
	animation:cssload-loading-ani1 1.15s ease-in-out 0.58s infinite;
		-o-animation:cssload-loading-ani1 1.15s ease-in-out 0.58s infinite;
		-ms-animation:cssload-loading-ani1 1.15s ease-in-out 0.58s infinite;
		-webkit-animation:cssload-loading-ani1 1.15s ease-in-out 0.58s infinite;
		-moz-animation:cssload-loading-ani1 1.15s ease-in-out 0.58s infinite;
}


@keyframes cssload-loading-ani1{
	70%{
		transform:scale(0.5);
	}
}

@-o-keyframes cssload-loading-ani1{
	70%{
		-o-transform:scale(0.5);
	}
}

@-ms-keyframes cssload-loading-ani1{
	70%{
		-ms-transform:scale(0.5);
	}
}

@-webkit-keyframes cssload-loading-ani1{
	70%{
		-webkit-transform:scale(0.5);
	}
}

@-moz-keyframes cssload-loading-ani1{
	70%{
		-moz-transform:scale(0.5);
	}
}


![indeterminate-spinner](https://user-images.githubusercontent.com/4369856/31371923-585a8ab6-ad48-11e7-9f72-4bb2b1dc3451.png)

**Comment by jenn-rhim** [comment]
@lgebhardt Assets for Dashboard:

![icn-contact](https://user-images.githubusercontent.com/4369856/31372046-cef8bf26-ad48-11e7-95d6-bb30519161aa.png)
![icn-contact 2x](https://user-images.githubusercontent.com/4369856/31372047-cf5d4676-ad48-11e7-9aa7-ca0e03a8f09a.png)
![icn-contact 3x](https://user-images.githubusercontent.com/4369856/31372048-cf758d80-ad48-11e7-9bbd-d27bb5ad8912.png)
![icn-download](https://user-images.githubusercontent.com/4369856/31372050-cf91f36c-ad48-11e7-99a1-097b3dfbd7da.png)
![icn-download 2x](https://user-images.githubusercontent.com/4369856/31372051-cfa9a21e-ad48-11e7-8109-cc0e11f64d2c.png)
![icn-download 3x](https://user-images.githubusercontent.com/4369856/31372052-cfbddcb6-ad48-11e7-9a0a-56b4c0906c91.png)
![icn-list](https://user-images.githubusercontent.com/4369856/31372053-cfd396be-ad48-11e7-809e-e76faeb87128.png)
![icn-list 2x](https://user-images.githubusercontent.com/4369856/31372054-cff1e01a-ad48-11e7-8b4a-7c05595bc869.png)
![icn-list 3x](https://user-images.githubusercontent.com/4369856/31372055-d009d404-ad48-11e7-9679-8acdbebb3ae6.png)
![icn-wallet](https://user-images.githubusercontent.com/4369856/31372056-d0387d22-ad48-11e7-9118-a0166c941dd7.png)
![icn-wallet 2x](https://user-images.githubusercontent.com/4369856/31372057-d05113aa-ad48-11e7-8551-bff9d02cf2b0.png)
![icn-wallet 3x](https://user-images.githubusercontent.com/4369856/31372058-d06743fa-ad48-11e7-9ac6-6bcaba9b93c1.png)
![img-headerlogo](https://user-images.githubusercontent.com/4369856/31372059-d07dac76-ad48-11e7-8a74-8fa561f8c137.png)
![img-headerlogo 2x](https://user-images.githubusercontent.com/4369856/31372060-d0a019a0-ad48-11e7-9a45-edd8da5254ec.png)
![img-headerlogo 3x](https://user-images.githubusercontent.com/4369856/31372062-d0df6006-ad48-11e7-99b1-ebfc5950bdd2.png)
![img-uphold-logo](https://user-images.githubusercontent.com/4369856/31372063-d0f77074-ad48-11e7-9f11-b7d0f4e11627.png)
![img-uphold-logo 2x](https://user-images.githubusercontent.com/4369856/31372065-d10daede-ad48-11e7-8651-6adbbdccdd53.png)
![img-uphold-logo 3x](https://user-images.githubusercontent.com/4369856/31372066-d12d3ff6-ad48-11e7-912c-bf76dfd0992a.png)

**Comment by jenn-rhim** [comment]
@lgebhardt  -- box shadow for all boxes we have in the dashboard and the verification process

box-shadow: 1px 1px 3px 0 rgba(47,48,50,0.15);

**Comment by jenn-rhim** [comment]
![icn-verify](https://user-images.githubusercontent.com/4369856/31418734-b70f9b56-adec-11e7-992b-1fe757e7551d.png)
![icn-verify 2x](https://user-images.githubusercontent.com/4369856/31418735-b72762b8-adec-11e7-9bbe-cc627220df0a.png)
![icn-verify 3x](https://user-images.githubusercontent.com/4369856/31418736-b740a2f0-adec-11e7-8f9c-ba96ade70593.png)

**Comment by jenn-rhim** [comment]
@lgebhardt -- not sure why sketch added margin in icn-uphold when exported the assets -- still need to figure that out so i can avoid this type of issue.  but i fixed it and posting them here.

![icn-uphold-logo 1x](https://user-images.githubusercontent.com/4369856/31560403-fa5f67c4-b008-11e7-9970-35ca74231646.png)
![icn-uphold-logo 2x](https://user-images.githubusercontent.com/4369856/31560404-fa7c472c-b008-11e7-91b3-881f44175fef.png)
![icn-uphold-logo 3x](https://user-images.githubusercontent.com/4369856/31560405-fa94518c-b008-11e7-8271-48ce62935006.png)

**Comment by jenn-rhim** [comment]
@lgebhardt : bat logo

![icn-bat_logo](https://user-images.githubusercontent.com/4369856/31562359-efa4d13c-b00f-11e7-9d63-99418c2b07f6.png)

![icn-bat_logo 2x](https://user-images.githubusercontent.com/4369856/31562360-efd297a2-b00f-11e7-8971-8daea0e6daff.png)
![icn-bat_logo 3x](https://user-images.githubusercontent.com/4369856/31562361-efeb97c0-b00f-11e7-85cb-5bdcd076184d.png)

**Comment by jenn-rhim** [comment]
@lgebhardt  It was such a pain to regenerate all of them the way that makes it easy to pop in the slot due to the different text sizes, but finally figured it out.  here... 


![icn-avatar](https://user-images.githubusercontent.com/4369856/31567696-ab8ea8d6-b025-11e7-887b-ebdfbc841600.png)

![icn-avatar 2x](https://user-images.githubusercontent.com/4369856/31567697-abc0e6b6-b025-11e7-8801-19c2b57bd5f2.png)
![icn-avatar 3x](https://user-images.githubusercontent.com/4369856/31567698-abda0e5c-b025-11e7-8dbf-518c9b040e27.png)
![icn-download](https://user-images.githubusercontent.com/4369856/31567700-abf1b7be-b025-11e7-98dc-991db1b08fcf.png)

![icn-download 2x](https://user-images.githubusercontent.com/4369856/31567701-ac24c884-b025-11e7-9db2-5c3e6ad05646.png)
![icn-download 3x](https://user-images.githubusercontent.com/4369856/31567702-ac3be56e-b025-11e7-94d7-678e8b30a326.png)
![icn-list](https://user-images.githubusercontent.com/4369856/31567704-ac536cde-b025-11e7-82b8-49cfb9384cd8.png)

![icn-list 2x](https://user-images.githubusercontent.com/4369856/31567706-ac836844-b025-11e7-932b-3d61408b282f.png)
![icn-list 3x](https://user-images.githubusercontent.com/4369856/31567707-ac9bdfd2-b025-11e7-91e9-099577b86838.png)
![icn-wallet](https://user-images.githubusercontent.com/4369856/31567708-acb2ab2c-b025-11e7-8e10-46f47721ebd4.png)

![icn-wallet 2x](https://user-images.githubusercontent.com/4369856/31567709-acdf73dc-b025-11e7-90dd-b0ff0ba39b5a.png)
![icn-wallet 3x](https://user-images.githubusercontent.com/4369856/31567710-acf95de2-b025-11e7-9f8d-6246ce1fda02.png)

**Comment by jenn-rhim** [comment]
Responsive progress indicator 

![screen shot 2017-10-13 at 12 33 41 pm](https://user-images.githubusercontent.com/4369856/31568277-5098a244-b028-11e7-866a-ddfd73c57ef2.png)
![screen shot 2017-10-13 at 12 30 45 pm](https://user-images.githubusercontent.com/4369856/31568282-552db268-b028-11e7-9752-5c30a2f60de5.png)

**Comment by jenn-rhim** [comment]
@lgebhardt 

![image](https://user-images.githubusercontent.com/4369856/31568380-e8287c7e-b028-11e7-929f-ef5588fab32e.png)
