### ISSUE TITLE
Downloads / Installs - changes needed in Publisher dashboard

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1383]
Two asks;

a) Need to include downloads (actual intent to download binary) into the Publisher dashboard with helper logos
b) Move the admin console functionality for codes to be the same for the Publisher dashboard

Downloads: Intent to download the binary
Install (First Open): Binary installed and opened first time
Confirmations: User is active for 30+ days

and c) need to email Publisher owners that terminology change as well.

cc @jenn-rhim @dlipeles

**Comment by yachtcaptain23** [comment]
Should be resolved as part of CRM 1.1

**Comment by yachtcaptain23** [comment]
Can use UI from https://github.com/brave-intl/publishers/issues/1433 as a guide
