### ISSUE TITLE
Promo Reports are possibly offset by a day

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1395]
When we generate Promo Reports, we probably want to see all the metrics inclusive of this moment. The current logic suggests "Today", which might mean tomorrow given the data is stored in UTC and we're in America. 

I'll be submitting a fix to adjust the dropdown menu default to UTC rather than using an American timezone.

**Comment by nvonpentz** [comment]
Also, the date picker allows users to select dates that do not exist e.g. Nov. 30th.  I believe the dashboard throws an error in that case.  We should only allow admins to select valid dates or display back the error to the user if not possible.
