### ISSUE TITLE
Do not apply fee when displaying referral payment balance

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1404]
The Eyeshade::Wallet is mostly composed of Eyeshade::Balances.  There is one balance per channel, and then one overall balance which includes all the channel accounts and the publisher account (for referrals).  The overall balance is known as the contribution balance:  https://github.com/brave-intl/publishers/blob/staging/lib/eyeshade/wallet.rb#L34.  At the moment, fees are automatically applied to any kind of Eyeshade::Balance during initialization: https://github.com/brave-intl/publishers/blob/staging/lib/eyeshade/balance.rb#L5.  The problem is that we are applying a fee for the entire the contribution balance which may also include referral payments.  We must only apply fees for channel accounts, not publisher (referral) accounts.

**Comment by yachtcaptain23** [comment]
Solved in #1438
