### ISSUE TITLE
Issue: Need valid/correct number on verified publishers 

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1413]
We need to have a source of truth that consistently reflects;

a) total verified publisher counts
b) total verified channel counts
c) total YT channel counts
d) total Twitch channel counts

added to the Admin Console dashboard.
and sync'd with stats.brave.com for consistency reasons.

@yachtcaptain23 this is a P1 - would be good to get a fix quickly.

**Comment by nvonpentz** [comment]
@mandar-brave What constitutes a verified publisher?  We can give you email verified, uphold verified, publishers with at least one verified channel, or some combination of those.
