### ISSUE TITLE
Add missing step for github verification flow

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#142]
On the updated 4.e in https://github.com/brave-intl/publishers/issues/50 we are missing a necessary instruction. The user needs to make sure that an empty file named '.nojekyll' exists in the root of the repo.

It would be best to update the copy so that step 1 informs the user to add the file. We'll then increment the other steps to 2 and 3 respectively.

The copy for Step 1 :  "Please make sure to add an empty file named '.nojekyll' to the root of your repo."

**Comment by mrose17** [comment]
Waiting for @alexwykoff to test; otherwise this is considered done.

**Comment by alexwykoff** [comment]
confirmed new step present in *.github.io flow
