### ISSUE TITLE
(Marketing|Publisher) Partner Dashboard

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1433]
![1-dashboard](https://user-images.githubusercontent.com/8647607/49823185-f3307a00-fd33-11e8-99d3-66b6c2ec794f.png)

![image](https://user-images.githubusercontent.com/8647607/49823238-0ba09480-fd34-11e8-9206-df05fcb2181b.png)

**Comment by dlipeles** [comment]
This will be a part of the forthcoming `V3 Publishers UI` epic, removing from the crm1.1 milestone

**Comment by corymcdonald** [comment]
Closing this issue, there are new redesigns to implement and we will be segmenting them into individual issues like "Refactor the wallet" rather than one master issue
