### ISSUE TITLE
Partner Referrals 

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1437]
![3-referrals-home](https://user-images.githubusercontent.com/8647607/49837362-ef641e00-fd5a-11e8-80f9-85efc4139188.png)
![4-create-code](https://user-images.githubusercontent.com/8647607/49837367-f428d200-fd5a-11e8-97f6-8e13255f7a94.png)
![image](https://user-images.githubusercontent.com/8647607/49837391-09056580-fd5b-11e8-9330-95a5b3fa0481.png)
![image](https://user-images.githubusercontent.com/8647607/49837395-0b67bf80-fd5b-11e8-93e7-9d8472f25985.png)
![image](https://user-images.githubusercontent.com/8647607/49837396-0e62b000-fd5b-11e8-9e40-c920def7188d.png)
![image](https://user-images.githubusercontent.com/8647607/49837402-128ecd80-fd5b-11e8-9182-dc20d69772a5.png)
![image](https://user-images.githubusercontent.com/8647607/49837404-14f12780-fd5b-11e8-91b8-1ac355970e9f.png)

**Comment by dlipeles** [comment]
@corymcdonald Hey Cory after you left the meeting I volunteered to build the foundation for the referrals page (set up react-rails, create the grid, add blank cards.) Then we can wire it in together. 

What are your thoughts on using modals as we see in the screenshots? Personally I think they're great for desktop users, but not usable for mobile users. 

Our first focus will be on desktop users so we'll have that covered, but I think this'd be a good opportunity to think about some ways we could present modal content in a mobile friendly way 

Hopefully we could apply that solution to the Tipping Banner as well

**Comment by yachtcaptain23** [comment]
Merged in with https://github.com/brave-intl/publishers/pull/1589
