### ISSUE TITLE
Brave rewards banner creator doesn't parse usernames 

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1444]
Log into the publishers dashboard and attempt to add a Twitter, Twitch, or YouTube link to your profile. If you just enter a username, it should be parsed into the profile URI for that service.

ref: https://github.com/brave/brave-browser/issues/2502

cc @tomlowenthal

**Comment by mandar-brave** [comment]
cc @dlipeles

**Comment by dlipeles** [comment]
Moved to #1902
