### ISSUE TITLE
Unnecessary Scrollbars

### ISSUE THREAD

**Issue by jonathansampson** [brave-intl/publishers#1447]
![image](https://user-images.githubusercontent.com/815158/50025599-b2db3100-ffab-11e8-9b7a-52c915f2731f.png)

![image](https://user-images.githubusercontent.com/815158/50025621-c25a7a00-ffab-11e8-9b0c-a1e073abe61e.png)

**Comment by corymcdonald** [comment]
Hey there @jonathansampson I was wondering the following

1. What OS
1. What web browser you're using?
1. Do you have a mouse plugged in?

**Comment by yachtcaptain23** [comment]
@corymcdonald I spoke with @jonathansampson . He's using Windows 10 Brave Browser. I would assume yes, he has a mouse plugged in.

**Comment by jonathansampson** [comment]
1. Windows 10 (1803, 17134.441)
2. Brave (Version 0.57.18 Chromium: 71.0.3578.80) (Official Build) (64-bit)
3. Yes, mouse is plugged in.

**Comment by dlipeles** [comment]
I can fix this, I was planning to do a sweep this weekend and cleanup many of these quality issues. 

This issue happened to be on my backlog as well, will follow up on this thread.

**Comment by dlipeles** [comment]
Closed as part of #1465
