### ISSUE TITLE
Need temporary message to Publisher re: Custom Tip ad

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1475]
In V0.58 of the build, two features that the browser is not executing on is "Unable to pick the custom tip in Brave Browser V0.58 and will only provide choices of 1. 5, 10 BAT"

The second issue is the Browser V0.58 is also not picking up the Custom image when a Brave user/patron has tipped the Publisher.

See issues:
Issue: https://github.com/brave/brave-browser/issues/2645
Issue: https://github.com/brave/brave-browser/issues/2668

For all existing Content creators that will create the Custom Banner, on Submit we will need to pop a dialog that lets the Content creator know that "The Custom tip selected for the banner will show up as 1, 5, 10 BAT only for V0.58 of the Brave Browser"

@dlipeles @jenn-rhim

**Comment by dlipeles** [comment]
Closed in #1469
