### ISSUE TITLE
Creating the referral report by pinging the referral server might exceed http header limits

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1479]

**Comment by nvonpentz** [comment]
Reducing the batch size is one easy option https://github.com/brave-intl/publishers/blob/f63b2d83e8b251003e18cadacd3ba1c5de4c8764/app/services/promo/registrations_stats_fetcher.rb#L4

Another option might be to change the params from `referral_code=XXX999` to `rc=XXX999`.
