### ISSUE TITLE
[Bug] A user can have both a non-null pending_email and a non-null email

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1484]
Seems like there's 51 cases. Perhaps it's some weird race condition for updating a record.

**Comment by nvonpentz** [comment]
I think this is expected.  If an existing publisher requests an email address change, their `email` will be their existing email address and `pending_email` will be their desired email address.  Only when they confirm their pending email address will `email` be updated to the new value and `pending_email` become `nil`.
