### ISSUE TITLE
Display last settlement balance, total amount settled, and balance on admin publishers#index

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1489]
Related to https://github.com/brave-intl/publishers/issues/1436

It would be useful for business development to know how much money a publisher has made and how much they will be paid during the next settlement just by looking at the list of publishers.  Ideally we should be able to sort the list of publishers on this criteria by clicking on the column headers.  That way we can find the highest earners quickly.

The challenge is that this information is not stored in the publisher database, and is requested on demand via the eyeshade API.  It's easy enough to request all the information needed with a few API calls for a single page of publishers, however we will not be able to sort on this information unless it is loaded into memory for every single publisher, which is unrealistic with the current APIs.

**Comment by yachtcaptain23** [comment]
eV will follow up with sort and pagination for Eyeshade.

**Comment by yachtcaptain23** [comment]
@yachtcaptain23 to follow up and see if this is satisfied by the top balances endpoint.

**Comment by tsmartt** [comment]
Closing as already implemented.
