### ISSUE TITLE
Partner Payments 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1531]
![11-payments-states](https://user-images.githubusercontent.com/4713771/51137562-d5f83b00-180c-11e9-9a24-9746b28dab10.png)

![image 3](https://user-images.githubusercontent.com/4713771/51137573-db558580-180c-11e9-9450-fc3efd8e7a08.png)

**Comment by yachtcaptain23** [comment]
Spoke with ev: we think we should include this as part of the settlement report and flag as a partner payout, and skip any concept of manual payout by admin users.

**Comment by yachtcaptain23** [comment]
Closed by https://github.com/brave-intl/publishers/pull/1620
