### ISSUE TITLE
Statements not generated for referrals

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1532]
When there are referrals the transaction list looks like this
```ruby
{"created_at"=>"2018-12-03T06:24:34.000Z", "description"=>"referrals through Dec", "channel"=>"XXXXXXXXXX", "amount"=>"29.148579608662246634", "transaction_type"=>"referral"}, 
```

When we try to find by a channel identifier since the identifier is XXXX it's not valid
https://github.com/brave-intl/publishers/blob/09b4756254c02ce3f5c86a5183610814b719ded6/app/services/publisher_statement_getter.rb#L44

https://sentry.io/brave-software/publishers-production-t2/issues/844816929/?referrer=slack

**Comment by yachtcaptain23** [comment]
@corymcdonald this is possibly stale. Would you check?

**Comment by corymcdonald** [comment]
Closing this addressed by Ledger -
https://github.com/brave-intl/bat-ledger/issues/575
https://github.com/brave-intl/bat-ledger/issues/694
