### ISSUE TITLE
Update e-mail styling for client edge cases

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1556]
The new e-mails appear to look good in most clients, however there are edge cases we should investigate for consistency. Perhaps we could request some help from QA. 

By market share the top e-mail clients are 

- [ ] Apple iPhone
- [ ] Gmail
- [ ] Apple iPad
- [ ] Outlook
- [ ] Apple Mail
    - [ ] Dark Mode
- [ ] Yahoo! Mail

Example: dark mode on Apple Mail

![screen shot 2019-01-23 at 3 23 24 pm](https://user-images.githubusercontent.com/4713771/51714261-af9f8000-2002-11e9-946a-08fb2ae3a30a.png)

New e-mails on the left, legacy counterpart on their right. 

![51205836-a6543c00-18bb-11e9-9d91-a4366d96e8a5](https://user-images.githubusercontent.com/4713771/51714672-ff327b80-2003-11e9-8aae-2ee523865f7c.png)

**Comment by tsmartt** [comment]
Closing as stale.
