### ISSUE TITLE
Optimize SiteBanner data in channels list 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1557]
API involved - `api/v1/public/channels`

We can optimize the size of our channels json by excluding any SiteBanners that match the pattern of a default Site Banner. 

ie. 

```ruby
{
"channel_id":"00b0eadb-bfdc-43f6-89d7-ff93e72c60a5",

"title":"Brave Rewards","description":"Thanks for stopping by. We joined Brave's vision of protecting your privacy because we believe that fans like you would support us in our effort to keep the web a clean and safe place to be.\n\nYour tip is much appreciated and it encourages us to continue to improve our content.",

"backgroundUrl":null,

"logoUrl":null,

"donationAmounts":[1,5,10],

"socialLinks":{"youtube":"","twitter":"","twitch":""
}
```

There are two approaches here

1. Exclude any SiteBanner data that matches the default pattern above `exactly`, the advantage is that the client will not need to implement anything new, as it already knows how to render a default banner if no data is supplied. Drawback is that we won't save space if the user changed anything on the banner, as we need to send the entire object in that case. 

2. With collaboration from the browser team, allow a possible `default` value for the text field, in which case the browser will render the default banner text. 

ex. 
```ruby
   description: default
```

 Drawback is the client will need to make code changes as well to interpret `default`.

**Comment by yachtcaptain23** [comment]
GZIP compression uses huffman encoding. This won't save us much space. Closing.
