### ISSUE TITLE
New nav bar

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1559]
Screenshots in https://github.com/brave-intl/publishers/issues/1437

**Comment by dlipeles** [comment]
Blocked. We can proceed with CRM1.1 using this stopgap 
![screen shot 2019-02-11 at 9 49 10 pm](https://user-images.githubusercontent.com/4713771/52608154-fa185d80-2e46-11e9-87d9-a0c3103c4836.png)

**Comment by dlipeles** [comment]
For UI 3.0 we need 

- Spec for the Channels Page
- Where we will put the Tipping Banner button
- If we will still have an Add Channels link in the Nav

cc @jenn-rhim 

![screen shot 2019-02-11 at 9 51 29 pm](https://user-images.githubusercontent.com/4713771/52608233-3d72cc00-2e47-11e9-9ad0-1b019cbcbd89.png)

**Comment by yachtcaptain23** [comment]
Closed by https://github.com/brave-intl/publishers/pull/1589/files
