### ISSUE TITLE
Notify user that channels will take 24 hours to appear in the web browser

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1564]
When publishers add websites there have been quite a few support tickets that their channels aren't appearing as verified. When the user has completed their channel upload we should display a message that it can take up to 24 hours for their channels to appear as verified.

**Comment by dlipeles** [comment]
note - Could be up to 48h currently, but will soon be 24h.

**Comment by Miyayes** [comment]
+1 from Reddit: https://www.reddit.com/r/BATProject/comments/atjkxg/delay_period_after_verification_one_suggestion/

>After a user has registered his website/youtube channel, inform him that "people will be able to TIP once their browser is update: this happens automatically every 48h or can be done manually by going to the settings". Something like that.

**Comment by corymcdonald** [comment]
This is generating a lot of support questions - let's try and prioritize this

**Comment by yachtcaptain23** [comment]
Merged as part of https://github.com/brave-intl/publishers/pull/1684
