### ISSUE TITLE
Show negotiated contract values

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1571]
To compute "Payment Total" for Partner Payments, we'll need to know the negotiated contract values multiplied by per download/confirmation/etc.

This issue will track the migration and implementation in admin

**Comment by yachtcaptain23** [comment]
Had a discussion: This is out of scope on our part.

**Comment by mandar-brave** [comment]
Ideally, we should not parse any reports. Eventually we will standardize reports for partners to enter but this is V1.

Keep it simple and ensure that partners can upload values which are outcomes for downloads, installs, confirmations -- do not make it mandatory for them to enter them, however. An an example one partner may be paid on downloads, some other on CPM, some others on installs, some others on some other metrics.

Our current report gathering, generation system is not built to be very flexible today.

@yachtcaptain23

**Comment by yachtcaptain23** [comment]
Just spoke with business development: 90% of agreements follow a standard protocol. Should prioritize if possible to save BD time.

**Comment by mandar-brave** [comment]
@yachtcaptain23 i dont agree with the assessment above. Please ask BD for contracts - i agree that variables are still downloads, installs, and confirmations but it is along with some other set of variables.

**Comment by yachtcaptain23** [comment]
Until this is requested, we're closing this. Re-open if necessary.
