### ISSUE TITLE
Align UI with the organization permissions

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1586]
We have a list of permissions for an organization and we should update our UI to toggle them on and off. In addition we should confirm that our Rails code also blocks the UI action so people can't send HTTP requests and still preform the action

**Comment by corymcdonald** [comment]
I think there's a discussion to be had about what to do with these actual permissions. Do we keep them per user? Per organization? 

Albert is leading the effort with structuring a change to the Organization model and what that means to the consumers of this code

**Comment by yachtcaptain23** [comment]
Spoke with @mandar-brave, we're tabling this until it's needed given that UI is in constant flux.
