### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by karenkliu** [brave-intl/publishers#1592]
## Description
Update the publishers landing page so that:
- The user understands what is a publisher, the benefits to being a publisher, and how Brave Rewards works
- Recent functionality is promoted; e.g. Twitter user can be a publisher (should be scaleable)
- The page provides help and support
- Sign up is highly visible as the main CTA
- The page is responsive across all breakpoints

## Designs
![pub landing - desktop hd](https://user-images.githubusercontent.com/2388823/52677205-dfdf8d80-2ee1-11e9-8b78-29167ce527f3.jpg)

The landing page has a sticker header/navigation bar so sign up is always in view:
![pub landing - sticky header](https://user-images.githubusercontent.com/2388823/52442994-660e6500-2ad9-11e9-8ed0-d35525238365.jpg)

The social proof section is a rotating carousel of testimonials that we can switch out to keep the content fresh.
![pub landing - social proof carousel](https://user-images.githubusercontent.com/2388823/52443026-80e0d980-2ad9-11e9-94ba-1e50cb577fd0.jpg)

## Specs
The page content follows a responsive, 12-column layout grid:

![responsive layout grid](https://user-images.githubusercontent.com/2388823/52444059-2b59fc00-2adc-11e9-929d-9300962814ea.png)

The typography on the page also has responsive rules:

![typography variables](https://user-images.githubusercontent.com/2388823/52450355-7e897a00-2aef-11e9-8127-9e3889dfffb0.png)

![responsive - navigation bar](https://user-images.githubusercontent.com/2388823/52677275-2503bf80-2ee2-11e9-9e54-43557190d387.png)

![responsive - section 1](https://user-images.githubusercontent.com/2388823/52677287-2d5bfa80-2ee2-11e9-8877-aadd4b8a6109.png)

For example:
![rotating title_example](https://user-images.githubusercontent.com/2388823/52679218-369c9580-2ee9-11e9-9e63-38c58dcf321b.gif)

![responsive - section 2](https://user-images.githubusercontent.com/2388823/52446857-108b8580-2ae4-11e9-8683-97ac6ed17836.png)

![responsive - section 3](https://user-images.githubusercontent.com/2388823/52677332-554b5e00-2ee2-11e9-843e-01645ab06603.png)

![responsive - section 4](https://user-images.githubusercontent.com/2388823/52677346-5f6d5c80-2ee2-11e9-9caf-223b68a6c790.png)

![responsive - footer](https://user-images.githubusercontent.com/2388823/52450195-decbec00-2aee-11e9-8655-6d70e81c12c4.png)

Grab the image and SVG assets from this ZIP folder:
[assets.zip](https://github.com/brave-intl/publishers/files/2882489/assets.zip)

For more CSS and plain text, check Abstract link: https://share.goabstract.com/16f12a89-94da-4b02-a395-75e5bd61cbc5

**Comment by corymcdonald** [comment]
Thank you for doing this Karen! It looks great. I can't wait to get this incorporated. 

Just some minor feedback, that's the old twitter logo and they've explicitly forbidden people from using it. In addition our app doesn't support tipping for twitter yet 😅

I don't know if we should put coming soon section unless we have definite plans to add those per the roadmap or a major release 🤔 

I also think that we should probably incorporate your background into the background of the app because currently it has this hot pink gradient taht would make it kind of look out of place 😄

**Comment by karenkliu** [comment]
Hi @corymcdonald, thanks for your feedback! In response:

- I took out Twitter in the rotating title
- I took out the 'Coming Soon' section
- I removed the geometric embellishment in the background SVGs to simplify it

I updated the specs + assets with these changes.

**Comment by karenkliu** [comment]
Hi @jonathansampson, per your feedback I updated the SVG assets so that we are using a smaller white wave graphic to achieve the same visual effect rather than different variations of the gradient bg.

**Comment by petemill** [comment]
Minor: how about separate logo graphics so that they can just automatically flow to multiple lines, instead of 1 for 'large' and 1 for 'small'?

**Comment by jonathansampson** [comment]
This will unfortunately be pushed back at least a week due to MWC.

**Comment by yachtcaptain23** [comment]
Closed by #1786

**Comment by rossmoody** [comment]
🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊
