### ISSUE TITLE
add a additional state for "Next Deposit Date:" display - "Payout In Progress"

### ISSUE THREAD

**Issue by evq** [brave-intl/publishers#1594]
when performing the monthly payout we often get user confusion as they may see their balances paid out in part, without the balance on their dashboard being updated. this is an artifact of the payout procedure.

it might be helpful if we were to have an alternate state for the "Next Deposit Date:" bit of text - whereby an admin can set a payout as "in progress" so that users know payout is ongoing

**Comment by corymcdonald** [comment]
Request from telegram: 
>since the cutoff is on the first, maybe in the next UI upgrade on the dashboard, have a "pending on dep date" and total pending, so people know what they have coming on the due date vs what they got after the cutoff

**Comment by evq** [comment]
Maybe we should call the balance `balance` and the amount pending in the payout report `pending payout`? Current use of the word pending could be adding confusion
