### ISSUE TITLE
Add analytics to each step of the publisher registration flow

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#16]
To analyze the effectiveness of our terminology and requirements of technical difficulty, we need to have some means of measuring the number of users who successfully visit and interact with each page in the flow.

Each page needs to have a measurement of:
1. How many users have visited a page.
2. How long users spend on the page on average.

There also needs to exist an easy means for designers and engineers to view the accumulated stats to compare page success.

**Comment by alexwykoff** [comment]
cc @ayumi @bradleyrichter

**Comment by alexwykoff** [comment]
mr : what do we need to be doing here?

ay : don't use GA

aw : piwik seems to work for brave.com, shall we try it here?

ay : @diracdeltas may know more about config, but probably should work

mr : we should probably use piwik. 

bc : i concur

mr : can we concat with https://github.com/brave/publishers/issues/65 ? 

aw : sure

to summarize : we should add piwik and properly display stats per stage in flow

**Comment by diracdeltas** [comment]
@mrose17 asked me to post how to add piwik to a site.

1. login to analytics.brave.com as the super user (username 'user' in 1p4t)
2. follow instructions at https://piwik.org/docs/manage-websites/#add-a-website to add a website
3. configure the privacy settings to be as strict as possible without breaking the site: https://piwik.org/docs/privacy/

**Comment by mrose17** [comment]
@diracdeltas - thanks!
