### ISSUE TITLE
Support manual payout report generation

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1603]
We'd like manual payouts to be tracked in Eyeshade, so we should include these transactions in the payout reports.  Let's create a new type of payout report entry, with the same fields as the rest except:
```
{
  "type": "manual", 
  "documentId": "fba98492-8ed7-4f9b-a2f6-dc62dcd0c1a3", // uuid of the authorized invoice
  "authority": "nick@brave.com" // email of BD team that approved the payment
}
```

Admins should be able to generate payout reports including only manual payments so we can they can do this outside of the monthly cadence easily.

**Comment by corymcdonald** [comment]
When they payout report is generated would you imagine that this is going to be done on an individual partner or like for every single partner in the system, like we do for the current publishers?
@nvonpentz

**Comment by nvonpentz** [comment]
I'm thinking probably for every partner, since it will be easier to payout many partners and because I'm not sure there are any cases when BD will authorize payment but does not want them to be paid immediately.

We could do both: generate a payout report for all partners on the payout reports page, and generate a payout report for a single publisher on publishers#show, but I think the latter is probably unnecessary.  @evq please let us know if you have an opinion.

**Comment by yachtcaptain23** [comment]
Blocked until wallet refactor is merged: https://github.com/brave-intl/publishers/pull/1438
