### ISSUE TITLE
Support posting of settlement report via admin dashboard

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1604]
Typically settlement reports are uploaded to Eyeshade through the swagger interface.  With manual payments, it makes sense to move this interface to the publishers dashboard since Publishers needs to process these payments by marking the unpaid invoices as paid before forwarding on to Eyeshade.  The flow will be:

1. Admin uploads settlement report to admin dashboard
2. For each manual settlement, Publishers looks up the corresponding unpaid invoice via the documentId, and marks the corresponding invoice as paid
3. Publishers forwards the settlement report to eyeshade via `POST /v2/publishers/settlement`

Related to https://github.com/brave-intl/bat-ledger/issues/519

**Comment by nvonpentz** [comment]
@corymcdonald based on the conversation in https://github.com/brave-intl/bat-ledger/issues/449, a file upload option seems preferable.

**Comment by yachtcaptain23** [comment]
Partially blocked by #1603.
