### ISSUE TITLE
Benign users are getting throttled too frequently

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1627]
I'm seeing this issue too locally. I believe there's a bug somewhere where we refuse the click-to-login maybe 25-50% of the time. I haven't figured out where it's happening quite yet. One workaround is we double the throttle limits for login.

**Comment by tomlowenthal** [comment]
What about the fact that people are seeing their links expire faster than half an hour?

**Comment by yachtcaptain23** [comment]
Linked to https://github.com/brave-intl/publishers/issues/733

It might be due to papertrail causing problems. Investigating paper trail as a possible issue too.

@tomlowenthal yes, we've been experiencing that on occasion. Still investigating.

**Comment by yachtcaptain23** [comment]
Might change subject header due to gmail collapsing emails of the same subject header.

**Comment by corymcdonald** [comment]
@tomlowenthal What if we generate a random UUID in the body as opposed to in the subject. We essentially just don't want gmail collapsing these emails. The ideal solution is to implement webauthn for this

**Comment by tomlowenthal** [comment]
Unique content in the body isn't necessarily going to prevent the collapse. Are we sure that collapsing is confusing people? Ultimately though, I'm 100% on board for webauthn as the real fix.
