### ISSUE TITLE
Investigate Channel API Delay 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1641]
Received a report of a channel being verified but not appearing in 
```
/api/v1/public/channels
```
Until a day later 

We should 
1. Test to see if this is the case
2. Remediate if any delays

Possible causes
We updated some cache headers to support browser functionality, let's make sure it didn't affect publishers cache in some way.

**Comment by yachtcaptain23** [comment]
Until we get more concrete details, we're tabling this.
