### ISSUE TITLE
Include verified / unverified on top balances page 

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1653]
Feature request to include the verified / unverified websites on the top balances page so that BizDev and Jimmy can go through and try and establish partnerships with the websites that have the largest unresolved balances 🎉

**Comment by corymcdonald** [comment]
Possibly can also integrate the Alexa APIs on this as well #1336

**Comment by jsecretan** [comment]
Yeah I think this would be easiest to include as just a separate column.

**Comment by yachtcaptain23** [comment]
Resolved by top balances.
