### ISSUE TITLE
Remove 2FA and ensure publisher state is not verified 🌻 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1696]
After 14 days of the 2FA Removal Job, 

1. Remove the Publisher's 2FA 
2. Remove the Publisher's Channels 
3. Ensure the Publisher's state for the next 30 days is `not verified` 
4. Ensure no changes to uphold wallet (May be out of scope, we will ask @mandar-brave)

**Comment by yachtcaptain23** [comment]
Completed by #1652
