### ISSUE TITLE
Track publishers which need admin approval

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1701]
Right now anyone who verifies a channel which gets flagged for admin approval is flagged silently. This  issue will show the 

(1) List of pubs that have been flagged for admin approval.
(2) Show how many pubs need attention on the admin dashboard
(3) Email us when a publisher gets flagged for admin approval.

**Comment by dlipeles** [comment]
We should follow up with Luke Mulks, and see if we don't want to repeal this feature altogether. 

See [discussion](https://bravesoftware.slack.com/archives/C0KHGGEUW/p1555000957102300?thread_ts=1554957966.091700&cid=C0KHGGEUW)

It would make sense to remove this for the reasons mentioned ^

As well as the fact that we do not require this approval process for even higher value Youtube or Twitch Channels.

**Comment by yachtcaptain23** [comment]
Resolved by https://github.com/brave-intl/publishers/pull/1828
