### ISSUE TITLE
CleanStaleUpholdDataJob errors before completion

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1703]
https://sentry.io/organizations/brave-software/issues/930290474/events/ba502580ed40484795d5cb8a07f656a0/?project=225116&statsPeriod=14d

Possibly a consequence of https://github.com/brave-intl/publishers/commit/15132280d10b6a8a060c0fe691b99901a439bf7d

**Comment by yachtcaptain23** [comment]
No longer reproduced as seen in https://sentry.io/organizations/brave-software/issues/?project=225116&query=is%3Aunresolved+CleanStaleUpholdDataJob&statsPeriod=14d
