### ISSUE TITLE
fully fix all current github security alerts

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#1707]
https://github.com/brave-intl/publishers/network/alerts is still showing a security alert for Actionview because some deps will accept the unpatched version. it also now shows a security alert for railties (patched in 5.2.2.1)

we should aim to keep these alerts at 0 to reduce noise and know when a new vulnerability is introduced.

**Comment by yachtcaptain23** [comment]
Security alerts are now clear.
