### ISSUE TITLE
Harden publishers#home for 503 errors from Ledger/Eyeshade

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1719]
It seems we'll need to address anything that uses Faraday. Sample trace can be found https://sentry.io/organizations/brave-software/issues/909303464/?project=225116&query=is%3Aunresolved&statsPeriod=14d&utc=false

**Comment by corymcdonald** [comment]
We've discussed 2 approaches 
- Completely make this synchronous with only one call to Eyeshade
- Detach the eyeshade wallet from blocking the loading of the homepage. AKA Everything asychronous

As a temporary solution the following options are being considered
- WalletGetter returns an empty hash `def wallet` while tracking if the first call failed
- One quick hack would be to have an instance variable set in the application controller for `@wallet`

**Comment by tsmartt** [comment]
Closing as stale.
