### ISSUE TITLE
Ability to set/change deposit currency (BAT conversion) on dashboard

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#172]
Allow users (publishers) to define which currency they'd want the BAT to be converted and deposited in their Uphold wallet.

![screen shot 2017-10-13 at 3 15 08 pm](https://user-images.githubusercontent.com/4369856/31568473-6fb14162-b029-11e7-8711-af2307947711.png)

**Comment by mrose17** [comment]
see the example in https://github.com/brave-intl/publishers/issues/178 for what `GET /v2/publishers/{publisher}/wallet` returns

**Comment by mrose17** [comment]
@lgebhardt - also, use the `wallet.preferredCurrency` value as the current value only if you haven't stored something in the database.
