### ISSUE TITLE
Add TOS link to the landing and dashboard pages

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#173]
1. need to create 2 separate TOS pages for Brave Payments:  for users and publishers
    • the pages need to be hosted in https://basicattentiontoken.org/ under FAQ
    • 

2. add links to the respective TOS page from each user-facing feature pages
   • Publisher side:  
          1) Landing page
          2) Dashboard
   • User side:
          

![screen shot 2017-10-13 at 3 36 34 pm](https://user-images.githubusercontent.com/4369856/31568989-5f33cb86-b02c-11e7-9169-68417d3a9d73.png)

![screen shot 2017-10-13 at 3 30 10 pm](https://user-images.githubusercontent.com/4369856/31568923-f637ed06-b02b-11e7-9927-ddab20891a06.png)

**Comment by mrose17** [comment]
the link is https://basicattentiontoken.org/publisher-terms-of-service/

**Comment by mrose17** [comment]
Fixed by https://github.com/brave-intl/publishers/pull/198
