### ISSUE TITLE
Refactor: Move authentication to a separate table

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1730]
Right now authentication lives on the `publishers` table. Because we plan on moving `organizations` table to a role under `publishers`, we'll have to move authentication out. This issue will track the refactor of authentication via email.

**Comment by dlipeles** [comment]
We should hold off on this until we're sure we need per-organization wallets. Given @mandar-brave's crm spec there are no use cases that currently require this. 

We can revisit when the need becomes more clear
