### ISSUE TITLE
New Landing Page 🖼 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1733]
### New Landing Page

![Screen Shot 2019-03-19 at 11 59 46 PM](https://user-images.githubusercontent.com/4713771/54658293-1d1bda00-4aa3-11e9-9005-0d9d4109628e.png)

#### Motivation
We wish to improve the new user experience by providing a more engaging and informational landing page. 

#### Goals

* Update the legacy landing page
* Move the publishers app from `publishers.basicattentiontoken.org` to `creators.brave.com`
* Ensure the existing resources on `bat.org` are still accessible
* Ensure `publishers.bat.org` redirects to `creators.brave.com`
* Fastly integration remains working

#### Implementation 
---

- [ ] #1729 
- [ ] #1728
- [x] #1727

**Comment by yachtcaptain23** [comment]
Closed by https://github.com/brave-intl/publishers/pull/1786
