### ISSUE TITLE
New channels list and API that will need to be filtered to only include publishers with uphold accounts that are fully KYC'd (aka isMember)

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1739]
Action items for channel list:
- [ ] New API
- [ ] Compression
- [ ] Add filters for uphold
- [ ] Add filters on ToS
- [ ] Add payout address

**Comment by yachtcaptain23** [comment]
Todo: Also include `uphold_card_id` to the channels list

**Comment by corymcdonald** [comment]
Might be a technical restraint because that data is stored only on Eyeshade and so we'd have to make N calls to Eyeshade to get that information

**Comment by evq** [comment]
eyeshade would internally have to make N calls (it does't keep state other than auth token) - so we have to cache this information either on eyeshade side or publishers side.

I think this is only useful / relevant on the pubs side so would cache here - wdyt? @corymcdonald @yachtcaptain23

**Comment by yachtcaptain23** [comment]
Agree with the above, blocked by https://github.com/brave-intl/publishers/issues/1765
