### ISSUE TITLE
Improve UX and details of Admin Dashboard 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1745]
We will be making various improvements to the UX of the Admin Dashboard. 

### Publisher Details

On the publishers page, we need to ensure the following sections are distinct, readable, and contain all the following details 

#### Payments
- Total contributions (Current Cycle)
- Potential payout
- Detail channel and earnings per channel in current month
- Total confirmations paid out
- Total contributions paid out

#### Referrals 
- Rework charts from stats for each of the ref codes for easy visualization 
- Total downloads (Current Cycle)
- Total installs (Current Cycle)
- Total confirmations (Current Cycle)

**Comment by corymcdonald** [comment]
Add consent to marketing field on page

**Comment by corymcdonald** [comment]
Let's add ordering all the tables by most recent created to this list

**Comment by dlipeles** [comment]
@corymcdonald On second thought I think I can handle this, using the new tabs you created 🎉

**Comment by dlipeles** [comment]
Include these points as well https://github.com/brave-intl/publishers/issues/1436

**Comment by dlipeles** [comment]
Closed in #1821
