### ISSUE TITLE
Improve the Admin Dashboard notes system

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1746]
We want to improve the Publisher notes system by creating a thread system 

- Admins can add notes to older threads 
- All notes are tagged by the admin who created them
- Admins can update old notes (show tag for the update) 
- Threads should be organized by the month

Additionally we need to create some thread features regarding suspension / unsuspension 

1. Prompt admin to create a thread when suspending a user, thread should require a link and description of evidence

2. `Require` admin to create a thread when `unsuspending` a user, thread should require a link and description of evidence

**Comment by corymcdonald** [comment]
Think this might be a good idea to consume ActionText. A new Rails 6 feature that allows for easy commenting etc. 

Rails 6 is currently planning to be released on April 30th, but there's RC 2 out that should make for minimal changes.

**Comment by dlipeles** [comment]
Closed in #1896
