### ISSUE TITLE
Log non-automated e-mails to and from publishers 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1747]
We wish to log a paper trail from suspended publishers, this will likely rely on #1746 being completed first. 

The details of this paper trail are as follows: 

* A new email for Suspended users will be created along the lines of  `suspended@publisher*` 
* Need to notify suspended publishers that they should reach out to `suspended@publisher*` 
* Only the suspended publisher's `account e-mail` can be used to contact `suspended@publisher*`
* When an email is received by a suspended publisher, the email is automatically registered in the Notes section as email from the Publisher.
* Admins should have the ability to use the console for responding (optional)
* The email trail should allow for anyone with admin console access to be able to annotate against the emails.

**Comment by yachtcaptain23** [comment]
Just spoke with Asad and Mandar. It'll make sense to record emails from the Publishers app and integration with the Gmail API will allow to both store the emails and respond back quickly.

**Comment by yachtcaptain23** [comment]
Spoke with Asad, downgrading priority.

**Comment by yachtcaptain23** [comment]
We started storing emails from Zendesk as PublisherNotes. Closing.
