### ISSUE TITLE
update landing page with screenshot of V3 pub dashboard UI

### ISSUE THREAD

**Issue by karenkliu** [brave-intl/publishers#1756]
## Description
Currently there is a big blank space on the right side of the pub landing page that was meant to show a product image. Insert an image of the refreshed V3 pub dashboard UI when it's ready.

## User Feedback
<img width="529" alt="Screen Shot 2019-03-25 at 11 37 27 AM" src="https://user-images.githubusercontent.com/2388823/54945170-75633980-4ef2-11e9-907d-de816fca8342.png">

## Inspiration
Use a product screenshot that conveys something similar to this:
![Screen Shot 2019-03-25 at 1 06 05 PM](https://user-images.githubusercontent.com/2388823/54945158-6e3c2b80-4ef2-11e9-8441-d9bf55104172.png)

**Comment by yachtcaptain23** [comment]
IMO We should make the whitespace highlight Youtube channels or Twitch using a carousel. Here's one example: https://www.twitch.tv/

**Comment by tsmartt** [comment]
Closing as stale, going to open a new, more focused ticket.
