### ISSUE TITLE
Twitch channels can appear duplicate in the Channels API

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1773]
This weird bug might be during contesting. However I have also seen publishers have two of the same youtube channels on their page. 

If you look at a twitch streamer who have transferred their channel to a new page your stream will appear twice in the `api/v1/public/channels` endpoint. 

I would expect that new channel should not appear in the public JSON until the 10 day delay has fully elapsed.

**Comment by dlipeles** [comment]
Related 

https://bravesoftware.slack.com/archives/GE5EHUM7Y/p1554825862006700

---

@nvonpentz 

> I used this to find duplicate verified twitch and youtubers

```count = {}
youtube_channel_ids = YoutubeChannelDetails.select(:youtube_channel_id).group(:youtube_channel_id).having("count(*) > 1").size.keys
youtube_channel_ids.each {|id| YoutubeChannelDetails.where(youtube_channel_id: id).each {|d| if d.channel.verified; count[d.youtube_channel_id] = 0; end}; }
youtube_channel_ids.each {|id| YoutubeChannelDetails.where(youtube_channel_id: id).each {|d| if d.channel.verified; count[d.youtube_channel_id] += 1; end}; }
count.each {|k,v| if v > 1; puts "#{k} #{v}"; end}; nil

count = {}
names = TwitchChannelDetails.select(:name).group(:name).having("count(*) > 1").size.keys
names.each {|id| TwitchChannelDetails.where(name: id).each {|d| if d.channel.verified; count[d.name] = 0; end}; }
names.each {|id| TwitchChannelDetails.where(name: id).each {|d| if d.channel.verified; count[d.name] += 1; end}; }
count.each {|k,v| if v > 1; puts "#{k} #{v}"; end}; nil```

**Comment by dlipeles** [comment]
@nvonpentz 
> It would probably be good to add some alerting if we detect duplicate verified channels as well

**Comment by corymcdonald** [comment]
Believe this can be closed, we might want to investigate other duplicate issues
