### ISSUE TITLE
Add "Check Wallet" or "Re-Connect" button

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#178]
in those cases where the user is already connected to uphold, it would be useful to have a button that goes to https://uphold.com/dashboard, call it "Check Wallet" or whatever.

in those cases where the user has been disconnected from uphold (it happens), eyeshade will tell publishers which will put up a different button "Reconnect" which should basically go to the usual oauth endpoint.

examples of current layout is below.

![1](https://user-images.githubusercontent.com/400552/31676347-2d44d546-b31c-11e7-92dc-27a660da5960.png)
![2](https://user-images.githubusercontent.com/400552/31676348-2d615a0e-b31c-11e7-9aa7-12ce5ae7b7dd.png)

**Comment by mrose17** [comment]
here is an example of what you get from `GET /v2/publishers/{publisher}/wallet`:

    {
      "rates": {
        "ETH": 0.00051121,
        "BTC": 0.000027622925624000002,
        "USD": 0.1586757528082244,
        "EUR": 0.13407180792928677,
        "GBP": 0.12055707671110465
      },
      "contributions": {
        "amount": "0.00",
        "currency": "USD",
        "altcurrency": "BAT",
        "probi": "0"
      },
      "status": {
        "provider": "uphold",
        "action": "authorize"
      }
    }

if status.action is present, the only value (for now) is authorize, which means that the "Connect" button should be presented (again(.

**Comment by mrose17** [comment]
@lgebhardt - `status.action="re-authorize"` but i'm seeing the "Create Uphold Wallet" button. is that intended?

**Comment by lgebhardt** [comment]
That is my understanding of the desired behavior. @jenn-rhim ?

**Comment by mrose17** [comment]
shouldn't it be "Re-Connect with Uphold"? an "Uphold Wallet" has already been created...

**Comment by mrose17** [comment]
Fixed.
