### ISSUE TITLE
Add support for Vimeo publishers

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#1782]
Create channel for Vimeo publishers.
At launch, the browser will support tipping and auto-contributions in terms of payout.

This is a P2; as in if there are no fires, this needs to get prioritized.

cc @yachtcaptain23

**Comment by yachtcaptain23** [comment]
If there's struggles with integrating with Vimeo's API, ping Luke.

**Comment by yachtcaptain23** [comment]
Merged
