### ISSUE TITLE
SetPayoutInProgressJob should initiate before it is the next month in Japan

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#1809]
So we don't show 'next deposit date {1 month away}' when it's actually in 8 days.

**Comment by corymcdonald** [comment]
Why don't we keep the same logic that we had in the view that we had before? 

https://github.com/brave-intl/publishers/blob/c37399c354bc7e5db188b5b5ca3fe1b7dd678fbd/app/helpers/publishers_helper.rb#L23

Might be a none-issue if we do that

**Comment by nvonpentz** [comment]
That works
