### ISSUE TITLE
Improve UX and details of Admin Dashboard II

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1819]
We will be making various improvements to the UX of the Admin Dashboard.

#### Publisher Details
On the publishers page, we need to ensure the following sections are distinct, readable, and contain all the following details

#### Overview
Name of Publisher
Email of the Publisher
Paid to-date
Age of account: signed up on
Consent to marketing field
Was suspended? Highlight and bold with a red colored font
Was unsuspended? Date and Notes

#### Channels
Alexa Rank
Consider using Similar Web APIs

**Comment by dlipeles** [comment]
Lesser priority than #1745

**Comment by yachtcaptain23** [comment]
Seems like most or all of the features are already implemented.
