### ISSUE TITLE
Flash on the homepage

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1826]
When a user's authentication times out we don't have a method for displaying the toast component on the homepage. Therefore it looks like this

![image](https://user-images.githubusercontent.com/5459225/56433435-b5b19f80-6285-11e9-875a-b37025e1a805.png)

We should have the page check to see if there is a flash element on the DOM and then read that into the flash component on mount

**Comment by rossmoody** [comment]
Few questions on this one. 

1. Is the scenario this happens solely related to timing out? If so, could we update the error message to be more approachable and maybe drop them on the login page? i.e. `Your sessions has timed out. Please log in again.` 
2. Can we leverage the toast component that we're using for other alerts for this communication? 

Lastly, I think some of this might be a little out of my code capabilities so I'm going to unassign myself but I can assist if needed (especially if we need a new component to surface this error).

**Comment by corymcdonald** [comment]
outside your code capabilities?!!

<img src="https://media.giphy.com/media/ACcXRXwUqJ6Ok/giphy.gif" />

**Comment by tsmartt** [comment]
Closing as stale.
