### ISSUE TITLE
Audit and update email syntax

### ISSUE THREAD

**Issue by rossmoody** [brave-intl/publishers#1834]
Just noticed in a login email that the from name is Brave Payments. It should probably be Brave Rewards Creators or Brave Creators, right? Was also thinking the subject might make more contextual sense to “Log in to your Creators account” since you’re not really logging into Brave Rewards

**Comment by corymcdonald** [comment]
Agreed, let's tackle this with the new landing page stuff

**Comment by dlipeles** [comment]
Agreed @rossmoody @corymcdonald , I think `Brave Creators` is the right brand to use, and we should use it as the de facto name for the app. `Brave Rewards` should be thought of as the link between `Brave Browser` and `Brave Creators`

**Comment by rossmoody** [comment]
after a break and reading `Brave Creators`, imo that feels really nice

**Comment by rossmoody** [comment]
Thanks so much to @nvonpentz and @atsyed87 for taking care of this!
