### ISSUE TITLE
👨‍💻 Tech Debt 🐛 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1870]
The purpose of this item is to track instances of tech debt that are important enough to log, but not so large that they warrant their own issue. 

These items are owned equally by all contributors, and we ask that enough detail be provided such that any developer can easily pick one up and work on it. 

---

#### Admin Dashboard
- [ ] Refactor publisher payments page to use props from server [(info)](https://github.com/brave-intl/publishers/issues/1870#issuecomment-490539001)

#### API
- [ ] Handle `nil` status update in `api/v1/publishers`

**Comment by dlipeles** [comment]
Reserved

**Comment by dlipeles** [comment]
#### Refactor publisher payments page to use props from server 

It is better to pass props from the server on the first load of a react component, especially in the case of read-only components. Currently the payments component performs an api call on load, we should refactor this to use props first. 

Files :
- `app/javascript/views/admin/payments/Payments.tsx`
- `app/controllers/admin/payments_controller.rb`
- `app/javascript/views/admin/payments/Payments.tsx`

**Comment by corymcdonald** [comment]
@dlipeles Not sure I agree with having it use props because it will take longer to load the page, and having it be an API call on load makes sense if we're going to be making each component into it's own separate call?

**Comment by dlipeles** [comment]
Will move to wikis
