### ISSUE TITLE
[hackerone] link sanitization issue

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1875]
hackerone: https://hackerone.com/bugs?subject=brave&report_id=577426&view=new-and-unassigned&filters%5B%5D=unassigned&substates%5B%5D=new&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1

**Comment by diracdeltas** [comment]
is this just when the user previews their own site banner, or does the XSS also work once the site banner is published so other users can see it?

**Comment by corymcdonald** [comment]
I'm fairly certain it is just when a user previews (Which really makes this not that big of deal). I'm double checking on that assumption though

**Comment by diracdeltas** [comment]
agree - if it's just when a user previews their own banner, this seems to be a self-XSS which we generally consider a non-issue
