### ISSUE TITLE
Spec for SSO with Ads

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1878]

**Comment by dlipeles** [comment]
It sounds like webauthn is the candidate for this, password-less auth is a great idea. 

For usability is there any chance we could support authenticator apps too? Definitely not sms-based auth, but could we consider apps like Google Authenticator, Authy and Duo?

Reason being, most people do not have yubikeys, and many phones (iPhones) don't easily support yubikeys yet. cc @tomlowenthal

**Comment by yachtcaptain23** [comment]
We'll revisit SSO if necessary (likely through Publisher ads)
