### ISSUE TITLE
Brave Rewards Redux

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1887]
This item follows a discussion between @jenn-rhim and I, there are several updates we should make to the Site Banner Editor. These should occur after the v3 UI update

#### Improve Image Editing

Currently a user clicking an image will be taken to a file upload, instead, they should be brought to an image editor and given the choice to either :

1. Reposition and rescale the current image
2. Delete the current image
3. Upload a new image

#### Improve Social Media Entry 

Users should be able to choose the order in which their Social Media Links are displayed, there should be more options for social media links. Additionally, the text entry of social media links should be simplified.

By default we should use verified channels as social links. 

*update* We should use usernames and not URLs #1444 

#### Save vs. Publish feature 

Currently, saving the banner will initiate a broadcast to the Brave Browser, ideally users will be able to save their changes 'locally' and broadcast/publish their banners to the Browsers when they decide to.

#### Channel Indicators 

Banner editor should indicate which type of channel is being edited ie. `Youtube, Site, Twitter, Twitch, etc.` by showing the appropriate icon.  

#### Mobile version of Component

We will create an alternate version of the component for mobile users, using best principles for data entry on mobile devices. 

#### Move to Channels Page

With the new UI, Tipping banner will likely live in the `Channels` page of the Publishers, we will need to decide where it will appear. 

#### Improve Style, Look, and Feel

Various aesethetic improvements, current implementation is crude in certain aspects (Text box highlight, social media link selection, tip selection) 

This should be synced between the Browser Devs and Publishers Devs. 

#### Bug Fixes 

- Re-uploading the same image does not trigger the edit flow (setState is not called)
- Cover image is chopped on the browser https://github.com/brave/brave-browser/issues/2015
- Social media username parsing https://github.com/brave-intl/publishers/issues/1444

**Comment by corymcdonald** [comment]
Are you using Redux as a solution, or as a term describing improvements on the Rewards banner?

**Comment by dlipeles** [comment]
@corymcdonald the latter

**Comment by yachtcaptain23** [comment]
Setting low priority given the volume and questionable amount of usage from users. It takes two steps and non-obvious ones that is to get this to show up on Brave Browser and you should ask them to make the tipping banner more obvious from the client side. 

Additionally, we should keep metrics to see how often this page gets opened up to know if it's worth fixing.
