### ISSUE TITLE
Regression : Dashboard : clicking on 'Edit Contact' does nothing

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#189]
Currently, clicking on the text produces this error in the console.
<img width="1440" alt="screen shot 2017-10-19 at 3 17 28 pm" src="https://user-images.githubusercontent.com/1434040/31792156-b75187be-b4e0-11e7-9806-026165a3210c.png">

**Comment by dgeb** [comment]
Fixed via #193
