### ISSUE TITLE
Use verified channels for tipping banner links

### ISSUE THREAD

**Issue by evq** [brave-intl/publishers#1902]
Freeform unverified URLs are prone to misuse - a publisher may put links to channels that they don't actually own in an attempt to collect tips in someone else's name.

Now that we have twitter support I think all the channel types that we support in the tipping banner are also supported as channels.

We should switch to only allowing a user to select a verified channel for each of the links. It probably makes sense to include a "none" option as well in case a user decides they don't want to show any of their channels.

**Comment by yachtcaptain23** [comment]
@mandar-brave I remember you had disagreements about this when I had proposed the same. Okay for us to implement now that we have Twitter integration?

**Comment by mandar-brave** [comment]
@yachtcaptain23 not against it but feel it's cumbersome. If we do not enforce it, then that is good (that is how i am reading the none option)

@evq we are saying user can always choose none? If so, i am good with it. Goal is not to enforce any authentication.

@evq are puns who use authenticated channels getting some +ve ratings when we score for grants?

**Comment by evq** [comment]
@mandar-brave none in this case means no links are displayed - not fallback to unverified URLs

**Comment by mandar-brave** [comment]
OK for the moment; i will follow up in person. No reason to hold pushing out.
