### ISSUE TITLE
Add responsive styling for Add Channel modal

### ISSUE THREAD

**Issue by rossmoody** [brave-intl/publishers#1904]
Follow up to https://github.com/brave-intl/publishers/issues/1898

With the addition of the new functionality, this section will probably have more eyes on it than usual and it might be a good opportunity to improve the responsive styling.

**Comment by rossmoody** [comment]
Designs ready @dlipeles 

https://share.goabstract.com/6e0a7840-793e-42f5-9013-37129018fb7e

**Comment by corymcdonald** [comment]
@rossmoody Maybe the organization of the tiles should be based on what we feel our top connections will be?

(Also we need to add vimeo which will mess up the perfect alignment 😢)

1. Youtube
2. Twitch
3. Twitter
4. Reddit
5. Vimeo
6. Github
7. Website

**Comment by corymcdonald** [comment]
I've proposed we can add Medium support too, but there's not been a spec or anything written for it 😄
