### ISSUE TITLE
Buttons need padding and Brave/BAT logo isn't hyperlinked 

### ISSUE THREAD

**Issue by srirambv** [brave-intl/publishers#1906]
![image (5)](https://user-images.githubusercontent.com/17010094/58200534-fb0c2700-7ca0-11e9-8a94-41ce39d364a8.png)

Email regarding adding referral link contains button that are missing padding and makes it look like its stuck together. Also the Brave and BAT logo at the bottom aren't hyperlinked to https://brave.com and https://basicattentiontoken.org. 

Checking the mail on Brave release channel on Linux. No specific email client used. 

cc: @rossmoody

**Comment by rossmoody** [comment]
Should also check out mobile formatting:

![Screen Shot on 2019-05-22 at 18:47:35](https://user-images.githubusercontent.com/29072694/58220054-22bfb700-7cc2-11e9-883d-2beed25c6da3.png)

Also @atsyed87, should we amend the copy on these mailers to omit the support email in favor of pushing people to community?

**Comment by tsmartt** [comment]
Closing as stale.
