### ISSUE TITLE
User receiving restricted missing wallet address email

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1912]
Last night when we sent out the emails a lot of users who weren't missing BAT cards saw that there was trouble with their account email message.

We should see if this is accurate, when their bat card was created etc

**Comment by corymcdonald** [comment]
We determined the root cause of this - basically a bad merge had caused the code that creates cards to be deleted. That being said I do think there is an opportunity to create more of a historical view of the account about which users were affected by what.

**Comment by yachtcaptain23** [comment]
Can be closed per @corymcdonald . Apparently this was addressed as part of a bugfix on Eyeshade.
