### ISSUE TITLE
Update definition of Verified Channel 

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1926]
As part of Gemini we'll want to update the definition of a verified channel to be: 

The current definition of verified + Publisher has KYC'd Uphold Connection 

Channels in the json list should only appear as verified (in the browser) if the associated publisher has KYC'd an uphold wallet.

**Comment by yachtcaptain23** [comment]
Merged in via https://github.com/brave-intl/publishers/pull/1954
