### ISSUE TITLE
Rework referrals charts

### ISSUE THREAD

**Issue by dlipeles** [brave-intl/publishers#1951]
There are a few updates to make across the board for our referrals charts

1. Only keep the latest stats data points for a given day: 

Referral stats are sometimes pulled several times a day, we need to choose only the latest data point for any given day (Note - this is not the same as summing all the entries for a day) 

2. Fix admin dash referral chart 

The admin dashboard referrals chart appears to have a bug when there are many data points, this causes errors when hovering over the data or selecting/deselecting datasets. 

3. Replace publisher side referrals chart with the updated charts from `2.` 

Once `1. and 2.` are completed, we should be able to replace the current publisher's referrals chart with the newer version. 

4. Investigate missing referral stats

There have been some reports of missing referral stats, this could be related to `1.` but it'd be best to at least investigate. @matches can show reports from users

**Comment by corymcdonald** [comment]
These stats are also screwed up based on some of the spikes that are happening. I'm going to investigating this based on Sampson's message on our slack about referral code `SGT200`

**Comment by yachtcaptain23** [comment]
Closing as I'll be addressing this in https://github.com/brave-intl/publishers/issues/1970
