### ISSUE TITLE
Dashboard Fails to Report Confirmations

### ISSUE THREAD

**Issue by jonathansampson** [brave-intl/publishers#1959]
The dashboard reports 0 confirmations for some publishers who have ongoing confirmations. For instance, this publisher has not seen any confirmations in several days, in spite of having _thousands_ of DAUs:

![image](https://user-images.githubusercontent.com/815158/59303219-5b1c3a80-8c5b-11e9-87c0-da85ec5063b9.png)

```
select ts::date, count(1) 
  from download 
  where ts::date > '2019-05-01' 
    and finalized and referral_code = '██████' 
group by ts::date 
order by ts::date;

     ts     | count
------------+-------
 2019-05-02 |   152
 2019-05-03 |   106
 2019-05-04 |    82
 2019-05-05 |    68
 2019-05-06 |    58
 2019-05-07 |    33
 2019-05-08 |    16
 2019-05-09 |    86
 2019-05-10 |    65
 2019-05-11 |    78
 2019-05-12 |    13
(11 rows)
```

**Comment by yachtcaptain23** [comment]
TODO: Follow up to make sure the fix on Promo server resolves this

**Comment by yachtcaptain23** [comment]
Just checked, seems fixed on my end. Please re-open if you notice this again. Thanks @jonathansampson!
