### ISSUE TITLE
Instrumentation to monitor sidekiq queue size

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#1969]
TODO: Develop a spec. I figured we could have a watchdog job, but if Redis is down, the watchdog would also fail. My current hunch is that it might make sense to open an API to report queue size.

**Comment by corymcdonald** [comment]
I looked into this a bit, seems pretty straight forward that we can just add a route here?

https://github.com/mperham/sidekiq/wiki/Monitoring#monitoring-queue-backlog

**Comment by nvonpentz** [comment]
As far as I’m aware this problem has only been cause by payout report generation, so generally we should see these things coming ahead of time without monitoring
