### ISSUE TITLE
RTBF Erasure from sendgrid

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#1985]
During the delete of publisher we remove the publishers email address from our database but we don't remove it from the contacts at Sendgrid. We should do so.

**Comment by yachtcaptain23** [comment]
API: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Delete-Recipient-DELETE

**Comment by yachtcaptain23** [comment]
Merged as part of https://github.com/brave-intl/publishers/pull/2022
