### ISSUE TITLE
Optimize the mobile view: responsive text size and form layout to the viewport

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#199]
All publisher pages are not responsive on mobile.  
1. body copy is too small to read
2. Text fields and button are side-by-side
3. Some headings are too big

Example screenshot: (scale down to show a realistic reading view)
![screen shot 2017-10-20 at 11 45 01 am](https://user-images.githubusercontent.com/4369856/31837039-281da576-b58c-11e7-9216-c94e4639776a.png)

1: Need to fix the meta tag for the viewport, scale currently set at 0.6: change to 1
2: Stack text fields and button: i.e. one element per row -- for the most cases (99%), do not try to keep a text field and a button on the same row even if that is the layout for the desktop.
3: proportionally scale down headings in the media query per break points

**Comment by ayumi** [comment]
#308 enhanced the landing page, however there's still room for further improvement. We need a responsive layout because while the first page is great on mobile, subsequent pages look less good.

Also another landing page thought:
> we spend ~200 pixels on the initial brave lion header logo ending up on a big empty space; 50–100px probably would suffice and save precious space for information

**Comment by jenn-rhim** [comment]
lion logo taking up space is a great feedback, worth tweaking to reduce the empty space for. it just needs to happen only on mobile as desktop would need this as is.   before making that change, i want to see where we are with the **page length** after fixing all the text size issue- making them legible.
