### ISSUE TITLE
2FA removal failing for all publishers

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2008]
In `app/services/channels/contest_channel.rb` we update a channel when it's being contested. If a user is trying to transfer their channel while they're trying to remove 2FA this results in a index errors when we try to remove a publishers channels

https://sentry.io/organizations/brave-software/issues/1080816217/?project=225116&query=is%3Aunresolved+TwoFactorAuthenticationRemovalJob&statsPeriod=14d

When addressing this issue I think we should do the following

1. Reduce the 2FA Removal time to 2 days 
   - already cleared with security, 
   - we remove their channels and lock their account anyway so they can't get paid in 30 days
   - if a user simply transfers their channel and waits 10 days then they'll be able to paid, so really all we're doing is punishing those users who want to keep email addresses 
2. Prevent users from transferring their channels while they're under going 2FA
3. Add rescue logic in `app/jobs/two_factor_authentication_removal_job.rb`

**Comment by dlipeles** [comment]
I do not believe this is affecting all publishers as this issue would suggest, in a random sampling of locked accounts all of them had their 2fa's removed successfully.

**Comment by corymcdonald** [comment]
You're right - It's affecting the users who have an id greater than the one that is currently violating the db constraints

**Comment by yachtcaptain23** [comment]
Just spoke with @corymcdonald. His suggested changes sound good.

**Comment by yachtcaptain23** [comment]
Closing this as it seems https://github.com/brave-intl/publishers/pull/2034/files might be the solution. Please re-open if this appears again.
