### ISSUE TITLE
Hard to login with small screens

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2009]
![image](https://user-images.githubusercontent.com/5459225/60351437-6b3a5680-998b-11e9-8b85-81f34a51a25d.png)

Hopefully should be fairly straight forward to fix. User was reporting that the sign in button moves on mobile

**Comment by corymcdonald** [comment]
@rossmoody Let me know if you have capacity for this, if not - no worries, just might be a little bit before anyone on Publishers can tackle it

**Comment by yachtcaptain23** [comment]
@corymcdonald Which phone are you using? I'm using an iPhone 7+ and the screen looks fine.

**Comment by corymcdonald** [comment]
@yachtcaptain23 This isn't my phone, just some random android phone 😄 Can you test on Android?

**Comment by alexwykoff** [comment]
Reproduce on Samsung S7 Edge. 

Did not reproduce on iOS or MacOS with constrained window.
