### ISSUE TITLE
HTTPS issue with sankakucomplex.com (NSFW - fair warning)

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#204]
After an initial investigation with @mrose17 it was shown that this domain is properly responding via HTTPS however the publishers site is showing an error.

**Comment by mrose17** [comment]
it would be nice to have something in the logs when we decide https is not in use...

**Comment by alexwykoff** [comment]
This publisher has been hanging out for almost two weeks waiting for a fix.
We're starting to get more reports of HTTPS validation failures : 
https://community.brave.com/t/cant-get-my-website-verified/10072/3

It would seem appropriate to bump the priority on this to 'right below YouTube' hotfix.

**Comment by ayumi** [comment]
I found the source of this error. Publishers does an HTTPS precheck, querying `https://#{brave_publisher_id}` e.g. `https://example.com`. Usually certs contain `example.com` and `www.example.com` as valid hostnames. However, for certain websites like `ukcolumn.org` and `sankakucomplex.com` the cert only contains the `www.` version and relies on redirection from apex to `www.` to get to the legit hostname.

I can make a fix to publishers to check also for `https://www.#{brave_publisher_id}`, but this is only the frontend validation. The backend, [eyeshade](https://github.com/brave-intl/bat-ledger) must also check `www.` for HTTPS. @mrose17 is eyeshade able to handle this case?

**Comment by mrose17** [comment]
@ayumi - @kpfefferle is looking at this and came to the same conclusion!

i am going to make a little change to the eyeshade to handle this case as well.
