### ISSUE TITLE
Gemini Uphold Work

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2048]
References:
https://github.com/brave-intl/bat-ledger/blob/master/bat-utils/lib/runtime-wallet.js#L305
https://github.com/brave-intl/bat-ledger/blob/master/bat-utils/lib/runtime-wallet.js#L460

**Comment by evq** [comment]
Is there a separate tracking issue for per-channel cards from #2061?

**Comment by corymcdonald** [comment]
@evq Just created one 😄  https://github.com/brave-intl/publishers/issues/2065
