### ISSUE TITLE
Update wordpress flow to remind publishers to disable the plugin when it is no longer needed

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#210]
cf., https://github.com/brave/wordpress/well-known/issues/2

**Comment by mrose17** [comment]
@nvonpentz - is this still an issue or can we close it?

**Comment by yachtcaptain23** [comment]
Re-opening later when do work on this.

Possibly a dupe of https://github.com/brave-intl/publishers/issues/1581
