### ISSUE TITLE
Changing "X" to "!" on error when attempting to download transactions

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#2114]
Just a suggestion, but probably a good idea to change the `X` into a `!` or a similar symbol. Some users might think it's dismissible. We also have a similar issue filed for desktop via https://github.com/brave/brave-browser/issues/5501. Example:

<img width="929" alt="Screen Shot 2019-08-07 at 5 14 09 PM" src="https://user-images.githubusercontent.com/2602313/62660200-704fd580-b93b-11e9-9cd2-e6fc8ad3dc4c.png">

**Comment by kjozwiak** [comment]
Please add required/appropriate labels as I don't have access 👍

**Comment by tsmartt** [comment]
Closing as stale.
