### ISSUE TITLE
not displaying "Download" if there's no transactions

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#2115]
Just a suggestion, but maybe we can improve the `Download Statements` page. It seems like we're showing the `Download` button even if there's no transactions. When a user clicks on `Download`, they'll receive the following:

<img width="929" alt="Screen Shot 2019-08-07 at 5 14 09 PM" src="https://user-images.githubusercontent.com/2602313/62660200-704fd580-b93b-11e9-9cd2-e6fc8ad3dc4c.png">

This might confuse users who think they have transactions and attempt to download a report. Maybe we can remove the button and add something similar to `No transactions this month`.

Either way, just a suggestion/observation 👍

**Comment by kjozwiak** [comment]
Please add required/appropriate labels as I don't have access 👍

**Comment by tsmartt** [comment]
Closing as stale.
