### ISSUE TITLE
Clarify adding a new site channel for DNS records for Cloudflare customers

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2131]
I spoke with Anthony who reported this, and the instructions should be more clear for Cloudflare users. 
<img width="1029" alt="Screen Shot 2019-08-08 at 1 58 52 PM" src="https://user-images.githubusercontent.com/8647607/62737963-f32d6a80-b9e5-11e9-8a71-a40117cc2f30.png">

**Comment by tsmartt** [comment]
Closing as stale.
