### ISSUE TITLE
Migrate OAuth-based details over to a single table

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2139]
In the current implementation of the table we use a polymorphic association for all the varies different channels that we support. This requires quite a bit of upkeep because it creates separate tables per channel. However, most of these connections could be unified into a single table.

I think we should keep the polymorphic association for the current details, due to the potential to add websites, torrents, other custom connections. However we should unify the existing OAuth implementations into a single table, this way it's much simple to add a new type of connection. 

Here's the work that might be required to do this 

`OauthChannelDetails`
```ruby
t.uuid :id
t.string "channel_id"
t.string "auth_provider"
t.string "name"
t.string "channel_url"
t.string "nickname"
t.string "thumbnail_url"
t.jsonb "stats"
```

Of course, since each channel was implemented at different times some of them will need a little more hand holding

**Twitter 🐦**
Rename screen_name -> nickname
Remove auth_email field

**Twitch 👾**
So currently there is a field name `nickname` and also `name`. However the OAuth connection puts the name as the nickname and display_name as the name. 

So these fields need to be reversed to align with the others.

remove auth_user_id, this is a duplicate of the twitch_channel_id

**Youtube 📺**
remove auth_email
remove auth_name
remove auth_user_id
remove subscriber_count (this is already tracked via stats)

**Comment by corymcdonald** [comment]
Here's an article which might be of some assistance when we tackle this - https://coderwall.com/p/grsooq/polymorphic-associations-and-single-table-inheritance

**Comment by tsmartt** [comment]
Closing as won't fix.
