### ISSUE TITLE
Create a v3 publishers channels API

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2142]
We should introduce a property that defines whether or not a publisher is KYC'd, verified or unverified

```
["yachtcaptain23.github.io",true,false,"7d9c7b8a-12fd-4235-9238-f14f8ef5f5de",{}]
```
```
["yachtcaptain23.github.io","verified",false,"7d9c7b8a-12fd-4235-9238-f14f8ef5f5de",{}]
```

**Comment by corymcdonald** [comment]
“” - not verified
“connected” - verified without KYC
“verified” - verified with KYC

**Comment by BrendanEich** [comment]
Important to be robust in face of missed client boolean-sense JS tests. In that light, "" which is falsy for unverified, anything nonempty string for truthy verified and verified+KYCed, is great. Thanks!
