### ISSUE TITLE
Spec for V4 channels API

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2211]
Goals: Minimize data storage and payload size for channels API

Action Items:
- [ ] Create a spec

**Comment by corymcdonald** [comment]
* (removing empty banner entries) we saved 40MB on db size
* if amount is default 1,5,10 it shouldn't be included in the list

**Comment by NejcZdovc** [comment]
@corymcdonald note that this is not v4, but should be done on v3

**Comment by yachtcaptain23** [comment]
Moving discussion to https://github.com/brave-intl/publishers/issues/2364
