### ISSUE TITLE
2 Scenarios where a session expire message is shown but has different behaviour

### ISSUE THREAD

**Issue by srirambv** [brave-intl/publishers#2228]
2 Scenarios where a session expire message is shown but has different behaviour 

Scenario 1 :
1. Login to publishers.basicattentiontoken.org
2. Wait for a few mins and then click the login email
3. Page shows session expired but logs in
4. Reload the page, logs out correctly

Scenario 2: 
1. Login to publishers.basicattentiontoken.org
2. Wait for a few mins and then click the login email
3. Page shows session expired but logs in
4. Reload the page, retains your session and removes the message 

![image](https://user-images.githubusercontent.com/17010094/64989183-f9432080-d89a-11e9-94c0-9e208fbf03fb.png)

cc: @yachtcaptain23

**Comment by yachtcaptain23** [comment]
I remember this being fixed. Closing. Please re-open if this appears again.
