### ISSUE TITLE
change all instances of "sign in" to "log in"

### ISSUE THREAD

**Issue by bradleyrichter** [brave-intl/publishers#2271]
Currently we are mixing verbs within our login screen content. All instance of "sign in" should be changed to "log in".

current:

![image](https://user-images.githubusercontent.com/13509546/65980745-9cb03b80-e42c-11e9-9dcb-c63e290ff4f8.png)

new:

![image](https://user-images.githubusercontent.com/13509546/65980688-7ee2d680-e42c-11e9-91e7-a9a986b5cb2e.png)

**Comment by bradleyrichter** [comment]
@corymcdonald Can you sneak this one in soon?

**Comment by corymcdonald** [comment]
@bradleyrichter 👍 Can do
