### ISSUE TITLE
Add a contention flow for users who try to claim an already owned channel

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#228]
Users need a way to be warned if someone else has claimed their channel

**Comment by lgebhardt** [comment]
#251 made some changes to this behavior. Users are now taken back to the previous page and given a message that the channel has been taken.

**Comment by mixonic** [comment]
Can this be closed? If not, what remains to be completed?

**Comment by alexwykoff** [comment]
Is there a clear method for a user to contend for ownership of a channel?

In particular I am thinking of the case where a channel may have multiple managers and the one who registered the channel with us has left the company and didn't use the contact info update flow to hand off ownership.  Other cases may exist as well.

**Comment by mixonic** [comment]
Ah, that doesn't seem to be implemented 👍 I was foiled by the description here (only described the warning). I've tweaked it to include your comments about contesting a claim.

**Comment by jenn-rhim** [comment]
This case will be relatively rare - the case that someone manages monetization accounts leaves the group without proper handoff. 

We could, however, offer the ownership change request at the bottom of channel claimed notice screen, which allows the requester to create the account with the channel in a pending state. We will send the email notification to the previous owner with a grace period to switch the channel ownership in case she or he doesn’t respond.

**Comment by nvonpentz** [comment]
This is described in more detail in #377
