### ISSUE TITLE
Rate Card UI Changes

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2288]
Action Items on Referral Server:
- [ ] (Referral server): API Changes to support the panel
- [ ] (Referral server): API Changes to support the graph

Action Items on Publishers
- [ ] New UI changes (Cosmetic request down in the comments)
![Screen Shot 2019-10-03 at 5 01 06 PM](https://user-images.githubusercontent.com/8647607/66337355-d339fa80-e8f3-11e9-9eb1-ccb70b059994.png)

- [ ] Support the chart

**Comment by alexwykoff** [comment]
Related Spec : https://docs.google.com/document/d/1kYo3r_C_L_d-OspsV_XkZK-p-M1FFfd_qwGH4chvmaA/edit#

**Comment by yachtcaptain23** [comment]
Amount should say ($7.50 USD with a link to https://support.brave.com/hc/en-us/articles/360025284131-What-do-the-referral-metrics-on-my-dashboard-mean- )

**Comment by corymcdonald** [comment]
Work

- [x] More panels around and move Contact information into settings
- [x] Auto show the referrals table
- [x] Pull group information from Eyeshade
- [ ] Get the confirmed group numbers from Eyeshade
- [ ] Filter the referral list for time period
- [ ] Update onboarding experience with rate card information
