### ISSUE TITLE
Acquisition Flow Update : publishers landing page needs better enticements for various platforms

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#230]
step 1 : make clearer the value proposition for channel owners

**Comment by mrose17** [comment]
i know this is important, but it is unclear to me whether it is actually urgent... particularly given the complete lack of any requests of development...

**Comment by jenn-rhim** [comment]
Not urgent.  We can wait until we start directing various entry points to this page. Currently the actual landing page that is funneling all external traffic is Publishers page on Brave.com with the CTA ‘Get Verified’, which makes our landing a redundant twin for most users who already decided to proceed. 

This landscape does need to change soon.

**Comment by yachtcaptain23** [comment]
Not enough details for action items.
