### ISSUE TITLE
Improve robustness of Payout Tracker

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2300]
This payout cycle in October we introduced a payout tracker, with that came some issues 

- When the payout report was still generating balances were shown as 0
- Nil error https://sentry.io/organizations/brave-software/issues/1250264937/?project=221970&query=is%3Aunresolved

**Comment by yachtcaptain23** [comment]
Closed by https://github.com/brave-intl/publishers/pulls?q=is%3Apr+is%3Aclosed
