### ISSUE TITLE
Update creators landing page with new Rewards channels and stats

### ISSUE THREAD

**Issue by karenkliu** [brave-intl/publishers#2321]
## Description
Currently creators.brave.com doesn't show up to date information. Update the intro section with all the channels that support tipping and new creator stats at the bottom of the page.

## Designs
Intro section with more channels:

![updated logos](https://user-images.githubusercontent.com/2388823/66875757-3cf57c80-ef64-11e9-9543-ce4b9d2289db.jpg)

Update "28,000" number to "280,000"
![bottom stat](https://user-images.githubusercontent.com/2388823/66875824-7d54fa80-ef64-11e9-89c4-4fdd7023df9e.jpg)

## Assets
[assets.zip](https://github.com/brave-intl/publishers/files/3731753/assets.zip)

**Comment by karenkliu** [comment]
@yachtcaptain23 Update - the correct creator number is 290,000 now.

**Comment by corymcdonald** [comment]
We updated the number to be 280,000 in production, but having a "live" update of the number via https://github.com/brave-intl/publishers/issues/2238 would make the most sense. 

Right now it seems somewhat straight-forward to do - making a call to http://publishers.basicattentiontoken.org/api/v3/public/channels/totals and then sum up all the totals.

**Comment by karenkliu** [comment]
@corymcdonald Yes we should do that!

**Comment by tsmartt** [comment]
Closing as dup https://github.com/brave-intl/publishers/issues/3151
