### ISSUE TITLE
Channels list V4 API

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2364]
Will update performance info with benchmarks, but slimming down the channels list as much as possible is ideal.

Benchmarks (Newer iPhones on 130 mbps download):
~ 5s download, 30s - 40s database insert

**Comment by yachtcaptain23** [comment]
Proposed solution 1:
Create the following endpoints:
`api/v4/public/channels/youtube`
`api/v4/public/channels/sites`
`api/v4/public/channels/excluded_sites`
`api/v4/public/channels/vimeo`
...

```
# V4 Version of Channels list
#
# Each channel is an array:
# [
#   channel_id (string),
#   connected state (enum where 0 is PUBLISHER_NOT_VERIFIED, 1 is CONNECTED, 2 is VERIFIED)
#   excluded (numerator where 0 is false, 1 is true),
#   wallet address (string)
#   site_banner details (hash)
# ]
```

Examples:
For `api/v4/public/channels/youtube`
`["UCr_USjgn4PQhVpqOT6RcAtQ",1,0,"6131cad3-fe35-4c75-b5a0-bd1febe74b35",{}]`

**Comment by NejcZdovc** [comment]
I think that we shouldn't try to improve current list approach, but go with api approach. We could mimic cache on client like we do on desktop, so to only hit api after 24h when publisher cache on client expires and user visits the site again. We would have same mechanism that we have now to force fetch publisher via the panel

**Comment by NejcZdovc** [comment]
Also based on what I just read from second comment this is a huge change on the client side

**Comment by corymcdonald** [comment]
I'm wondering what the privacy implications of having an API for this. Based on this paper it looks like SafeBrowsing can track users websites, Yandex being the worse offender of this. https://hal.inria.fr/hal-01120186/file/RR8686.pdf

However, if we proxy through Fastly, similar to the way we currently are doing, then we wouldn't be tracking users.

**Comment by NejcZdovc** [comment]
@corymcdonald @evq has a proposal how to do this with privacy in mind. Why I am pushing for alternative approach (not need to be API, could be x) and not improve list approach is because it would take a lot of time on both sides and it's just a temp solution as list is just not scaling

**Comment by yachtcaptain23** [comment]
@NejcZdovc With regards to the database changes, the proposal found in https://medium.com/@JasonWyatt/squeezing-performance-from-sqlite-insertions-971aff98eef2 suggests a single column solution would allow for maybe sub 1 second inserts on 100,000 rows compared to 50 seconds for a relatively similar multi-column implementation (and we're approaching 300,000 rows). I know it's a big engineering change, but regardless such a change (if it works) would need to happen whether we dynamically call the API for certain values.

**Comment by corymcdonald** [comment]
Discussion of this issue will happen mostly in Slack #publishers-list-perf-discussion until a decision / draft if more final.

**Comment by yachtcaptain23** [comment]
Proposed Solution 2: https://docs.google.com/document/d/1-MJ-wSUoYbJTh5ATjh-ngVLjT21f2G_0tdg3VMWZAqg/edit?usp=sharing

**Comment by yachtcaptain23** [comment]
Merged into production.
