### ISSUE TITLE
Document practices around email campaigns

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2382]
We discussed today in that there was a mistake in templating which is touched on in #2279, but this brings about a bigger discussion.

We should document / develop a guide for the best practices around 

- when to send emails
- what belongs in a marketing email vs transactional email
-  opt-in / opt-out practices 
- providing plain text / HTML unsubscribe links to users
- publishing this guide so users to be transparent and engaged with our users

**Comment by yachtcaptain23** [comment]
Let's make use of the Wiki rather than bloating the README.

**Comment by yachtcaptain23** [comment]
Updating here: https://github.com/brave-intl/publishers/wiki/Emailing-Publishers-Checklist

@corymcdonald let me know if there's anything missing. I'll sync up with @mandar-brave to make the checklist and requirements are accurate

**Comment by yachtcaptain23** [comment]
Email campaigns have moved purely to SendGrid and not sent by Publisher's backend. Closing.
