### ISSUE TITLE
Add email to header

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#239]
For every screen post email verification, we should display the email address in the header.

Flow example:

![screen shot 2017-11-07 at 2 49 30 pm](https://user-images.githubusercontent.com/1434040/32517156-31a78eca-c3cb-11e7-8b86-e387435fbd24.png)

Dashboard example
<img width="665" alt="screen shot 2017-11-07 at 2 55 53 pm" src="https://user-images.githubusercontent.com/1434040/32517355-cdeddfdc-c3cb-11e7-88d7-35a03c351d15.png">

**Comment by jenn-rhim** [comment]
@alexwykoff  we should use git for posting only the finalized screens (at the time), not for discussion.  Posting something that is in discussion or not approved would confuse the implementation team.

**Comment by alexwykoff** [comment]
Interesting. In all other discussions as I have seen, the email in the header was fully approved and in immediate scope.

**Comment by alexwykoff** [comment]
Updated original post with callout screens to differentiate between mock and final spec. 
Engineering can take them as guidance for where the email is expected to exist in header without worrying about body content.

**Comment by jenn-rhim** [comment]
Current model for the Publisher account is domain/channel based, not email based. This change will go in once we change the account model to email based.

**Comment by ayumi** [comment]
closing as superseded by multi-chan e.g. #382
