### ISSUE TITLE
update copy for disconnected wallet

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#240]
In the case where the frontend system for displaying the dashboard cannot connect to the backend system for managing wallets, the user needs to see a reasonable message to alleviate their concerns.

**Comment by jenn-rhim** [comment]
what are the resulting effects we experience from this? currently we handle one case that is to notify the user to reconnect to uphold. are there any other cases we cannot handle with this method?

**Comment by nvonpentz** [comment]
@alexwykoff can we close this?  Users are presented with "Reconnect To Uphold" if the connection has been broken.

**Comment by alexwykoff** [comment]
that happens in the ui but do we send the appropriate email yet?

to the best of my knowledge, if the wallet is disconnected then payments are going out as well.

**Comment by nvonpentz** [comment]
Closing in favor of #479
