### ISSUE TITLE
Handle changes in domain registration

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#249]
If you've registered potato.com and become a Brave publisher; and potato.com expires and Cate Camper registers it right away, contributions to potato.com should no longer flow to you.

eyeshade, as the canonical registration checker, should be the service which checks periodically:
https://github.com/brave-intl/bat-ledger/issues/42

we'll need a way to get that info into publishers and present a flow to the users (probably clear out the `brave_publisher_id` then send a notification).

**Comment by mrose17** [comment]
update: it's _eyeshade_ not _ledger_ that is the canonical checker for sites...

**Comment by ayumi** [comment]
closing as dupe
