### ISSUE TITLE
Catalog HTTPS configuration errors, generate appropriate guidance for users in trusted file flow.

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#253]
There are a reasonable number of HTTPS configuration errors which impeded trusted file flows.

We need a catalog of common errors and then guidance copy created to help users overcome their configuration issue.

Edit (Albert Wang): Examples are found on https://badssl.com/dashboard/

**Comment by kpfefferle** [comment]
Here's the error we were seeing when trying to verify ukcolumn.org:
```
hostname "ukcolumn.org" does not match the server certificate
```

**Comment by kpfefferle** [comment]
As of PR https://github.com/brave-intl/publishers/pull/259, domain verification errors will appear in the logs as `PublisherHostInspector #inspect_uri error: [ERROR_MESSAGE]`, so it will soon be possible to search the logs for errors that we encounter when inspecting host names.

**Comment by kpfefferle** [comment]
On reflection re: user-impacting errors, I've added a second logging statement:
```
PublisherHostInspector #perform failure: [ERROR_MESSAGE]
```
While each of these would also log the above `#inspect_uri` error message as well, this should allow for filtering of only those failures that might result in a user-impacting response.

**Comment by ayumi** [comment]
i think the common case will be covered with #259.

the other case will be expired certs, and it will be nice to say "Your SSL cert is expired, please fix it. you can get a new one from letsencrypt for free."

**Comment by nvonpentz** [comment]
Related to #408

**Comment by yachtcaptain23** [comment]
Larry will be following up with the logs to see if there's anything actionable.
