### ISSUE TITLE
Fix the balance view for the user funded vs Brave settled BAT

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#2533]
Issue: As we have moved to user funds and tips from user funds go directly to the creator wallet, we don't reflect what is Brave settled vs. user funded settlement to the creator
This was noted by Wikipedia who was able to see direct deposits in their account not via Brave and caused confusion

See image -- 
![image](https://user-images.githubusercontent.com/35932307/73862176-02ee0600-47f3-11ea-97e2-20a015bdab6c.png)

In this image, the total number is fine as we pull all user funded tips from Uphold so the creator sees the right total; however the split between what was settled via settlement and what was received via user tips (aka settled directly) is not split.

We need to be able to split this to show what is Brave settled vs. already deposited with a note that there is a 5% platform fee on both.

cc @jenn-rhim @corymcdonald 

Assigning to @jenn-rhim for design suggestions. @jenn-rhim please assign back to me when ready.

**Comment by jenn-rhim** [comment]
@corymcdonald 

Here is how we'd indicate the breakdown to eliminate the confusion about the total deposited.
A. Statement: 
1. Add line items in the overview at the top of the statement as shown in the following mockup. 
2. Summary table below: merge the contribution table and fees table as they are related

B. Dashboard UI:
Similarly, display the break-down next to the total pending balance. 

![statement](https://user-images.githubusercontent.com/4369856/75913480-dfc17100-5e07-11ea-90c1-d0003de7fd65.png)


![dashboard-topbox](https://user-images.githubusercontent.com/4369856/75913427-c91b1a00-5e07-11ea-8376-7e15958277f9.png)
