### ISSUE TITLE
Support Custom home page

### ISSUE THREAD

**Issue by mandar-brave** [brave-intl/publishers#2547]
We have a need to support Super Referrer pages in certain regions and that needs to allow super referral clients to;

a) Sign up
b) However, no channel is required to register

We need a feature that supports customization of one image that allows the super referrer to own the user experience on New Tab Page. This image should match the NTP SI image specifications and will be cross platform - aka one single high resolution image and logo (one logo and one image only).

This feature should be supported on a per region basis - as in the super referrer can have an image and a logo per Brave supported region. 

The creator can update the per region image and logo as/when required and those will be expected to refresh on the client.

@jsecretan we need specs for NTP SI for both;
a) image
b) logo

cc @yachtcaptain23 
@jenn-rhim we need help with the UI/UX here

cc @mattmcalister - please update Anthony

**Comment by mandar-brave** [comment]
Closing issue for the moment.

cc @jsecretan @yachtcaptain23

**Comment by anthonypkeane** [comment]
> @jsecretan we need specs for NTP SI for both;
> a) image
> b) logo

Specs are as per NTP SI. Please read the custom homepage spec for info as it is detailed there
