### ISSUE TITLE
Proper branded email template for all notifications in Publishers Brave Payments 

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#255]
@alexwykoff please add the list of cases with the content :)

![email-template-pub](https://user-images.githubusercontent.com/4369856/32673032-40f3e07a-c602-11e7-913e-88079bd77c2b.png)

**Comment by jenn-rhim** [comment]
@lgebhardt @dgeb

**Comment by dgeb** [comment]
What are the official links for Brave in Medium, Reddit, and Rocketchat?

**Comment by alexwykoff** [comment]
https://basicattentiontoken.org/ the links are all in the footer 

https://medium.com/@attentiontoken 
https://www.reddit.com/r/BATProject/
https://twitter.com/@attentiontoken
https://basicattentiontoken.rocket.chat/

**Comment by dgeb** [comment]
@alexwykoff thanks!

**Comment by ayumi** [comment]
I believe this is resolved as of #261 – if we require content revisions let's create new issues for those.
