### ISSUE TITLE
Add unsubscribe/account management links to outgoing Sendgrid publisher emails

### ISSUE THREAD

**Issue by atsyed87** [brave-intl/publishers#2551]
We need a link to the account management FAQ in the footer section of outgoing publisher emails (i.e, updates on payout, reminders to sign up and grab unclaimed BAT, etc.) 

Let's just add a footer link that says `Manage my Account/Email Preferences` - this should link to the [Managing your Creators Account](https://support.brave.com/hc/en-us/articles/360039211232-Managing-your-Creators-Account) FAQ on the Brave Help Center. This article also includes direct links to the Account Settings page in the publishers system. 

cc. @mandar-brave @yachtcaptain23

**Comment by mandar-brave** [comment]
@yachtcaptain23 would be good to make change ahead of next payout.
Thanks.

**Comment by yachtcaptain23** [comment]
Let's add https://support.brave.com/hc/en-us/articles/360039211232-Managing-your-Creators-Account to the footer
