### ISSUE TITLE
Merchant Feature

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2557]
With the upcoming SKU work, we should be able to turn on and off certain features of the Publisher's dashboard based on if they are a merchant or not.

Blocked on https://github.com/brave-intl/publishers/pull/2559
Blocked on https://github.com/brave-intl/bat-go/issues/259

MVP Priority:
* Merchants should be able to verify channels (0 points)
* Merchants should be able to connect to payment providers e.g. Stripe. (5 points)
* Merchants should be able to view their current balances through the dashboard. (New row on the dashboard) (3 points)
* Make call to payment server to generate keys and secrets. https://github.com/brave-intl/bat-go/issues/259 (3 points) 

Later Priority:
* Invoices will be generated from the payment processing providers. `/invoices` should contain messaging to reflect that

Later+1 Version features:
* GUI for SKU management

Later+2 Version features:
* API endpoint for SKU
* API documentation?

**Comment by yachtcaptain23** [comment]
Later Version features:
1. GUI for SKU management

Later Version + 1 features:
1. API endpoint for SKU
2. API documentation?

**Comment by tsmartt** [comment]
Talk with pj about this.
