### ISSUE TITLE
Expose publishers admin website as API

### ISSUE THREAD

**Issue by dahacouk** [brave-intl/publishers#2563]
Expose [publishers admin website](https://creators.brave.com) as API. Having multiple properties requires a publisher admin to log in and out multiple times to administer their properties. This could be made much easier if all this functionality was exposed via an API so that third-party dashboards could interact with the publishers admin website.

**Comment by jonathansampson** [comment]
@dahacouk Can you elaborate on the use case? Multiple properties are supported today; did you encounter an issue or limitation with the multi-property support?

**Comment by dahacouk** [comment]
@jonathansampson Sure... When I say multiple properties I meant multiple accounts... I have various companies, organisations, personas that I keep separate for accounting reasons. I also keep them separate so that I can have different teams working on each organisation and hand out different permissions to each team member. The [publishers admin website](https://creators.brave.com) doesn't enable me to manage teams in this way so I have to set up a different account for each organisation and then give that email out to each team member. This is all very time consuming and insecure. If this interface was exposed as an API then I could create all this functionality at my end and you wouldn't have to implement the team function at all. It would allow me to "flip" between my accounts really quickly because my "dashboard app" would manage the API connections to multiple accounts simultaneously. I hope that makes sense. Cheers!

**Comment by tsmartt** [comment]
Going to close for now due to lack of activity. We're happy to reopen and discuss if you'd like to submit a PR for this.
