### ISSUE TITLE
Channel already registered

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#264]
Alert user when the channel has been already claimed by another owner/manager.

**Comment by ayumi** [comment]
Here's the styles from #267 for convenience:

From a slack conversation with @jenn-rhim:

jenn [11:08 PM] 
this is how i’d like to treat the case where the channel has been already claimed.  it’s level 1 warning as opposed to level 2 warning (alert bar).


jenn [11:08 PM] 
uploaded this image: 
![channel taken warning](https://user-images.githubusercontent.com/29154/32780747-650a078a-c910-11e7-857a-bb52edc90277.png)


jenn [11:09 PM] 
if this is not quick, we can make do with the current scheme until we can fix it, but i’d still use a little more catchy alert bar style, which we will use for other cases as well. here


jenn [11:09 PM] 
uploaded this image: 

![channel taken warning-alt](https://user-images.githubusercontent.com/29154/32780780-762092be-c910-11e7-9aa6-2dfd19345d79.png)

**Comment by ayumi** [comment]
I'm in favor of the simple blue warning bar, because it's simple.
