### ISSUE TITLE
Statement UI Fix

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#265]
The following UI for the statement, enumerating all generated statement history is unscalable, and probably doesn't make sense for the users. 
https://github.com/brave-intl/publishers/pull/218

This issue is attempting to fix that.

**Comment by mrose17** [comment]
@jenn-rhim - we need a description... thanks!

**Comment by TheLucasMoore** [comment]
Hey Jenn is this addressed by https://github.com/brave-intl/publishers/pull/347?

**Comment by jenn-rhim** [comment]
Yes, #347 serves as an interim solution. A preferred UX will be speced here.

**Comment by nvonpentz** [comment]
Duplicate of #542
