### ISSUE TITLE
Fix "5 BAT minimum" messaging (e.g., next to each individual channel instead of only next to the total sum / pending amount)

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#2706]
Currently, the 5 BAT minimum notice is written below the total pending sum in the top left corner. However, the 5 BAT minimum applies to _each channel individually_, meaning that a user can have (example case):

- Channel A: 3.25 BAT
- Channel B: 4.00 BAT
- Channel C: 4.75 BAT

The sum of channels A + B + C = 12 BAT, which is what is displayed in the top left corner. 12 BAT is > 5 BAT, so creators are led to believe they have passed the threshold for a payout.

However, the creator will **not** receive their payout for that month, given no individual channel is above 5 BAT. 

Perhaps we can introduce some more precise messaging to reflect the above payout logic.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/hq356d/brave_creator_payouts_pending_for_over_2_months/

**Comment by zcraber** [comment]
+1

**Comment by tsmartt** [comment]
Related to #2499

**Comment by Miyayes** [comment]
## Update

If it's for a custodian that does _not_ enforce a 5 BAT minimum, we should remove such language.
