### ISSUE TITLE
Allow a single Owner to manage many Properties

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#273]
Currently "publishers" (people who publish) and the "published property" (a web site, a video channel, etc.) are combined in one table in the database. This creates usability and management  issues for publishers that publish multiple properties. For example statements can not be aggregated between properties, Uphold wallets must be linked to each property, management tasks such as changing the owner's name or email must be performed for each property.

To mitigate these issues the goal is to separate the publishers from their properties in the database and UI of the site. Functionally we will have a model where one Owner owns many properties (sites, video channels, etc).

To accomplish this will be relying on the fact that all verified entries in the Publishers table have a verified email address.  A unique Owner will be created for each unique email address in the table. We can expect there will be differences in the name and phone number of these owner accounts. Flattening this data is still TBD. Simplest case is we take the first entry's values and discard the rest.

The existing Publishers table entries will then be associated with the new owner records. At this point the Publisher's table will represent Properties. Further refinement could be done to normalize different property types. This is not being proposed in this issue.

The login process after this step will involve entering an email or domain, receiving an email containing a login link and using that link to authenticate. A second phase will include the addition of OAuth to allow authentication against google (and potentially other OAuth providers). See #274.

Once owners are associated with multiple properties they will need a way to manage them. #229 address adding and removing properties. @mrose17 noted that some Owners will have 100s of Properties.

@mrose17 indicated that we will start with one wallet per owner. If a need to associate different wallets with different Properties is need we will address in a follow-on release.

Statements on the dashboard will support both per Owner and per Property statements.

**Comment by mrose17** [comment]
@lgebhardt - if you take a look at https://github.com/brave-intl/bat-ledger/blob/master/eyeshade/controllers/owners.js#L393 you'll see how the eyeshade server "taxonimizes" an owner. publishers have an owner field, that if present, refesr to the associated owner. you may not need all the fields (e.g., `provider*` is used to hold the components of the owner-identity.  publishers also have a field to allow them to have uphold information distinct from their owner. for the publishre site, we can consider that a future.

**Comment by ayumi** [comment]
This has essentially been implemented (in `staging2`) by #452 -- lets track blockers for deployment in separate issues.
