### ISSUE TITLE
Add more timescales to referral chart / graph

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#2748]
## Description

Currently, the referral chart displays lifetime activity. However, when lifetime activity is long, the graph becomes difficult to interpret (due to scaling).

![image](https://user-images.githubusercontent.com/11497541/84348615-60b8a300-ab83-11ea-8ee6-c8800b8cbb6a.png)

## Solution

Add smaller timescales and time windows to the referral graph. 

## Source

Initial request from user: https://www.reddit.com/r/BATProject/comments/h0gfzc/its_getting_tooo_thin_make_a_shortened_period_of/ cc: @corymcdonald

**Comment by tsmartt** [comment]
Closing as stale.
