### ISSUE TITLE
Offer discrete data visualization mode for referral graph

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#2749]
## Description

Currently, the referral graph is continuous. This can be useful to see flowing trends, but can be confusing at certain values and at certain scales. 

Given referral data is inherently discrete (i.e., one only has integer values of _downloads_, _installations_ and _confirmations_, while all other values are ill-defined), an option to view the data in a discrete manner should be offered. 

## Solution

Possible example:

x-axis = date
y-axis = # of referrals (e.g., # of downloads, # of installs, # of confirmations)

![image](https://user-images.githubusercontent.com/11497541/84349615-ab3b1f00-ab85-11ea-8f47-94fbdf0d6d02.png)

**Comment by tsmartt** [comment]
Closing as stale.
