### ISSUE TITLE
CSRF token mismatch when adding Twitch channel

### ISSUE THREAD

**Issue by evq** [brave-intl/publishers#2753]
User encounters CSRF error when trying to verify Twitch channel.
```
{"status":401,"message":"invalid csrf token"}
```

**Comment by Dragendave** [comment]
It did work in the end using FireFox.

But on any site when trying to link to Twitch using Brave, I get this error. Not only the Creators Page from Brave.

**Comment by yachtcaptain23** [comment]
Metrics says we're still getting fairly healthy signups on Twitch. Closing.
