### ISSUE TITLE
Re-activate existing referral codes when user verifies their identity. 

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2768]
Users should be able to reactivate their existing promo codes.
When a user verifies their identity we kick off a job to reactivate their existing codes

The job 
* Checks the user's country to ensure they aren't in one of the restricted geos
* calls `Promo::UpdateStatus` to update the status of the Publisher to 'Active' 
* Deletes the promo expiration time feature_flag

**Comment by evq** [comment]
Resolved in https://github.com/brave-intl/publishers/pull/2780
