### ISSUE TITLE
Create script to move expired promo codes to no_ugp automatically

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2769]
If the promo expiration time is up we should have a piece of code (automated job) which automatically enqueues the referral codes for expiration and move to the `no_ugp` state. 

Additionally we should create a script to handle the case where publishers had a promo_expiration time but then later KYC'd thus removing the need for a promo_expiration_time

**Comment by tsmartt** [comment]
Closing as stale.
