### ISSUE TITLE
do not send `show_verification_status` if the value is not known

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#277]
in the call to `POST /v1/owners` on eyeshade. the value must be either `true` or `false` not `NULL`, etc.

**Comment by lgebhardt** [comment]
Would it make sense to send false in the case where the value is null? That will keep it consistent with the way it was before the change allow nulls in `show_verification_status`.

**Comment by mrose17** [comment]
`false` is fine. that's the default if the value isn't present.
