### ISSUE TITLE
Use paper_trail on additional models to improve audit logs

### ISSUE THREAD

**Issue by dgeb** [brave-intl/publishers#279]
Add `has_paper_trail` on `YouTubeChannel` and perhaps other models.

See https://github.com/brave-intl/publishers/pull/276#discussion_r151018649

**Comment by mrose17** [comment]
perhaps we could also sentry when calls to the eyeshade service fail with a 4xx or a 5xx ?

**Comment by ayumi** [comment]
@mrose17 let's open a new issue for that

we do log to Sentry for most errors in an automatic fashion, so if you found specific endpoints please add them to the new issue
