### ISSUE TITLE
Investigate why users are seeing Forbidden with Fastly change

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2791]
https://community.brave.com/t/unable-to-access-publishers-site-403-forbidden/139072

Some users are reporting they are seeing "Forbidden" since we've introduced a change to have requests route through Fastly and then hit Publishers. 

We should investigate to see what IP addresses they are accessing from and check if they are on Fastly's forbidden range.

**Comment by SaltwaterC** [comment]
OP here. When going through TOR, it's still being routed through Fastly, albeit the exit node is not denied.

![Imgur](https://i.imgur.com/fnWMAYy.png)

DM sent on support site with full address.

Also, checked my address here: https://www.whatismyip.com/blacklist-check/

It only came back listed on dyn.nszones.com and bl.nszones.com. Those are fairly obscure lists as I have never heard about them until today.

**Comment by corymcdonald** [comment]
Found the error, we use a Rack based middleware for filtering out the IP address. Since we're using Fastly the ip address that is being returned is the [Fastly IP range](https://api.fastly.com/public-ip-list). 

The relevant code snippet is located here 
https://github.com/brave-intl/publishers/blob/0a6dd40afc3318a960bb3575d858907293cc36eb/config/initializers/rack-attack.rb#L46-L53

To remediate this we should ensure that the correct IP address is being returned. We might be able to use the ActionDispatch `remote_ip` middleware as it's inserted before this middleware is being called. Otherwise we can replicate some of Rails built-in logic located here https://github.com/rails/rails/pull/38150/files#diff-24e755424fe27338cfcde43be978c2bdR150

**Comment by SaltwaterC** [comment]
Hi @corymcdonald. We are back to square one. The 403 - Forbidden error is back.
