### ISSUE TITLE
Investigate 500 reports from Community 

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2792]
Publishers are seeing errors but upon first glance it's not clear what's happening

https://community.brave.com/t/error-500-internal-server-error-for-my-publishers-account/139470/9

* Gather email addresses for users affected
* Check Sentry, other logs

**Comment by corymcdonald** [comment]
First issue - https://github.com/brave-intl/publishers/issues/2793

**Comment by Brave-Matt** [comment]
Another user seeing this behavior on Community:
https://community.brave.com/t/brave-contributor-internal-error/140849/2

**Comment by Brave-Matt** [comment]
Another user: https://community.brave.com/t/my-publisher-account-is-not-opening/141866

**Comment by Brave-Matt** [comment]
And another! https://community.brave.com/t/i-cant-login-to-my-account/141756/2

**Comment by yachtcaptain23** [comment]
All seem to be fixed. Closing
