### ISSUE TITLE
Check existing `no_ugp` for users who have completed KYC

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2797]
We have logic that checks to see if a user is_member and updates their promo status, so we should double check this is working.

**Comment by corymcdonald** [comment]
We've seen a very small portion of the existing user base affected by this issue. It looks like there are 35 accounts have been affected. 

The uphold status of the various accounts are as follows. 

| status | count |
| ------ | ------ | 
| blocked | 6 |
| ok | 24 | 
| restricted | 5 | 

We have some after_save callbacks in the `UpholdConnection` model. 

https://github.com/brave-intl/publishers/blob/f508593041287d7318b3bee3cd27ebcd6640d82b/app/models/uphold_connection.rb#L51-L54


This after_save callback only gets saved if there was a change made to the `is_member` field (i.e. the field goes from false to true). 

* 3 of the accounts were put into `no_ugp` and haven't been updated in the last year. This was likely caused by the country script run in June 30th

For accounts that were registered afterwards my theory is that once a user disconnect from Uphold we send `no_ugp` to the promo server and then the user reconnected.

I'm going to re-run these through the Promo::UpdateStatus flow again and monitor if there were any changes next week.

**Comment by tsmartt** [comment]
Closing as stale.
