### ISSUE TITLE
Don't include deleted publishers channels in Channels list

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2837]
If a publisher has deleted their account we should not show their channel information as verified

**Comment by tsmartt** [comment]
Related to #3114

**Comment by yachtcaptain23** [comment]
This is already implemented, as the dependent destroy on the channel will destroy the channel
https://github.com/brave-intl/publishers/blob/85658e1502c11e2ddda7f85ff115d44de27bd33c/app/models/channel.rb#L34

The channels list will get synced after the site banner gets deleted too: https://github.com/brave-intl/publishers/commit/85658e1502c11e2ddda7f85ff115d44de27bd33c#diff-12fe79ce6fc1e844acaae268ef8fd1b1dacfc7d92ac585d50ef901374225678bR15
