### ISSUE TITLE
Gmail is eating images embedded in styles

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#286]
When a message is displayed in gmail the images are being stripped.

![screen shot 2017-11-15 at 10 54 19 am](https://user-images.githubusercontent.com/29154/32870991-7c776088-ca4c-11e7-89cd-36d52844be8c.png)

**Comment by ayumi** [comment]
Partially fixed by https://github.com/brave-intl/publishers/pull/287
