### ISSUE TITLE
Improve checks for Wordpress

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2872]
On Pete Snyder's website https://www.peteresnyder.com/ there is a link to a wordpress site.

In the following code we misidentified this Github site as a wordpress site because the response body contains `wp-content`

https://github.com/brave-intl/publishers/blob/5c59c54505133b957717f5038899d978c455592a/app/services/site_channel_host_inspector.rb#L102-L108

We should instead try to query a `wp-content` directory to ensure there are no false positives. Alternatively we can expand the github check to determine if this is a github site or not.

**Comment by pes10k** [comment]
Just as suggestions:

To detect github pages, you might look for a `Server: GitHub.org` response header
For wordpress sites, you could look for a  `<link rel="https://api.w.org/" href="…">` tag in `<head>`

**Comment by tsmartt** [comment]
We should just use pek10k' suggestion and check the response header.

**Comment by tsmartt** [comment]
@OAuthBringer removed WP, so no longer relevant.
