### ISSUE TITLE
Oauth is not working for desktop Safari (perhaps CSRF issue)

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#288]
When trying to verify a YouTube channel via Oauth, the user is presented with a blank screen.  After walking backwards in history, an error message is displayed:

<img width="1719" alt="screen shot 2017-11-15 at 9 18 21 pm" src="https://user-images.githubusercontent.com/1434040/32873583-6ee01090-ca52-11e7-8e52-01321f8f8aa3.png">

The test machine used Safari 11, macOS High Sierra.

**Comment by ayumi** [comment]
this worked for me, safari 11.0 (11604.1.38.1.7) on macOS El Cap 10.11.6

**Comment by nvonpentz** [comment]
This worked for me, safari 11.0.1 (12604.3.5.1.1) on macOS Sierra 10.12.6
@alexwykoff can you still reproduce this?

**Comment by nvonpentz** [comment]
Closing because it is not reproducible
