### ISSUE TITLE
Setup asset_host

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2889]
Guide is here: https://edgeguides.rubyonrails.org/asset_pipeline.html#cdns and particular 4.4.1 stands out

Basically it seems only `config.action_controller.asset_host = 'mycdnsubdomain.fictional-cdn.com'` needs to be setup for things to automagically work.

**Comment by tsmartt** [comment]
It seems we are not configured to use our CDN properly in prod, this should fix that.
