### ISSUE TITLE
Stripe Metadata in V4 Channels List

### ISSUE THREAD

**Issue by corymcdonald** [brave-intl/publishers#2902]
## Stripe Metadata in V4 Channels List

The `stripe_connections` table stores relevant information related to a user's connected Stripe account.

For the client to send a tip to a particular user we will need to store the `stripe_user_id` in the channel's response object located here - https://github.com/brave-intl/publishers/blob/staging/protos/channel_responses.rb

For the Client side integration we will need to follow the Stripe guide for accepting a payment and then paying out.  
https://stripe.com/docs/connect/collect-then-transfer-guide#accept-payment

Stripe recommends creating the PaymentIntent on the server side so that prevents malicious customers from setting their own prices. 

But because these are tips I think we can rely on just allowing the Client to create a PaymentIntent and then collecting the card details within the browser context. 

Once the client calls `stripe.confirmPaymentCompleted()` and the status result from the paymentIntent is `succeeded` then to fulfill the tip we can either.

*  listen for the payments on the Server-side via the Stripe webhook
* or have the client send a request similar to the current tipping flow

I think the Stripe webhook is a little better because we would need to implement this regardless to mark orders as paid? the Stripe tipping kind of fits nicely with the other work being done with SKUs

**Comment by tsmartt** [comment]
Closed at stale.
