### ISSUE TITLE
Require 2FA authorization before allowing users to disable 2FA

### ISSUE THREAD

**Issue by jumde** [brave-intl/publishers#2936]
## STR

1. In a open publishers session, navigate to Profile > Security 
2. Disable 2FA

## Expected
User should be asked to re-authenticate before disabling 2FA

**Comment by diracdeltas** [comment]
related: https://github.com/brave-intl/publishers/issues/2179

**Comment by thypon** [comment]
A similar protection should be enabled for before email change.

**Comment by thypon** [comment]
Fixed in https://github.com/brave-intl/publishers/pull/3553
