### ISSUE TITLE
Change contact email flow might need tweaking

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#294]
Needs investigation by myself and @jenn-rhim

**Comment by nvonpentz** [comment]
@alexwykoff @jenn-rhim what is the problem / is this still relevant?

**Comment by alexwykoff** [comment]
I think this was a generic placeholder to show work was happening.  To the best of my knowledge the proper documents have been created as well as a handful of new github issues to track particular mail cases.
