### ISSUE TITLE
Refactor PayoutReports.contents

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2963]
At the moment, PayoutReports.contents stores all the payout report metadata into a single column. This contents should ideally be stored into S3. 

This Github issue will track 2 things:
(1) The deletion of the contents and prevention of more contents being added to the PayoutReport object.
(2) Creating an S3 object which will store a download copy of the payout report contents in CSV format

**Comment by tsmartt** [comment]
Pretty big performance improvement, also reducing the size of the DB. Nick says he doesn't care about historical data, so we could drop this column. This is no longer being used, it is the predecessor to potential payments.
