### ISSUE TITLE
Channel that doesn't exist is allowed to registered with publishers

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#301]
should it or should not? I don't have a YT channel, only have a YT account (by the fact that I have an enterprise google account). But I was able to go through and select the channel and complete the publisher registration. See below

![image](https://user-images.githubusercontent.com/4369856/32959755-84b126d6-cb77-11e7-9916-5793c7895a45.png)

![image](https://user-images.githubusercontent.com/4369856/32959772-9280fb74-cb77-11e7-93b6-54884f0207ef.png)
^ is to show that I haven't agreed to YT TOS to create the channel.

**Comment by tsmartt** [comment]
Closing as stale.
