### ISSUE TITLE
channel verification timeout

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/publishers#3017]
a site channel's verification process seems to fail every time that it is run. the id can be found in the logs of /magic/. not sure if i can post here, but it happens pretty often. every day or so
after querying the db a bit, it seems like the publishers site / domain is not setup as the error stored was `domain_not_found`. perhaps there is a better way to handle these errors? or to try less frequently?

**Comment by tsmartt** [comment]
This is most likely one of the expected 5 or 7 checks after initial set up. This should not fail with an error.
