### ISSUE TITLE
Payout statements broken for Gemini creators

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3035]
## Description

Currently, the payout statements section in the creators.brave.com dashboard only expects Uphold. If the Creator is connected to Gemini, the payout page displays a notice/error saying that there is an issue reading the transactions from Uphold, even though the Creator does not use Uphold. 

**Screenshot:**

![image](https://user-images.githubusercontent.com/11497541/107596550-0d9d6100-6be6-11eb-923f-5f3647bbbb4d.png)

**Comment by Miyayes** [comment]
As a stopgap solution, we can just link to the Gemini creator's account (transaction history) page, until something more specific is created.

**Comment by Miyayes** [comment]
Another stopgap solution is to hide the statements component for any user on Gemini.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/mmnj14/brave_creator_account_connected_to_gemini_but_bat/

**Comment by Photolunatic** [comment]
+1
How can I add myself as being affected by this issue?

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/n7keu4/viewer_contributed_bat_but_it_isnt_in_my_creator/
