### ISSUE TITLE
When the user verifying the channel attempts to verify again, pass them through

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#305]
As long as the user auth is good, and legit channel, and it is the same user who verified it before, I'd strongly recommend us being forgiving and send the user to the dashboard. --> if fixing it this way is relatively cheap. 

![screen shot 2017-11-17 at 11 16 59 am](https://user-images.githubusercontent.com/4369856/32964767-1cc94b36-cb89-11e7-96af-aea72671ca0f.png)

**Comment by lgebhardt** [comment]
I'll work on this

**Comment by lgebhardt** [comment]
@jenn-rhim Do we quietly take them to the dashboard, or show them a message that indicates what happened?

**Comment by jenn-rhim** [comment]
Take them to the corresponding dashboard silently.
