### ISSUE TITLE
Localization bug on creators.brave.com

### ISSUE THREAD

**Issue by AlanBreck** [brave-intl/publishers#3057]
The auto-localization for creators.brave.com directs to `https://creators.brave.com//?locale=ja` (note the double `//`) which results in a blank page. It would appear the correct link is `https://creators.brave.com/?locale=ja`.

### Steps to reproduce:
1. Change default language of browser to Japanese.
2. Go to https://creators.brave.com
3. Observe blank page and URL

**Comment by yachtcaptain23** [comment]
This is working on dev: https://github.com/brave-intl/publishers/pull/3084

Will follow up staging

**Comment by yachtcaptain23** [comment]
This was fixed in https://github.com/brave-intl/publishers/pull/3097

Closing.
