### ISSUE TITLE
webtest-pj.herokuapp.com shows up as unverified on staging pCDN

### ISSUE THREAD

**Issue by jumde** [brave-intl/publishers#3082]
@dlipeles confirmed that: `webtest-pj.herokuapp.com` is correctly verified and Uphold looks good too. This is not picked up correctly by pCDN

![image](https://user-images.githubusercontent.com/1903815/110021084-2a0d5480-7cdf-11eb-8b80-3f8bf63bfa2b.png)

![image](https://user-images.githubusercontent.com/1903815/110021104-2f6a9f00-7cdf-11eb-9e40-53b2054cf702.png)

**Comment by yachtcaptain23** [comment]
The account is marked as a BitFlyer account, chasing down as to whether or not this is supposed to happen.
