### ISSUE TITLE
JP translations: Remove "PayPal" in welcome modal

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3085]
Remove PayPal language ~if user doesn't have PayPal option~ in the welcome modal in order to generalize the experience:

**New translation:**

**ウォレットサービスの接続**

支払いを受けるために、希望する支払いオプションを接続してください。

__________________

This is the second bullet point in the modal below. 

![image](https://user-images.githubusercontent.com/11497541/110172546-4c7c9c00-7dcb-11eb-8100-600c0dccc3c4.png)

**Comment by soi-tnk** [comment]
@Miyayes How about this? This is super general, but surely don't confuse paypal users. New users after March 13 will only see bF button after this popup disappears, so they won't be confused as well.
---
**ウォレットサービスの接続**
支払いを受けるために、希望する支払いオプションを接続してください。
---
^ in English:
**Connect wallet services**
To receive payments, connect your desired payment options.

(original text in English:
To receive payments, your wallet accounts must be connected. Connect Gemini or Uphold for your desired payment options.)
