### ISSUE TITLE
Email Creators with a BAP balance but without PayPal account attached, to attach a PayPal account as soon as possible

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3117]
## Description

Add banner at the top of the Creator dashboard for `?locale=ja` telling users

1. With a non-zero balance;
2. Without a PayPal account already attached 

to attach a PayPal account as soon as possible. 

This banner will be removed at a later date (per @Miyayes). 

Color of the banner should be **red** to indicate importance.

**Text:**

```BAPの支払いを受けるには、クリエイターアカウントにPayPalアカウントを連携してください。まもなく、BATポイントシステムから新しいシステムへの移行が行われます！```

**Comment by dlipeles** [comment]
Notifying relevant Creators via e-mail should be equally good, @Miyayes I will share the e-mail list with you in DM
