### ISSUE TITLE
JP translation: Replace "Points" language in landing page

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3121]
## Description 

On the publishers/creators landing page, there are several instances of "Points" or "BAT Points" language. Replace this with BAT language.

## New translation

1. If it says ポイント alone, replace with BAT
2. If it says BATポイント, then remove the ポイント part and just keep BAT

![image](https://user-images.githubusercontent.com/11497541/112178973-9e496280-8bd0-11eb-9749-fbfde6cdb773.png)

**Comment by dlipeles** [comment]
Hm, I don't see any occurrence of this string `ポイント` in our codebase, but I do see it on the JP landing page. I wonder if we're serving an outdated version from a cache

**Comment by dlipeles** [comment]
Doesn't show up in any search either 🤔 

https://github.com/brave-intl/publishers/search?q=%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88

**Comment by dlipeles** [comment]
Is it possible this is coming from the brave-com repo 🤔  

https://github.com/brave/brave-com/blob/8809d837c6b96deb3b1f2e90ba60ccca43fe9ae7/content/_index.ja.md
