### ISSUE TITLE
Remove ability for Creators to set default tipping amounts in their tipping banner

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3137]
## Description

Currently, Creators can set the set of default tipping amounts in their tipping banner via the Creators dashboard. When present, this will overwrite the general suggested default tipping amounts set by Brave.

![image](https://user-images.githubusercontent.com/11497541/211132649-88f7eeae-26b2-4d06-9b13-15fcbb3c2fa3.png)

Browser/client side: https://github.com/brave/brave-browser/issues/24548 

## Solution

- [ ] Step 1: Remove option to set the set of default tipping amounts on the Creator side in the Creators app UI

**Comment by Miyayes** [comment]
This will become higher priority once we enter Phase 2 of the "Custom tipping amount" feature, where users can edit and save their own default tipping amounts. We do not want a collision between a Creator's settings vs. a User's settings in the browser.

**Comment by Miyayes** [comment]
Example of ongoing maintenance that is required for the values: https://www.reddit.com/r/BATProject/comments/nq2kpa/how_do_i_set_a_1510_banner/

**Comment by jlbyrne** [comment]
I ❤️ deleting code!
