### ISSUE TITLE
Potential Payouts table missing address

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/publishers#3142]
this is causing some of our publishers to not get paid out

**Comment by tsmartt** [comment]
@maikelmclauflin can we get a few more details on this?

**Comment by maikelmclauflin** [comment]
hey, yeah, so it seems like there are some missing addresses in the potential payouts table. i guess my question is, does it even make sense to insert potential payout rows if there is no address to pay out to, at least at the time of generating the payout
