### ISSUE TITLE
Email notification with welcome kit to YT creators

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#317]
Welcome kit contains an instruction on how to get their subscribers to support them:
1.  Steps to create a clickable sticker on their channel header/banner
2. Provide a link for the sticker, which takes users to the YT channel supporter landing page

*note: this email doesn't have CTA.

This email will be sent out manually to all registered YT creators when ready (preferably before 11/30). Thereafter (once all previous users are caught up with the message), this will be part of our automated email notification logic: being sent out when the verification is successful, right after the welcome email.

**Comment by yachtcaptain23** [comment]
Stale issue. Probably need to rethink since BR.
