### ISSUE TITLE
Creators with PayPal account (with bank account attached) are still being told they need to attach a bank account

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3170]
## Description

When Japanese creators attach a PayPal account, they need to connect a bank account in order for the PayPal account to be considered ready to receive payout. However, some Japanese Creators have connected a bank account (and provided screenshots of this), but their dashboard is still telling them they need to attach a bank account to receive payment.

## Some possibilities

1. Could be that they attached the PayPal account and then only subsequently attached a bank account, but we do not check the bank account connection status asynchronously. (Workaround would be for the Creator to disconnect and then reconnect the PayPal account in order to trigger the detection. This happens in the Gemini case.)
2. We do check asynchronously, but the call to PayPal's API is broken, or PayPal's API has changed 
3. Only some bank accounts work. (We've been told by some Creators that although they have a bank account attached, PayPal says that their particular bank account is not eligible for certain kinds of deposits?)

Some of these Creators have sent us screenshots wherein we can clearly see a bank account attached inside their PayPal account dashboard.

**Comment by Miyayes** [comment]
Please send me or Steven a message if you need some example cases.

**Comment by yachtcaptain23** [comment]
Messaged PayPal, they confirmed the API is responding the right message. User issue.

**Comment by yachtcaptain23** [comment]
Talked with @Miyayes, closing.
