### ISSUE TITLE
Landing page for the YT channel supporters

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#318]
This landing page is intended to explain how Brave Payments works, what they need to do/setup to support their favorite YT channels in an easy to understand terms and steps. 

*Plan for release at the same time as the instruction email for the registered YT creators.

Entry points:
- Sticker/badge that YT creators create on their channel header
- Tweet?
- Other ads?

**Comment by jenn-rhim** [comment]
![landing-yt-subscribers](https://user-images.githubusercontent.com/4369856/33409011-2090477a-d52e-11e7-8f48-dee947d28b74.png)

**Comment by mixonic** [comment]
@jenn-rhim can you provide a link to the raw assets for this, or DM them to me? I can take a look at implementing this.

**Comment by jenn-rhim** [comment]
Thanks, @mixonic, for offering your help. It’s done and being launched tomorrow. :)
