### ISSUE TITLE
[Brave Browser Bug] Some Videos can be played on Chrome, but NOT on Brave

### ISSUE THREAD

**Issue by daming-lu** [brave-intl/publishers#3191]
This issue might not belong to this repo. Feel free to move it to the browser repo. Basically, I noticed that for famous video websites like Bilibili (NASDAQ: BILI), the videos on it can be played on Chrome but not on Brave. Others like YouTube, are good.

https://www.bilibili.com/video/BV1ti4y1K7uw

Really hope this bug can be fixed so that I don't need to switch back to Chrome 😄

**Comment by daming-lu** [comment]
![Screen Shot 2021-04-22 at 4 50 16 PM](https://user-images.githubusercontent.com/5635322/115798349-e6ec6b00-a38a-11eb-9ffb-b78812ea75cd.png)

Here is how it works on Chrome (no problem)

But on Brave, it keeps loading forever.

**Comment by Miyayes** [comment]
Hello, can you refile this issue in github.com/brave/brave-browser/issues? Thanks. We cannot transfer it as it's a different organization.

**Comment by daming-lu** [comment]
> Hello, can you refile this issue in github.com/brave/brave-browser/issues? Thanks. We cannot transfer it as it's a different organization.

Thanks, Chris! I've moved it [there](https://github.com/brave/brave-browser/issues/15479)
