### ISSUE TITLE
When trying to reclaim a channel, don't create/destroy publishers

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#321]
To handle #305 we created #319. However, now we have the hidden problem of creating and destroying publishers, which isn't ideal – we should avoid creating a junk record.

**Comment by lgebhardt** [comment]
Eliminating this sort of behavior will be a top priority when we split the owners and allow multiple published properties.

**Comment by jenn-rhim** [comment]
yes, this is a temporary issue. when we move the Publishers to user-based account, instead of domain/channel-based account (coming soon), this case will not happen.
