### ISSUE TITLE
Add validations for all publisher input fields

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#324]
Once logged in, publishers can enter ~100 characters of any kind in to the phone number field.  They should only be able to enter valid phone numbers.

![image](https://user-images.githubusercontent.com/12549658/33102201-a875f04a-cee9-11e7-8e32-b7cc6626b6bc.png)

**Comment by nvonpentz** [comment]
There is phone number validation when registering a website.  So the issue here is the validation after a publisher has logged in and is editing contact information.  I will start on this soon, unless someone wants it.

**Comment by ayumi** [comment]
there's probably a backend change that might also be needed, but the client side validation should handle most of the cases for now.
