### ISSUE TITLE
When locale=ja, cannot verify GitHub, YouTube channel, etc. due to CSRF issue

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3244]
## Description

If locale=ja, verifying channels (such as Github, YouTube) fails with a CSRF error. When the creator changes to locale=en, the channel verification is successful. 

@a-t-s-u-s-h-i was able to reproduce exactly as described above.

## Solution

Fix the CSRF error in the locale=ja case.

**Comment by yachtcaptain23** [comment]
This seems to be a regression when `0007d35b814aa75771ad402d1c64a6d2a97cd548` was merged. Working on a fix
