### ISSUE TITLE
Add built-in retry handling into parent payout jobs

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#3245]
The following jobs don't include Sidekiq's retry mechanism:
```    
Payout::UpholdJob
Payout::GeminiJob
Payout::BitflyerJob
```

This may be the root cause for missing payments.

I believe the easiest solution is to store the last processed Publisher ID into Redis, and when the job resumes, we find the next publisher ID in the `publisher_ids` list and resume from there.

------

Edit: We can also refactor the logic to better improve speed and fetch when we run the following in the `JobImplementation`.

```
      publishers.find_each do |publisher|
        @payout_report_job.perform_async(
          payout_report_id: payout_report_id,
          publisher_id: publisher.id,
          kind: kind,
```

**Comment by tsmartt** [comment]
Let's put this on the docket for next month, right after payout happens. We're already planning to look at the overall architecture and see where we can get speedups.

**Comment by yachtcaptain23** [comment]
Resolved in https://github.com/brave-intl/publishers/pull/3287
Duplicate of https://github.com/brave-intl/publishers/issues/3286
