### ISSUE TITLE
dependabot alert for browserslist

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#3247]
https://github.com/brave-intl/publishers/security/dependabot

 Dependabot cannot update browserslist to a non-vulnerable version
The latest possible version that can be installed is 4.14.2 because of the following conflicting dependency:

react-scripts@4.0.1 requires browserslist@4.14.2 via a transitive dependency on react-dev-utils@11.0.4
The earliest fixed version is 4.16.5.

**Comment by tsmartt** [comment]
Thanks, we'll resolve it.
