### ISSUE TITLE
update and sandbox imagemagick

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#3289]
Imagemagick has a long history of vulnerabilities, more of which are found every year: https://www.cvedetails.com/vulnerability-list/vendor_id-1749/Imagemagick.html

We should either replace it, or update to the latest release and run it in a sandboxed environment.

**Comment by evq** [comment]
@tsmartt since we landed https://github.com/brave-intl/publishers/pull/3335/files can we remove imagemagick and it's associated gem so we can close this out?

https://github.com/brave-intl/publishers/search?q=magick

**Comment by tsmartt** [comment]
This is done as of https://github.com/brave-intl/publishers/pull/3335
