### ISSUE TITLE
Failure to normalize domain when logging in

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#336]
This issue was reported in the [community forums](https://community.brave.com/t/gets-error-message-when-trying-to-log-into-a-verifed-account/10688).

If a publisher verifies "domain-name.com", and they attempt to log in with "www.domain-name.com", the app is unable to find the domain, and the publisher is unable to log in.  Conversely, 
 if the same publisher tries to re-register the domain "www.domain-name.com", the app is able to locate it and informs the user that it is taken.

The user in the forums confirmed that this was the problem, and is able to log in if "www." is omitted.

Publishers should be able to log in with "www." preceding their domain name.

**Comment by dgeb** [comment]
I can fix this together with #297, since it's related. We need to invoke the `PublisherDomainNormalizer` for all domains.
