### ISSUE TITLE
Add reliable way to trigger captcha

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#339]
### Description
Currently there is no reliable way to generate captchas on production and staging.  This makes it difficult to debug errors with captchas.

We should add a query string param that will generate a captcha.

**Comment by nvonpentz** [comment]
@ayumi

Aren't we only redirecting to static#index if the the recaptcha fails in the first place? Shouldn't the captcha be brought up after `@should_throttle` is set to true, at which point we verify it and then redirect to root and flash the failure message only if it `throttle_legit` is false?

It looks like `throttle_legit` will always be false on the first time through. I'm not sure if this is intended.

This will work for #create_auth_token since we are rendering new_auth_token.html.slim when `throttle_legit` is false instead of redirecting to root.  This will set `@should_throttle` and pull up the captcha form, at which point they can try again, and if the captcha form is correct, `throttle_legit` will be true on the second time around, and let them through.

Since we are redirecting to root for #create, the params are not passed with the redirect, so the same strategy that pulls up the captcha on #create_auth_token does not work here, even if we add the `@should_throttle` instance variable to static#index as you've suggested.

We could keep the redirect to static#index and store whether to bring up the captcha in the session/params.  What do you think?

**Comment by ayumi** [comment]
1. Yes, throttle_legit is always false on the first time. This is intended because the person needs to see the repcatcha form and submit it in order to make throttle_legit true.

2. Yes create_auth_token / new_auth_token will be okay.

3. No I don't think we should ever need to set should_throttle in session; instead we should copy over
```rb
# PublishersController
def should_throttle_create?
    Rails.env.production? &&
      request.env["rack.attack.throttle_data"] &&
      request.env["rack.attack.throttle_data"]["registrations/ip"] &&
      request.env["rack.attack.throttle_data"]["registrations/ip"][:count] >= THROTTLE_THRESHOLD_CREATE
  end
```
to StaticController; and in StaticController #index add:
```rb
@should_throttle = should_throttle_create?
```
