### ISSUE TITLE
Support only Webp, Jpg, Png in banner/background image uploads

### ISSUE THREAD

**Issue by tsmartt** [brave-intl/publishers#3407]
[Here](https://github.com/brave-intl/publishers/blob/eafd27b159a4e2893ba73348a2eb5feef494578f/app/controllers/publishers/site_banners_controller.rb#L65-L66) we check for BMP, but the WASM module [does not have it built in](https://github.com/brave-intl/wasm-thumbnail/blob/main/wasm-thumbnail/Cargo.toml#L12).

Edit: actually it just makes sense to support webp, jpg, png. Gif doesn't make sense in our context.
We should display an appropriate warning if the file is of the wrong type.

**Comment by adithyaakrishna** [comment]
@tsmartt I saw that we arent checking for .gif extension as well but the WASM Module has that extension built-in
Can I add that as well?

**Comment by jlbyrne** [comment]
Steps to Reproduce:

1. log into any creators account, and click on the 'tipping banner' button. 
2. on the modal, click on either the logo or banner to see the file selector popup.  Confirm that only .jpeg, .png. and .webp extensions are clickable
3. save the image and confirm no errors on the back end
4. Remove the 'accepted' attribute from the image inputs.  Try and upload a weird file type, like .dmg.  When you attempt to apply your changes, the edit modal should disappear and the banner should be the default banner.
