### ISSUE TITLE
Payout Report Status When Done

### ISSUE THREAD

**Issue by tsmartt** [brave-intl/publishers#3470]
There should be a status indicator on the admin panel reporting when a payout report generation is complete.

**Comment by OAuthBringer** [comment]
Alright, managed to get things running and setup locally, spun out all my different PRs.  I was able to assign myself as admin in dev context without having a yubikey configured somehow.

**Comment by OAuthBringer** [comment]
As far as I can tell so long as a report doesn't fail it should be visible in an incomplete state in admin (not sure if this is true though).  I've already added both status and the percent completion and am working on the specs now.

**Comment by OAuthBringer** [comment]
Removed percent completion and submitted updated PR

**Comment by tsmartt** [comment]
Great work @OAuthBringer
