### ISSUE TITLE
Clearly Communicate Payout Dates for Referrals and Contributions

### ISSUE THREAD

**Issue by tsmartt** [brave-intl/publishers#3488]
The current language is not ideal.

Need to specify referrals happen every 2 weeks and contributions on the Tue/Thur closest to the 13th.

**Comment by jonathansampson** [comment]
Not only payout dates, but which contributions will be paid out as well. For example, with a contribution of 5 BAT received on the 6th of November be processed and distributed a week later on the 13th of November? Or, will that 5 BAT contribution be processed on the 13th of December?

**Comment by tsmartt** [comment]
Wording was improved last week in https://github.com/brave-intl/publishers/pull/3925
