### ISSUE TITLE
Tweak mobile views for dashboard and log in pages

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#349]
After tweaking the mobile views for the homepage in #337 , we have yet to adjust the mobile views for the dashboard and login page.

We need to determine when to address this.

**Comment by mixonic** [comment]
I'm going to focus my effort on an improvement to the logic flow (currently not mobile friendly). Here is a screenshot of the current login page on iPhone 7:

<img width="385" alt="screen shot 2017-12-06 at 2 02 08 pm" src="https://user-images.githubusercontent.com/8752/33679937-187635e4-da8e-11e7-83f8-b120237908be.png">

@jenn-rhim is considering the impact to the dashboard which is probably more extensive and requires detailed mocks.

**Comment by mrose17** [comment]
Blocked on #382 and #385

**Comment by nvonpentz** [comment]
Resolved by #365 and others
