### ISSUE TITLE
Stop telling users to use the Wordpress plugin

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3504]
## Description

If you go to verify your domain name/website and it detects Wordpress, it still instructs the user to use the deprecated Wordpress plugin.

![image](https://user-images.githubusercontent.com/11497541/146304368-8f739e41-2e41-463b-95f1-65e5de957fec.png)

**Comment by diracdeltas** [comment]
This seems pretty important to do if we aren't maintaining the wordpress plugin anymore.

**Comment by OAuthBringer** [comment]
@Miyayes Can you provide any info on replication steps for this? Should be pretty straight forward to remove.  Are you getting the error when visiting a wordpress site?

@tsmartt Any additional context here/dev context tricks to replicate/review

Thanks, literally first day on the app so just getting the lay of the land.

**Comment by OAuthBringer** [comment]
Figured it out.  Just tried to add wordpress.com and it showed up.

**Comment by OAuthBringer** [comment]
I don't seem to be able to remove an unverified channel via the app.

**Comment by OAuthBringer** [comment]
Verification is being triggerred via a param being passed from the frontend
