### ISSUE TITLE
Remove dependency on https://github.com/dlipeles/omniauth-reddit

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#3512]
https://github.com/dlipeles/omniauth-reddit needs to be moved into an official brave repo

**Comment by dlipeles** [comment]
transferred this one over to @tsmartt , noticed a permission issue trying to transfer to brave-intl , hope it helps 

this closes #1950 too

**Comment by diracdeltas** [comment]
@tsmartt - you can try to transfer to brave-intl, an admin will probably need to approve

**Comment by diracdeltas** [comment]
sgtm, thx
