### ISSUE TITLE
Create custom fetch-related errors for fetch-utils.js

### ISSUE THREAD

**Issue by dgeb** [brave-intl/publishers#352]
As @mixonic [pointed out](https://github.com/brave-intl/publishers/pull/347#discussion_r154732111), our custom fetch utils should be using explicit error classes that can be caught specifically instead of the overly broad `catch` handlers in use on the dashboard.

**Comment by ayumi** [comment]
Does this impact anything right now, or is it a proactive thing to improve fetch error handling?

**Comment by dgeb** [comment]
@ayumi It would be a proactive measure to allow for explicit catching of expected errors and bubbling of unexpected errors. It does not fix any known problems, but it's possible that it could reveal some unknown problems.

**Comment by yachtcaptain23** [comment]
Code no longer in use. Closing.

Primary logic for fetching async has been moved to `app/javascript/utils/request.js`
