### ISSUE TITLE
the verification_wordpress page needs an escape hatch

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#358]
If the publisher is directed to https://publishers.basicattentiontoken.org/publishers/verification_wordpress and the site really isn't wordpress, there needs to be an escape hatch with a link to `publishers/verification_choose_method`

**Comment by jenn-rhim** [comment]
2 links are added below the instruction text as the escape hatch: taking the user to the instructions pages for the 'regular domain' and for the 'github site' respectively.

![image](https://user-images.githubusercontent.com/4369856/33685487-982cb1e4-da86-11e7-8d39-0b39f1a43b2e.png)
