### ISSUE TITLE
Display error message when trying to connect Gemini Wallet that has same recipient ID as another

### ISSUE THREAD

**Issue by tsmartt** [brave-intl/publishers#3625]
Currently we allow you to connect a Gemini wallet, even if that same wallet is connected to another account. You can connect he wallet, but the background job to add a recipient ID fails silently when we go to update the connection's recipient ID. We should instead put the wallet in a bad state and display an error to the user.

**Comment by tsmartt** [comment]
Any non-active status should work, but double check that we don't reuse another one somewhere else in the system.

**Comment by tsmartt** [comment]
This should be the same across all wallets. Uphold, Bitflyer, Gemini. 

The line that fails is [here](https://github.com/brave-intl/publishers/blob/0aefd1117a3061b4311ec05401debeb720a07f69/app/jobs/create_gemini_recipient_ids_job.rb#L12)

It fails silently.

**Comment by OAuthBringer** [comment]
I've confirmed that the duplicate logic functions, but it is showing an arfiact continue to veri
<img width="624" alt="Screen Shot 2022-05-19 at 1 01 24 PM" src="https://user-images.githubusercontent.com/8813557/169357246-ef7798d0-704e-43e0-b055-fdf1f2515310.png">
fyurl.  That should be removed.

**Comment by OAuthBringer** [comment]
Resolved some time ago.
