### ISSUE TITLE
Advise users on 2 factor auth recovery

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#364]
2017-12-07 21:25Z: Edited the below per @diracdeltas 's comment.

We have U2F as a dark launched feature, however it has a UX issue where a user who's lost their token will be locked out of their account, requiring manual intervention. 

Before launching this publicly, we need to add a recovery flow, ~~where we offer some one time use password the user can use to rescue their account~~. Ideally we can share this flow between U2F and TOTP.

~~Github two-factor docs present a good example of the UX:
https://help.github.com/articles/downloading-your-two-factor-authentication-recovery-codes/
https://help.github.com/articles/recovering-your-account-if-you-lost-your-2fa-credentials~~

This will be primarily advisory, such as a link to "How do I recover my account?" which explains to setup an alternate U2F key for recovery, or to contact us.

@jenn-rhim We mainly need a UX spec. ~~or an Okay that borrowing from the Github UX would be ok (I'm in favor of that, so we need to do less thinking :) )~~

cc @mixonic

**Comment by diracdeltas** [comment]
discussed in slack. i feel that while this is nice to have, it's not a blocking feature for releasing 2fa.

1. users can register multiple 2fa devices if they wish and use one of them for recovery if they lose the others
2. in my experience, many ppl don't copy backup codes at all or lose them by the time they need time, so we need a fallback anyway
3. fallback will probably end up being phone/video call with support person who does some kind of identity verification (like using their on-file W9); we can just use this as the primary recovery strategy for now

for advanced users, we could ask for a pgp public key and email them a recovery email encrypted to it (1st factor = email account ownership, 2nd factor = pgp private key)

**Comment by ayumi** [comment]
Thanks, I updated the issue with your feedbacks!
