### ISSUE TITLE
Don't initialize a new blank Uphold Connection on every user creation

### ISSUE THREAD

**Issue by tsmartt** [brave-intl/publishers#3668]
https://github.com/brave-intl/publishers/blob/staging/app/controllers/publishers_controller.rb#L165-L168

**Comment by OAuthBringer** [comment]
This is related to https://github.com/brave-intl/publishers/issues/3701

The reason the uphold connection is called at all in the controller is in an effort to populate an available currencies selection on the dashboard. 

I'm happy to burn it all away.

**Comment by OAuthBringer** [comment]
Confirmed transactions 500 is resolved

**Comment by OAuthBringer** [comment]
Resolved a while ago
