### ISSUE TITLE
Remove deposit currency selection and ensure everything is in BAT (Uphold)

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3701]
## Description

- [x] Remove currency selectors across the Creators UI, and always use BAT
- [ ] For creators who have a non-BAT deposit currency set, switch them to BAT and send them an email letting them know. 
- [ ] Test and make sure that creators who were set to a previous deposit currency now have a BAT receiving card, and successfully receive BAT without it being auto-exchanged for whichever other currency. (Note: If you send BAT to a non-BAT x card, it will be automatically converted into x.)

**Comment by OAuthBringer** [comment]
I'm looking at all of this stuff right now due to updates to Uphold's wallet connections.  I think this is actually very simple and  resolves a number of bugs associated with uphold.

**Comment by OAuthBringer** [comment]
<img width="1055" alt="Screen Shot 2022-06-10 at 10 53 50 AM" src="https://user-images.githubusercontent.com/8813557/173092724-5cac35cd-f23b-4761-9c12-0dc0ae98f8e9.png">

Pretty easy to remove the selection/limit to only bat.

Removing the dialog itself will be a little bit more effort but as a minimal first step this enforces BAT only.

**Comment by OAuthBringer** [comment]
Hard coding the default currency to BAT for all new connections removed the dialog entirely so that's no longer an issue.

**Comment by OAuthBringer** [comment]
@Miyayes Could you please provide copy for the email notification? Thanks.

**Comment by Miyayes** [comment]
Dear Brave Creator,

We'd like to let you know that all payout deposits to Uphold accounts, moving forward, will always be sent and received in BAT. Of course, once you receive BAT in your Uphold account, you can continue to exchange it or withdraw it as you like on Uphold.  

You're receiving this email because the default deposit currency in your Brave Creators account was set to a currency that was not BAT. 

Thank you for being part of Brave Creators! 

--------------

@OAuthBringer wdyt? Short and simple.

**Comment by OAuthBringer** [comment]
@tsmartt @jlbyrne The first section of this is also present in staging right now.

To test.

1. When creating a new uphold connection (if you are KYC'd), you will only have the option to select BAT as the default currency on create, and when you go to change it after creation BAT will also be the only options.
2. If you already had a connection with a different default currency, only that default currency and BAT will be available when you go to change it.
3. Changing from the non-bat default currency will remove it as an option and only BAT will be available to the user from then on.

**Comment by OAuthBringer** [comment]
@Miyayes The restriction of BAT for available currencies is in prod now FYI.

Follow up steps required, changing the default value/syncing with uphold is not a task to be taken lightly.

**Comment by OAuthBringer** [comment]
This at least gets us to all new connections are using BAT and that's the only option.

**Comment by betheodo** [comment]
On the Uphold side an error occurs with the inability to create a card, which leads to an error binding wallet.
