### ISSUE TITLE
Handle changes in domain registration

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#376]
Related: https://github.com/brave-intl/bat-ledger/issues/42

When domain registrations change or expire, we should invalidate the Publisher record otherwise the old owner can continue to collect Brave Payments while they no longer own the domain.

To resume using Brave Payments again, the publisher needs to reverify their domain from scratch (#377).

**Comment by ayumi** [comment]
This is blocked on multi-channel.

We need Eyeshade to ping periodically for publisher domain registrations, and notify a Publishers endpoint of a lapsed publisher domain. This would then deactivate the domain from the publisher's account on Eyeshade and Publishers and require reverification.

**Comment by nvonpentz** [comment]
@ayumi @mrose17 @flamsmark Should we discuss this at the next security discussion? I believe that is 2018-03-27

**Comment by flamsmark** [comment]
Yesterday, we agreed that the new owner can attach the domain to their Publishers account just by demonstrating domain control. Do we also want to take any proactive action on registration change or expiry?

**Comment by nvonpentz** [comment]
@flamsmark I think we should.

There have been 0 reported cases of domain turnover, so there are more pressing concerns, but I think we should implement this in the medium future.
