### ISSUE TITLE
Allow publishers to reverify their domains and replace their old Publisher account

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#377]
While discussing #364, we decided publishers with 2FA enabled who have lost their 2nd Factor can recover their accounts by reverifying their domains from scratch. Afterwards, we should invalidate and replace the old Publisher record and notify the previous Publisher email address.

Care should be taken to prevent active publishers from being harassed or otherwise DOS'd (e.g. anon shouldn't be able to disable Publisher accounts by spam retrying this flow). Adding to rack-attack rate limiter should be sufficient.

This reverify workflow can be reused in (#376); when domain registrations lapse or change Publishers will need to reverify as well.

Additional notes from #640:

1. A publisher requests to reverify the channels in their account (either for changes in ownership or for missing TOTP codes), and successfully demonstrates ownership
2. We send emails to the current owner alerting them of the activity
3. If there is no contest after a waiting period (3 days?), we allow the publisher to reset TOTP codes, or claim ownership of the channel(s)

* If there is a contest we manually mediate.
* If this results in an account without any channels or pending BAT, the account is removed.

**Comment by ayumi** [comment]
This will be an essential flow in the medium future, both for 2FA recovery but importantly #249 changes in domain ownership.

I believe eyeshade currently disallows re-registration of domains, so we might need to adjust that.

**Comment by ayumi** [comment]
This might be blocked on Multi-channel, which will result in some architectural changes.

**Comment by mixonic** [comment]
@kpfefferle and I discussed this a bit. The description on this issue describes a recovery method based on the old world of publishers having a single channel. We agree this is blocked.

Some options:

* I have mild concern about using control over any channel an owner has for a valid second factor. Basically, we should not treat control over a channel as a valid second factor. Allowing this would allow a user with access to an accounts email address and one channel to access the account and *all* channels for that owner.
* We could permit control over a channel to be a valid second factor anyway, over my above concerns. At the least, if we do this, we should disclose on the 2FA page that no matter what a user registers control over any channel is a valid second factor.
* Finally what we suggest is better: Any owner can claim a channel away from another owner. Thus if a user lost access to their account (lost a U2F device and had no fallback) and we refused to give them access manually, then they would need to register a new account with a new email address and claim the channels to that owner via verification. This is maybe even what the current implementation permits (cc @lgebhardt). The downside here is that if this happened there would remain a zombie account nobody can log into, and it would be coupled to the user's email. This sounds like very much an edge case though.

**Comment by lgebhardt** [comment]
I'm not opposed to allowing a channel re-verification as a third factor, but it does weaken the system. But so does allowing a channel to be moved to a new email. In either case an owner that loses their computer or phone, and it's password management, would allow a channel to be moved or used to reverify. The end result is still the loss of the account.

My concerns with the last option are the zombie account, but more so the fact that the user can no longer use that zombie email address. So if you lose the U2F device you've also lost use of that email address for brave. If we go this way I think we should clean up the owner account when the last channel is removed through this process. Then the owner could change emails back to the original. That's slightly better, but still requires two email addresses. It's also quite a lot of work for an owner that has many channels. This will require a rework of the validations for uniqueness of channels and behind the scenes will be messy (think of how many people may try to claim google.com each day).

**Comment by lgebhardt** [comment]
> We send emails to the current owner alerting them of the activity

In order for a locked out user to contest this change we need to allow the transfer to be contested using a link that does not require a login. Should we provide an approval link as well in this email?

**Comment by nvonpentz** [comment]
I think that they should wait the timeout period regardless, so no approval link.  But let's also hear from @flamsmark.

**Comment by lgebhardt** [comment]
In the case of a contested channel the user can click on a link in the email. Should we make this a two step process that uses an intermediate page instead of the link(s) in the email directly taking the actions?

For example the link in the email takes you to a page on the Publishers site. From there the user can see some more details, such as the name of the other owner that's trying to claim the channel, and the time the transfer will automatically happen. Then they can click a button to reject the transfer (or approve it if desired).

The final design of this page would need to be provided by @jenn-rhim.

**Comment by nvonpentz** [comment]
I think taking them to a separate page is a good idea, but we should hear from @jenn-rhim next week about this.  @lgebhardt Can you still make progress on this until then, or are you blocked?

**Comment by lgebhardt** [comment]
I can make progress.

Another option for the separate page would be to let the publisher fill out a reason for rejecting the transfer. That could be sent using an internal email so we can monitor the process..

**Comment by lgebhardt** [comment]
@nvonpentz After sleeping on this I agree that we should only allow rejections based on the email. It's possible for emails to be intercepted, and that would provide a route to steal a channel. Assuming the user went to the trouble to setup 2 factor authentication they were trying to avoid that risk. 

I do think it should be possible to approve a transfer from the dashboard, but that's sort of an edge case since the user could remove the channel and then add it on another owner account if they have login access to their original owner account.

**Comment by nvonpentz** [comment]
@lgebhardt Those were my thoughts exactly.  In the case in which their email is compromised, we're relying on them noticing the suspicious activity during the waiting period.

I think being able to approve a transfer from the dashboard is fine, but it feels kind of like a misuse of the tool.  We should try and nudge publishers to just remove and reverify their channels with the UI in the that case.

**Comment by lgebhardt** [comment]
@jenn-rhim We need UX for the following:

## Dashboard:
- How channel appears for the primary owner if it is being claimed by another
  - Option to reject transfer
    - Should we collect any user input?
  - Option to approve transfer?
- How channel appears to secondary user until channel is approved or rejected by primary owner

## Rejection process:
  Do we reject just by navigating to a url in the email, or do we take them to a page that describes the process with details and provides an option to reject? I'm in favor of a page to handle the rejection process as it allows be better error displays and the possibility of explicit conformation actions such as a checkbox to confirm the user agrees.

Emails:
  - To primary owner when channel is being claimed by another owner
  - To secondary owner after claiming channel
  - If rejected:
    - To secondary owner (claimer) that channel was rejected
    - To original owner that channel transfer was rejected.
  - If approved:
    - To secondary owner (claimer) that channel was approved
    - To original owner that channel transfer was approved and they no longer own this channel

**Comment by flamsmark** [comment]
I'm 100% agreed that there should be no way to approve a transfer from an email, only to contest it.
