### ISSUE TITLE
User-based account creation via email verification for all publishers: Landing page change

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#378]
Publishers create their accounts via email verification: 
1. email verification fulfills user's account creation
2. upon clicking the access key from the email, the user needs to be taken directly to the dashboard in a blankslate state. 

Changes in the landing page:
![1-landing](https://user-images.githubusercontent.com/4369856/33747496-33b126ee-db78-11e7-9fcf-20a27b3c9b3d.png)

**Comment by nvonpentz** [comment]
@jenn-rhim is there anything left to be done on this?  This is how it is currently:
![image](https://user-images.githubusercontent.com/12549658/37421103-d4c4e7b6-278e-11e8-8c06-dda2314bea94.png)

**Comment by nvonpentz** [comment]
Closing with jenn's approval
