### ISSUE TITLE
User-based account creation via email verification for all publishers: Sign Up page

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#379]
Publishers create their accounts via email verification:

1. email verification fulfills verifying the user identity.
2. upon clicking the access key from the email, when valid, the user is presented with the 2nd screen that asks them to enter name and decide on marketing opt-out.
3. Clicking Sign up button takes the user directly to the dashboard in a blankslate state.

**Sign-up page** (new: this page is needed to accommodate Oauth options in the later phase):
![2-sign up](https://user-images.githubusercontent.com/4369856/33747613-bf63f644-db78-11e7-99e4-d89200aa957c.png)

**Return from email: complete sign-up**

![signup-optout](https://user-images.githubusercontent.com/4369856/34026206-3f70108a-e109-11e7-9599-69e24bcb5073.png)

**Comment by ayumi** [comment]
Requires #382

**Comment by dgeb** [comment]
Now that an email address can only be associated with a single account, we need to consider what happens when a user attempts to join with an email already associated with an account.

One potential solution is to show the same "Email sent" page but actually send a log in email instead of a signup email. In this way, we can limit account exposure by not revealing whether a particular email address is taken.

**Comment by dgeb** [comment]
Although the "Return from email: complete sign-up" page above shows a checkbox to list a site publicly, I think that option is transitioning to be per-channel and not per-account.

@jenn-rhim Can you confirm that that this checkbox should not be present on this page?

**Comment by jenn-rhim** [comment]
@dgeb -- per earlier comment on 'email (account) already registered' -- we'll **silently handle** this as there's no fundamental difference in the user requirements: i.e. we just sent the user to the login page as you noted. 

as for the opt-out checkbox, this became the account level flag: we will skip the opt-in per channel. this only comes up when the user first signs up.  

that reminds me, with this account model change, we might run this interstitial that contains the name field, the opt-out and TOS, for all users who sign in for the first time after this transition-- this will give us the good rebase for all accounts.  what do you think? @ayumi

**Comment by ayumi** [comment]
@dgeb The TOS is currently linked from the app in prod and I believe it's legit (updated 2018-01-05):
https://basicattentiontoken.org/publisher-terms-of-service/

**Comment by jenn-rhim** [comment]
@dgeb @ayumi 
the **marketing opt-out copy** has been requested to change:

'Yes, help me increase contributor awareness by listing my site in Brave’s marketing channels.'

![signup-optout](https://user-images.githubusercontent.com/4369856/34843974-dcb067a2-f6c4-11e7-8757-6c1b5b4d5c3f.png)

**Comment by dgeb** [comment]
@ayumi @jenn-rhim great - thanks for the clarifications 👍

**Comment by dgeb** [comment]
@ayumi I believe this has been completely implemented now that #492 has been merged.
