### ISSUE TITLE
Change text to remove "wallet" language in "Uphold is reporting to us that your account connection is out of date." error messaging 

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3804]
## Description

Replace: 

>Uphold is reporting to us that your account connection is out of date. This could be the result of changing your Uphold password or other changes on your Uphold account. Please try disconnecting and reconnecting your wallet.

With: 

>Uphold is reporting to us that your account connection is out of date. This could be the result of changing your Uphold password or other changes on your Uphold account. Please try disconnecting and reconnecting your Uphold account. 

(Remove "wallet" language.)

**Comment by OAuthBringer** [comment]
👍 Easy enough, I'll move this out with the capabilities updates

**Comment by OAuthBringer** [comment]
PR is up, currently blocked by some security updates that are also blocking the uphold updates.
