### ISSUE TITLE
Inform the user if the token is expired and allow them to send a new key

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#381]
when the access token is expired, allow them to resend the fresh key to the email they came from in one click.

![login error](https://user-images.githubusercontent.com/4369856/33748068-59c13b1e-db7b-11e7-9bf3-0b88d0df49dd.png)

**Comment by nvonpentz** [comment]
@jenn-rhim should we include the email address that we will send the login link to in the message?
