### ISSUE TITLE
Statistics of Donates to Channels

### ISSUE THREAD

**Issue by betheodo** [brave-intl/publishers#3816]
Why not add statistics for publishers.
For example, a separate module to report who and when donated.
It would be very convenient to understand what country you most donate users.
For example, add the IP of the user when donating, so you can understand what country it is from.
Or Brave does not track users who donate to the publisher by IP?
So you can understand which countries like the content more and bet on it.

**Comment by Miyayes** [comment]
Naturally, given the privacy premise of Brave, this kind of information is unknown to us and we do not track it.
