### ISSUE TITLE
Change "{custodian} wallet" text to "{custodian} account"

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/publishers#3817]
## Description

**Example:** 

![image](https://user-images.githubusercontent.com/11497541/182784765-0680e0a2-f599-46b7-ac29-4112a9c25a41.png)

Can be changed to "Gemini account" instead. 

I think we should start moving away from "wallet" language when dealing with custodial options as well. Especially with "Brave Wallet" for Creators in the works, it will be good to disambiguate. Preferred language is "{custodian} account". For example, it makes straightforward sense to users that they have an *account* on Gemini, Uphold, bitFlyer, and they can connect that *account* to their Brave Creators account to receive payouts, etc. 

This will also better match the language on browser/client, where we no longer use "wallet" language unless talking about Brave Wallet/real web3 wallets.

**Comment by OAuthBringer** [comment]
👍
