### ISSUE TITLE
Wallet connect Uphold disconnect and reconnect error

### ISSUE THREAD

**Issue by nndcneyut98** [brave-intl/publishers#3818]
![Screenshot 2022-08-06 100106](https://user-images.githubusercontent.com/59326605/183230868-4d8a9b69-c6e1-475c-bec6-4ad7c4606dcb.png)

Proceed to disconnect uphold wallet when having problem "Uphold is reporting to us that your account connection is out of date" and then get error "Could not establish Uphold connection. It looks like your Uphold account is already connected to another Brave Your Uphold account can only be connected to one Brave Creators account at a time.

**Comment by nndcneyut98** [comment]
@OAuthBringer pls help

**Comment by OAuthBringer** [comment]
@nndcneyut98 Is this still an issue? I made some updates to this recently that should fix the issue for most users that encounter it.

**Comment by nndcneyut98** [comment]
@OAuthBringer yes sir, i disconnected my wallet and reconnected it, and had the above problem

**Comment by OAuthBringer** [comment]
@nndcneyut98 It means there is an existing publisher account that is connected to the same uphold wallet and we enforce 1 at a time.

**Comment by nndcneyut98** [comment]
@OAuthBringer I only have 1 up hold account and 1 publisher account. I just proceed to disconnect it when I get the error "Uphold is reporting to us that your account connection is out of date" and can't reconnect and it shows the message like above.

**Comment by nndcneyut98** [comment]
I disconnected in both uphold and publisher account

**Comment by Brave-Matt** [comment]
@nndcneyut98,
For support requests like these, we typically prefer to handle them on our [Community website](https://community.brave.com) so our Github repos don't get cluttered with support requests. Please feel free to DM me there (`@mattches` on Community) and I'd be happy to take a look at your case.

Thank you.

**Comment by nndcneyut98** [comment]
@Brave-Matt  i post it but no any admin care https://community.brave.com/t/cannot-uphold-connection-when-disconnecting-and-reconnecting-creator/418844/7
