### ISSUE TITLE
Multi-channel support: dashboard blankslate state

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#382]
**dashboard global change**
1. global header: links- Dashboard, Add Channel, Log Out under expanded user menu
2. user's name (if we get it via OAuth) should prevail over email
3. Contribution balance: move to the top left of the content area

**blankslate 'only' items** (blankslate=no channel has been added/verified for this account)
1. Messaging next to the balance: inform the user the balance is not shown until at least a channel is added
2. Repeat CTA 'Add Channel' in place of where the actual added channel will be displayed: allow the entire area to be the click target.

![4-dash-blank](https://user-images.githubusercontent.com/4369856/33748196-f4cdd48c-db7b-11e7-8342-d91e0ff633f8.png)

**Comment by lgebhardt** [comment]
@jenn-rhim Is the dashed box in the image part of the design? Or is it just there to denote the target area?

**Comment by dgeb** [comment]
@jenn-rhim do you have assets for the blue info icon? I'd guess this will look quite similar to `icn-warning` (the red exclamation).

**Comment by dgeb** [comment]
@jenn-rhim @ayumi This is the current blank slate dashboard view:

![screen shot 2018-01-24 at 1 23 17 pm](https://user-images.githubusercontent.com/29122/35349731-c4a38500-0109-11e8-8a77-13545d6e1a56.png)

Differences include:

* The `Dashboard` label is not shown in the header.
* The warning icon is used next to the text "Add a website or YouTube channel to see how much your fans on Brave have contributed so far." This differs from the blue info icon, but I don't have that asset.

Please confirm whether you'd like me to make any of these tweaks so we can get this closed. Thanks!

**Comment by jenn-rhim** [comment]
@dgeb let's keep the DASHBOARD. it's part of the nav (though we don't have a deep structure right now). 

I'm sending the asset over the slack.
