### ISSUE TITLE
Multi-channel support: verification process

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#383]
- no fundamental changes to this process for now
- except this module is spawn off of the dashboard and returns the user to the dashboard

**Changes:**
1. remove global header for Brave Payments
2. process name, step indicator, and cancel in the process header
    -- process name: Add Channel
    -- step indicator: no half circle needed (every step is a whole circle)
    -- cancel returns to the dashboard 

- **no header** on the channel type screen:
![7-1-addch-type](https://user-images.githubusercontent.com/4369856/33748700-d78b0432-db7e-11e7-8f6b-0843cb081ef1.png)

- remove all other fields except 'domain' field on the domain info screen:
![5-step1 domain info](https://user-images.githubusercontent.com/4369856/33748740-21f43052-db7f-11e7-81be-1d6db5887d5b.png)

- verification method screen:
![6-step2 verif method](https://user-images.githubusercontent.com/4369856/33748786-5584db38-db7f-11e7-9eec-4f38616bb164.png)

**Comment by dgeb** [comment]
@ayumi I believe this can closed via #501
