### ISSUE TITLE
Multi-channel support: dashboard channel list

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#385]
For now, the channel info is limited to
1. channel icon: favicon for the website (if we can get it easily, otherwise generic icon shown in the first mockup below), YT channel avatar
2. channel name: the same, domain or YT channel name
3. date that the channel is added
4. action, 'Remove Channel' --> will get user's confirmation on a dialog
5. 'Brave Verified Pub' opt-in toggle
6. Status: if not verified -- "Verification in progress" or "Your website is not approved"
7. Your website is not approved accompanies an action, 'Request Review' link.

*Uphold wallet card: connection status -- Connected (green circle) or Not Connected (gray circle) with the ability to disconnect.

*the opt-in toggle is removed from statement/contact card; becomes channel-specific.

![8-publisher dashboard](https://user-images.githubusercontent.com/4369856/33749117-e90266a4-db80-11e7-9824-705fa701a784.png)

![9-pubdash2](https://user-images.githubusercontent.com/4369856/33749608-813f2c70-db83-11e7-81b0-740f344efa42.png)

**Comment by lgebhardt** [comment]
How will the channels be sorted?

Can the user sort or filter channels?

If a website channel has not yet submitted the site for verification what will the process be to step back into the flow?  There are two states an unverified website channel can be in: awaiting user actions or waiting for the system to complete the verification process.

Will there be per channel statements?

In the upper right where does the icon and displayed name come from?
What does the drop down arrow do?

We should probably have an issue to describe the Remove Channel flow. Will it have the ability to transfer a channel to another owner account?

**Comment by jenn-rhim** [comment]
1. for now, we will just use simple rule, sort reverse chronologically, i.e. newer entry on top.  (then will adjust as necessary in the future with status or name, but let's not worry about this)

2. no, we won't have the sort or filter control that user can use for now.

3. we won't log the site that the user hasn't committed the verification. i.e. it won't show up in the dashboard.  the verification process is simple enough that it's not a huge saving for the user or for us to keep the state. if the user canceled a site verification, they should re-start.

4. yes, there will be, in the near future version.

5. default avatar comes from us, which user can change with their photo -- will get to this in the next round. I'll provide the default generic avatar.  displayed name is email for now (until we have a user profile page).  dropdown will only supply Log Out at this moment.

6. we will ask user to confirm in a dialog. upon confirmation, the channel will be removed from the dashboard (with a nice transition :) ).  no, we won't have the ability to transfer the ownership here (will discuss a few different viable solutions soon and firm up the plan).

**Comment by lgebhardt** [comment]
Regarding 3, there is the verification token they need to enter into their site (DNS, wordpress or github process). If we don't keep the record we lose this token (if it's per domain) and the user may not realize they need to enter a different token, if they entered one in a previous incomplete session. 

We could keep the token on the Owner account and all their domains would use the same token. This might be good in other ways, allowing a user to reuse the same token to identify themselves. Is this something we want to do?

**Comment by mrose17** [comment]
@jenn-rhim - we need to keep the token around, as @lgebhardt suggests. i think we need to display sites claimed -- but not verified -- at the top of the list with "verify" and "cancel verification" buttons.

what do you think?

**Comment by jenn-rhim** [comment]
i agree - once the verification token is issued for a specific domain, but the user's session has timed out prior to clicking the 'Verify' button, we should allow users to 'resume'.

what i mentioned above is for user specifically **canceling the process**, one of the cases for verification started but 'not submitted', in which case we should honor the user's explicit desire and revoke the token as well as the domain record.  

**time out** is another case, and especially we don't know where the user is in the out-of-bound steps with regard to handling of the token, it'll be better for both of us to revive the session.

**Comment by dgeb** [comment]
@jenn-rhim We need the following assets:

![screen shot 2018-01-08 at 1 10 54 pm](https://user-images.githubusercontent.com/29122/34685162-7ce67632-f475-11e7-9dcc-0ce59db8a935.png)

![screen shot 2018-01-08 at 1 11 01 pm](https://user-images.githubusercontent.com/29122/34685164-7f06b512-f475-11e7-81c7-b783800957d2.png)

Thanks in advance!

**Comment by ayumi** [comment]
Non-urgent feedback:

Considering we will add different platforms in the future, it might be nice to have a way to easily determine channel platforms since channel names and thumbnails may be similar across platforms.

I see in the pics above we show "___ on YouTube"; perhaps we want to show an icon?

**Comment by dgeb** [comment]
@ayumi I believe this can closed via #501
