### ISSUE TITLE
Problems verifying wordpress site

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#387]
Some members of the Brave community have [reported](https://community.brave.com/t/trouble-verifying-wordpress-site/11783) that they are unable to verify their wordpress sites:
> I have downloaded the well-known-uris plugin and added the verification code, but nothing ever seems to work or happen.

This user's domain is https://peculiarmonkeys.com/

Publishers should be able to verify their wordpress website by following our directions, or at least be updated as to why their verification process has stalled, and what to do about it.

**Comment by ayumi** [comment]
Wordpress makes up over 30% of websites so it's very important for us to have solid support.

We should figure out improved logging/error messages for the wordpress plugin to help diagnose issues.

**Comment by ayumi** [comment]
Fixes underway in https://github.com/brave-intl/brave-payments-verification/pull/2

**Comment by nvonpentz** [comment]
+2 from the [community forums ](https://community.brave.com/t/trouble-with-site-verification/12958)

**Comment by ayumi** [comment]
our wordpress plugin is fixed and live at https://wordpress.org/plugins/brave-payments-verification/ !

**Comment by nvonpentz** [comment]
Duplicate of #546, closing this in favor of the newer issue.
