### ISSUE TITLE
2FA Log in

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#393]
![6-2fa-authcode](https://user-images.githubusercontent.com/4369856/33983955-cf3ffe9a-e06a-11e7-90d2-75c474965e30.png)

![7-2fa-authcode-error](https://user-images.githubusercontent.com/4369856/33983963-d4a1fb54-e06a-11e7-8a5c-4ad58913ddce.png)

![8-2fa-securitykey](https://user-images.githubusercontent.com/4369856/33983965-d7f6d4a0-e06a-11e7-8041-efc94b25768a.png)

![9-2fa-securitykey-error](https://user-images.githubusercontent.com/4369856/33983970-dc1940cc-e06a-11e7-969a-6575ca183c5a.png)

**Comment by mixonic** [comment]
Headlines in these mocks use Poppins Regular which is available on 
 Google fonts: https://fonts.google.com/specimen/Poppins Currently headlines are in `"Open Sans", Arial, san-serif` per styles: https://github.com/brave-intl/publishers/blob/staging/app/assets/stylesheets/variables/fonts.scss#L136.

Body test in the mocks is Helvetica, actual site sill uses `"Open Sans"` which is provided as an asset by the application.

I'll experiment with opening a PR to change the font across the UI.

**Comment by mixonic** [comment]
Similar to what I mentioned on https://github.com/brave-intl/publishers/issues/395#issuecomment-355069546, the only remaining work here is related to error reporting styles.

**Comment by mixonic** [comment]
The remaining bits here (only the error styles) I'd like to have @jenn-rhim take a fresh pass at. The current versions are:

**TOTP Registration**

<img width="1024" alt="localhost_3000_publishers_two_factor_authentications_request_totp true" src="https://user-images.githubusercontent.com/8752/34574679-fc23ed4a-f12c-11e7-8b9e-8a2b44d1424c.png">

**U2F Registration**

<img width="1024" alt="localhost_3000_publishers_two_factor_authentications" src="https://user-images.githubusercontent.com/8752/34574680-fc3f0544-f12c-11e7-9bbe-96de53df5966.png">

The items I think need consideration are:

* The error style at the top of the "sub panel" (the box with rounded corners) I think is a solid improvement on the current TOTP error style. The TOTP errors use a general "flash" message style. We can change that so flash errors appear as the design in this issue.
* In general errors should be presented to the user close to where they took an action. For example near the button or at the top of a form. Again the design here is better than the TOTP design, but I'm not sure it is better than the current U2F version which reports the error just above the retry prompt and where previously instructions were present.
* The U2F error design on this issue doesn't remove the text "Insert your security key..." when the error is present. Those instructions should not be visible, as the user must first click "Try Again" before they can follow those instructions successfully.

@jenn-rhim and I can hash it over over a chat/hangout if needed. I don't think I'm suggesting massive changes, just some tweaks. I'd like to move this to a P2 though as a non-blocker for launch.

**Comment by jenn-rhim** [comment]
re: the location of the error message...

1. I'm developing the design pattern for the error message, depending on the type of error: global vs. local (i.e. page level error vs. control/field level), and there's also hybrid. 

And this one, arguably* I'd define it as a page level problem. And for the page level error, the error message UI is what I presented in the mockup.  

2. definitely the message in the main UI needs to change to 'Not authenticated.' or something like that (I'd like keeping the wording really simple). And clicking 'Try Again' resets the page content to the pre-error state.

*note: this page UI is a little exceptional and not typical, because the real user interaction happens out-of-bound and the UI simply serves as the message/status. For most cases, when the error is global/page level, it works well keeping the error message box at the top of the page.

**Comment by mixonic** [comment]
@jenn-rhim I'd really like a fresh pass at the mocks if you can do that for me.

For example the errors in U2F registration (https://github.com/brave-intl/publishers/issues/394) are local but the errors in U2F authentication (https://github.com/brave-intl/publishers/issues/393, this issue) are global. That doesn't seem ideal.

I think If I just changed the text in your design to "Not authenticated." it would look pretty weird. You can iterate more quickly on what that looks like and approve something working with your design tools, so a fresh mock would be a good way to communicate the change to me.

**Comment by mixonic** [comment]
Instead of fresh mocks for the above @jenn-rhim suggested I wing it. I'll open a PR to close this off shortly!
