### ISSUE TITLE
2FA U2F set up

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#394]
![4-securitykeysetup1](https://user-images.githubusercontent.com/4369856/33984166-825f1df8-e06b-11e7-81a9-4cde18c2686f.png)

![5-securitykeysetup2](https://user-images.githubusercontent.com/4369856/33984175-89121e52-e06b-11e7-91fd-c9a945bacfef.png)

![10-securitykey-setup-error1](https://user-images.githubusercontent.com/4369856/33984189-931ae85c-e06b-11e7-9e27-614150f51780.png)

![11-securitykey-setup-error2](https://user-images.githubusercontent.com/4369856/33984191-9712e23e-e06b-11e7-82d8-5e40a8f5cb25.png)

**Remove Security Key: when TOTP is still in effect** 
![18-2fa-removekey-1](https://user-images.githubusercontent.com/4369856/34025851-182cabc0-e107-11e7-8ce5-39f905d706c9.png)

**Remove Security Key: no TOTP**
![19-2fa-removekey-2](https://user-images.githubusercontent.com/4369856/34025876-34481e48-e107-11e7-86cc-b2815abaf5a5.png)

**Comment by mixonic** [comment]
The removal warnings are completed. The only remaining work here is the icons and style of notices/warnings during registration.

**Comment by mixonic** [comment]
I'd like to reconcile how errors are presented here with https://github.com/brave-intl/publishers/issues/411
