### ISSUE TITLE
2FA TOTP UI

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#395]
still to come 
- disable TOTP
- reconfigure TOTP
- errors

![2-authenticator-setup](https://user-images.githubusercontent.com/4369856/33984226-b8bf3270-e06b-11e7-97ce-cfc2d171ba9a.png)

**Reconfig**
![15-2fa-authreconfig](https://user-images.githubusercontent.com/4369856/34025769-a4cf04ac-e106-11e7-9399-9c09688e5123.png)

**Disable TOTP: when security key setup still in effect for 2FA**
![16-2fa-auth-disable-1](https://user-images.githubusercontent.com/4369856/34025818-e9f0860a-e106-11e7-94d1-ed89b9b113e9.png)

**Disable TOTP: when no other 2FA is set up after disabling TOTP**
![17-2fa-auth-disable-2](https://user-images.githubusercontent.com/4369856/34025821-ee058ace-e106-11e7-9926-bf53e057168e.png)

**Comment by mixonic** [comment]
The only remaining work here is to change how errors on this page are currently displayed.

Currently, they use the same "flash" message style used across other pages. This is basically a universal feature of the current site. I think it is an open question as to if the flash message style demonstrated here should be a) only for this page or b) the new universal flash style.

I'd suggest we just make it opt-in at a development level, although if we know it will be universal we can make some implementation decisions around that knowledge.

Regardless we do not think this is a P1 blocker for 2FA to go live. It should probably be related to a redesign effort.
