### ISSUE TITLE
Blank page when Checking for HTTPS

### ISSUE THREAD

**Issue by jonathansampson** [brave-intl/publishers#397]
Domain: https://jonathansampson.github.io/

I logged in via the email link...

![01](https://user-images.githubusercontent.com/815158/33995590-0652ed64-e0a4-11e7-8d5a-ad1cb3b834f0.PNG)

I clicked _I'll use a trusted file_...

![02](https://user-images.githubusercontent.com/815158/33995616-196244ea-e0a4-11e7-89a9-193564aa7fbf.PNG)

I clicked _Check for HTTPS_...

![03](https://user-images.githubusercontent.com/815158/33995632-26a11cee-e0a4-11e7-8d8e-27cdab0e92f6.PNG)

**Comment by dgeb** [comment]
I'll investigate and fix this.
