### ISSUE TITLE
Remove Opt-in step from verification: applies to all pubs

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#403]
**Background:**  the current opt-in has a problem of trying to get combined agreements from the users on 1) being listed on our Brave Verified Publishers list and on 2) being ok to be used in our marketing effort (effectively co-marketing) in one button.  3) We also need to get TOS agreement, which has been missing.

The result of the discussion came down to the following decisions:
1.  By signing up Brave Payments, the publisher is automatically in our Brave Verified Publishers list.
2. Channels they verify will automatically get the 'Verified' badge that will be shown in the browser Payments table.
--> '# 1 and # 2' mean that we don't need the user's opt-in.

3. We do need the user's consent on their logos/names potentially being used on our properties (websites, social media, and any promos/campaigns). --> this applies to the publisher level, not individual channel level. 

## This means **the changes in Pub sign-up & verification flow**.
**1. During the sign-up**: when the user made the round trip from the email link, we present them one more screen to complete registration.  The screen will ask their name, phone # (optional), and the opt-in checkboxes. This will be the full screen mode, not pop-up.

**2. We no longer need the opt-in step** at the end of channel verification (for any channel), which simplifies the flow.

(screens to come soon: legal input/review required)

**Comment by ayumi** [comment]
Implemented in #491
