### ISSUE TITLE
replace deprecated request package

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#4054]
https://nodesource.com/blog/express-going-into-maintenance-mode/ - request is deprecated and has an SSRF that is failing dependabot for this repo. look into replacing it with axios or got.

**Comment by diracdeltas** [comment]
@tsmartt your PR doesn't fix the issue because the latest version of Request is still vulnerable: https://github.com/brave-intl/publishers/security/dependabot/139. the package is deprecated so it will need replacement to properly solve this.

**Comment by thypon** [comment]
The attached PR should fix the issue
