### ISSUE TITLE
Add explanation for why we need to access a youtube publisher's Google account

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#409]
We have had many errors corresponding to when a user clicks "Cancel" on this screen:
![image](https://user-images.githubusercontent.com/12549658/34005635-8bf41d56-e0c9-11e7-9d00-bfb75e1e29e3.png)

The original error that was reporting this has been patched in #406, but it raises the question, why have [~200 people](https://sentry.io/brave-software/publishers-production-t2/?query=is%3Aunresolved+new_session&statsPeriod=14d) clicked "Cancel"?

I suspect it's because we do not give any reason to why we need access to their their google account, scaring off privacy concerned publishers.  A user in the [r/BATProject reddit](https://www.reddit.com/r/BATProject/comments/7dfa22/youtube_demonetization_batbrave_awareness/) said this:
> FYI I was going to sign up to Brave Payments, then you asked me to sign into my Google account with clear no explanation (on that page). You may want to clarify to people why you are wanting access to their Google account. I cancel until I could learn more info

We should add more specific instructions in two places, the choose verification page, and the oauth dialog that google brings up (pictured above).

**Comment by jenn-rhim** [comment]
@nvonpentz most oauth permission screens sound scary, not just ours. :)  and some requesters actually do ask more data than necessary (not cool). we're not doing that. 

i believe we do have control over some of the info on this screen even though the screen is generated by google auth team:
1. who's making the api call: Publishers Dev (localhost)
2. the oauth scope: channel/account name, avatar, etc. 
when we submit the request. 

- can we find out if there's a different way that the scope can be presented to the user than the creepy sounding ('view your yt account')? OR find out if there's a different way to get all we need ^^ which can be spelled out to the user?  

- can we also find out if we can put a condition to this: i.e. **channel/account that is currently active**?

If we do this, i think we'll be in a better shape that we don't need extra explanation in other screens.

**Comment by nvonpentz** [comment]
@jenn-rhim Google recently changed what is allowed to be shown on the consent screen.  They [made it stricter](https://stackoverflow.com/questions/44138213/google-oauth-consent-screen-not-showing-app-logo-and-name) in order to increase security and prevent phishing attacks.  You can no longer display the app name or logo.  Instead the url will be shown, basicattentiontoken.org (this is not the case for development,  but this is true for production).

We can [apply](https://support.google.com/code/contact/oauth_app_verification) to get the app name displayed.  But I don't think this will really solve our problems.

The scopes that are presented to the user are named by Google, we do not have control over this.  I'm not sure what you had in mind for a 'different way to get all we need which can be spelled out to the user', but I don't think there are other options.  Since Google is the one authorizing, we must conform to their system.

As far as adding a condition to only allow channels that are currently active, there is a property of the google account `status.isLinked` that is `true` if there is a linked youtube channel, but I don't think there is a way to filter the consent screen by this property.  Maybe @ayumi has an idea about this.

If my assumptions are correct, then it looks like we must provide clarity before they reach the consent screen.  This is how it looks right now, after we pushed a temporary fix in #410 ![image](https://user-images.githubusercontent.com/12549658/34132963-5805749a-e420-11e7-8d10-5f925d002856.png)

Ayumi suggested that their be some more padding at the bottom, what do you think Jenn?  When I made the fix, I tried to do it in such way that preserved the two boxes being the same size, but this might not be a priority.

**Comment by jenn-rhim** [comment]
my recommendation is to display this info **in the next screen** if it's not too much more work.
because:
- high likelihood that this still won't get read
- this short term fix will need to be changed to a more scalable one to go along with the multi-channel support very soon
- we can set the expectation much better in wording with the user's full attention

for the permission screen, i've chatted with @nvonpentz and it does look like we have a limited control, or no granular scope that we can specifically request.  i hope still submit the name of the 3rd party (us) in the way that our user can recognize, **Brave Payment**s, so that it doesn't throw them off.

-- a screen to come...

**Comment by jenn-rhim** [comment]
Here is the UI and UX:

**1. User selects YT**
![1-pub-type](https://user-images.githubusercontent.com/4369856/34237404-6392f160-e5b1-11e7-8390-92703c84b417.png)

**2. Informed about what's about to happen next**
![2-yt-oauthwarning](https://user-images.githubusercontent.com/4369856/34237439-8f121230-e5b1-11e7-89cb-9feb7a05ad11.png)


**3. G-auth**

![3-gauth-1](https://user-images.githubusercontent.com/4369856/34237443-933f458a-e5b1-11e7-9954-b02d7b88e345.png)

**4. G-auth**

![4-gauth-2](https://user-images.githubusercontent.com/4369856/34237451-9e1ac402-e5b1-11e7-9c9f-22205eb0ca2d.png)

**5. G-auth**

![5-gauth-permission](https://user-images.githubusercontent.com/4369856/34237458-a1c6dfd2-e5b1-11e7-9016-b75ad50a0c07.png)

**Comment by mixonic** [comment]
I'll take this, but I'll open a PR after https://github.com/brave-intl/publishers/pull/452 lands since it touches some of the same flow.

**Comment by nvonpentz** [comment]
@jenn-rhim After the twitch update, we changed one of the earlier screens.  Before I implement this, can you check and make sure that this is still the flow you want

1. User Selects youtube
![image](https://user-images.githubusercontent.com/12549658/37525108-39ce2004-2902-11e8-85e6-9b7bb35baca6.png)
2. Informed about what's about to happen
![image](https://user-images.githubusercontent.com/12549658/37525141-592c8bf2-2902-11e8-911b-dcbec280d9c9.png)
3. G-Auth screens

**Comment by yachtcaptain23** [comment]
Confirmed with @nvonpentz that this issue is stale. Closing. We'll re-open if we see publishers bringing up questions about why we need to OAuth.
