### ISSUE TITLE
2FA trap/promo at sign up

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#411]
In order to make 2FA discovery and enabling easy, insert this step just before the user lands on the dashboard (right after the opt-out screen).

- it takes the user directly to the 2FA home page
- allows user to skip enabling

![2fa-trap](https://user-images.githubusercontent.com/4369856/34149523-3a407420-e45a-11e7-8771-0f3f3f42ea59.png)

**Comment by ayumi** [comment]
people might get annoyed that there are 2 "popups" to dismiss.. but it might become okay when we have owners/multi-property working since the extra security will be extra appreciated.

**Comment by jenn-rhim** [comment]
Yes, agreed. Luckily the user has to go through them only once. And 2FA step is a courtesy step to help the discovery of the feature, and it’s the right time to be alerted if they’d ever want to turn it on. Get it out of the way and don’t need to go back there much. 

this is for better UX but of course we can determine when is the appropriate time to roll it out based on the feature maturity.

**Comment by kpfefferle** [comment]
@ayumi This was completed in #457, but I don't think it auto-closed as that PR was merged to `staging2`. It can be closed now.
