### ISSUE TITLE
2FA Contextual Help

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#412]
*note: we may potentially need to create a Pub specific help section on the site in the future. till then, we'll handle extra sideline content in the form of contextual help flyout.
**any suggestions on the wording are welcome.

**current browser support limitation**
![2fa-overlay-browserw](https://user-images.githubusercontent.com/4369856/34149789-161d0fbc-e45b-11e7-9f06-abb8b219ca21.png)

**supported/tested u2f keys**
![2fa-overlay-supportedkeys](https://user-images.githubusercontent.com/4369856/34149818-2de99674-e45b-11e7-9c7c-04969cd8934e.png)

**Comment by ayumi** [comment]
works with my Yubikey 4

our list of many devices will be compiled Soon.

**Comment by mixonic** [comment]
FWIW I've also confirmed that the Ledger Blue https://www.ledgerwallet.com/products/ledger-blue works.

**Comment by mixonic** [comment]
The popups here seem to overlap with https://github.com/brave-intl/publishers/issues/419, which is a P1.

@kpfefferle and I suggest simply making this issue a P1. The alternative is we ignore the popup parts of #419.
