### ISSUE TITLE
Multi-channel support: allow user to resume verification process

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#413]
Once the verification key has been handed out to the user at the 3rd step, we keep the channel record along with the key and expose the incomplete channel on the dashboard for the user to re-enter the process.

this is because:
1. the session can time out while the user is completing the out-of-bound steps
2. we need a mechanism of revoking the key (though not guaranteed), so that they can clean restart. 

*channel record should be discarded if the process is abandoned prior to the key distribution: i.e. first 2 steps as they are very simple to restore.
**warning screen when the user removes incomplete channel (ask them to delete the key file)

![dashboard-incompletech](https://user-images.githubusercontent.com/4369856/34150530-6b2c0f10-e45d-11e7-85a9-6819e96f54ab.png)

**Comment by ayumi** [comment]
#473 implemented resume of channel verification.

Option for users to remove resumable channels is To be Implemented.

**Comment by dgeb** [comment]
@ayumi I believe this can closed via #501
