### ISSUE TITLE
2FA Warn users after setting up U2F

### ISSUE THREAD

**Issue by mixonic** [brave-intl/publishers#414]
After a user registers a U2F device they should be warned that registering a TOTP device as a fallback is strongly recommended.

**Comment by jenn-rhim** [comment]
i've covered this in https://github.com/brave-intl/publishers/issues/419, which captures the breath of the 2FA home states and content. 

I'd like to use this ticket to zoom in on the implementation of the warning. 
- it would be really nice if we can apply some dynamic css element to the message box appearing under TOTP section when the user is returning from the dialog. some sort of reveal transition. suggestions are welcome!  :)

related screens:
1. when the user set up the security key first and only:
![2fa-home-a0k1](https://user-images.githubusercontent.com/4369856/34187196-067e09aa-e4e5-11e7-83c6-29017f0405ae.png)


2. when the user removes TOTP, which leaves the U2F as the only 2FA.
![2fa-disableauthapp-1](https://user-images.githubusercontent.com/4369856/34187231-33871702-e4e5-11e7-94bd-7e6b3d771f32.png)

**Comment by mixonic** [comment]
This was addressed:

* The prompt to add TOTP if you only have U2F: https://github.com/brave-intl/publishers/pull/428
* The modal for confirming removal of any device (TOTP or U2F)L https://github.com/brave-intl/publishers/pull/424

This issue can be closed IMO. Please re-open if I am mistaken!
