### ISSUE TITLE
2FA Home: content & various states

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#419]
I had to make minor updates on the content in Hardware security keys section to make the 'browser limitation' blurb more noticeable.  -- this is to prevent user frustration if they discover it after the fact.  

- reference mocks below indicating different states of 2FA main page + the contextual help

--------------------------

## Two-factor Authentication

Two-factor authentication (2FA) is a method of confirming your identity by using two different forms of verification when you access Brave Payments in order to increase security (Recommended for protecting your account).

**App on your phone**
Use an app on your phone to get an authentication code. You will be asked to type in this code when logging in. 

**Hardware security keys**
Security key is a small device that connects to your computer via a USB port and works with FIDO Universal 2nd Factor (U2F). You will be asked to insert and press the key instead of typing in a code. Currently, security key is supported by Google Chrome and Opera. 
*A list of security keys that have been tested

--
**Limited Browser Support** contextual help flyout
This means you will need to update to the latest Google Chrome or Opera in order to set up and log in using security keys. More browsers will start supporting the security key in the near future. We will inform you on the changes.

--
**Tested Security Keys** contextual help flyout
The following products have been tested and proven to work with our system. 
- YubiKey
- Ledger Blue
- Product 3
- Product 4
- Product 5
--------------------------

**1. 2FA Disabled**
![2fa-home-a0k0](https://user-images.githubusercontent.com/4369856/34271774-a0321cae-e642-11e7-8900-82e700ae4663.png)

2. TOTP Enabled; U2F disabled
![2fa-home-a1k0](https://user-images.githubusercontent.com/4369856/34186816-d334cc3e-e4e2-11e7-88a8-a5a8d2d95258.png)

3. TOTP disabled; U2F enabled
![2fa-home-a0k1](https://user-images.githubusercontent.com/4369856/34186810-cdc3cc28-e4e2-11e7-9bfd-ce662be2bbd7.png)

4. Both enabled
![2fa-home-a1k1](https://user-images.githubusercontent.com/4369856/34186821-d7d3a076-e4e2-11e7-8af9-ff7e5c0caa41.png)

5. Contextual help for the supported browser
![2fa-overlay-browser](https://user-images.githubusercontent.com/4369856/34186827-dcf399bc-e4e2-11e7-988f-479dafe1f94b.png)

6. Contextual help for the supported key list
![2fa-overlay-supportedkeys](https://user-images.githubusercontent.com/4369856/34186829-e203b9fa-e4e2-11e7-98a7-65d15097dccf.png)

**Comment by jenn-rhim** [comment]
Fixed the mockup that didn't reflect the copy change above ^^ for **1. 2FA Disabled**

![2fa-home-a0k0](https://user-images.githubusercontent.com/4369856/34271774-a0321cae-e642-11e7-8900-82e700ae4663.png)

**Comment by mixonic** [comment]
Reviewing this with @kpfefferle we believe the only remaining work to close this out is:

* Icons need to be added to the dashboard page per these mocks (we use them elsewhere, but have not added them here). This should also consider mobile responsiveness IMO.
* The popups for browser support and U2F device support have not been added.
* Some minor style tweaks can probably been made, however we would like the button colors, fonts etc to be part of a different ticket. This is in alignment with conversations between myself and @jenn-rhim I believe.
