### ISSUE TITLE
Make it easy to dismiss the Confirm Modal

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#426]
#424 added a new spiffy reusable Confirm Modal which is awesome!

It's a slight amount of effort to click the X to dismiss. I think we could enhance it by also allowing users to dismiss it by clicking outside in the gray or by hitting the Escape key.

**Comment by jenn-rhim** [comment]
Dismissing the dialog by clicking outside of the dialog has to be for the non-modal dialogs. In general, delete confirmations are modal and should not be dismissed until user chooses provided actions on the dialog.

**Comment by ayumi** [comment]
@jenn-rhim thanks for the comment -- I can understand where you're coming from. My personal style is to be modal averse as they can feel abrupt when overdone, but as long as we minimize them to where it's necessary then I'm okay with them.

**Comment by jenn-rhim** [comment]
Yep. Totally in agreement. In fact, I was going to stipulate that easy dismissal of any sort of overlays somewhere when we build our UI library. 

It’s just that when the user calls for ‘delete’ or ‘disable’ of things and clicks outside to bypass the answer, what should we consider that as? I think we are on the same page. ;)
