### ISSUE TITLE
[WIP] Email - Publisher winback email

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#431]
Conditions :
 A publisher has started the verification process for their domain before the site update, but has not completed after 5 days.

Frequency :
Once

Subject :
Come back to finish verifying <_user verified domain_>

Body :

Paragraph :
Welcome back! Just a few more steps until your funds are unlocked.

We've made the process easier with some new verification methods. Thousands of publishers have signed up and we’d like you to join too!

By just taking a few more steps to verify <_publisher domain_>, you’ll start receiving funds from your audience.

Please visit https://publishers.basicattentiontoken.org/ to continue the verification process. 

Call to Action : 
Verify My Domain

Post-Script :
Got questions? Need help? Let us know how we can help!
publishers@basicattentiontoken.org

Didn’t sign up for this or feel like this email was sent to you by mistake?
Feel free to cancel the verification process by Unsubscribing

**Comment by jenn-rhim** [comment]
@alexwykoff the frequency needs to be set until the user completes or request that they no longer want to receive the notification. Once is not good enough.

**Comment by alexwykoff** [comment]
The scenario in this case is for folks who tried the DNS-only version of the site we had. 

We have other emails pending to cover incremental nudges for newer users, so droning the same message in a winback scenario wouldn't be quite effective. 

If this initial winback doesn't work, then it would certainly be sensible to design different winback campaigns in the future.

**Comment by jenn-rhim** [comment]
Do those other cases of nudging targeted at the same users? 

These are people who dropped out of the verification. From a conversion funnel standpoint, they are the closest to winback, higher probability than people who haven’t gotten to this point. Also, we can’t guarantee that they opened the email. 

I’d consider setting a few more emails with a potentially increasing intervals. It’s a very common email strategy.

**Comment by alexwykoff** [comment]
The other cases are for folks who have started verification but paused in a shorter interval. They should be more contextually relevant to where they were in the process (wordpress vs DNS vs .well-known txt for instance) and thus have a better chance at conversion.  

The interval for those can and should be higher as you rightly noted.

**Comment by nvonpentz** [comment]
Blocked until #623 is implemented

**Comment by nvonpentz** [comment]
stale
