### ISSUE TITLE
babel update

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/publishers#4425]
babel-traverse needs to be updated to a maintained package, @babel/traverse. https://github.com/brave-intl/publishers/security/dependabot/197

**Comment by diracdeltas** [comment]
@jlbyrne was this perhaps fixed by https://github.com/brave-intl/publishers/pull/4431 ?

**Comment by jlbyrne** [comment]
Yes, it was.  Looks like I linked to the wrong issue.  I updated the PR description to link this one.
