### ISSUE TITLE
"Can't find domain" on login when domain is verified but email is incorrect

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#444]
If you have a verified domain and supply an _incorrect_ email address in the login page, the app reports "Couldn't find a publisher with that domain name", and no login email is sent.  This message is incorrect, as there is a publisher with that domain name, just not that domain * email combination.  We don't want to tell users we don't have record of their domain after they have verified it.

![image](https://user-images.githubusercontent.com/12549658/34611673-73b37a0c-f1f4-11e7-91ba-42427b47f5f5.png)
verified domain: nickvonpentz.com
correct email: default@default.org

We should change message to reflect as much accurate information as possible.  "Incorrect email for domain" or something similar.

We could theoretically just send the email anyway to the correct email address, but I don't think that would be good UX since they are expecting it to go to the one they supplied.  I imagine we don't want to inform the user which email address is the correct one for the domain either, so stopping execution here seems to be the best approach.

**Comment by ayumi** [comment]
mm good UX question! one idea is to redesign the form slightly to make it easier for verified domains

Website Domain
`[ example.com ]`
`< Primary Button: Email me a link to log in >`

Email (for unverified domains)
`[ alice@example.com ]`
`< Secondary button: Resume verification >`

cc @jenn-rhim

**Comment by nvonpentz** [comment]
No longer relevant as all publishers use email address to login.

Related to #274
