### ISSUE TITLE
Publishers from New York are unable to receive donations in the form of crypto

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#463]
Because of they do not have a [Bitlicense](https://en.wikipedia.org/wiki/BitLicense), Uphold will not allow residents of New York State to deposit or receive crypto on their platform.  As a result, we are only able to pay out publishers from NY in fiat.

Until Uphold gets a bitlicense, we can't do much about this, though we might want to add an explanatory note to the dashboard or elsewhere on basicattentiontoken.org.

![image](https://user-images.githubusercontent.com/12549658/34795753-538c1898-f621-11e7-81b0-5ff0fcafc5e7.png)

**Comment by corymcdonald** [comment]
Closing this - we get the available currency list from Uphold. They should return the available currencies for that specified region. In addition Uphold is very close to getting their Bitlicense 🎉
