### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by mixonic** [brave-intl/publishers#465]
We will migrate the site off Bootstrap 3 and onto Bootstrap 4 (beta.3, currently). Bootstrap 4 has better customization options for its typographic and layout grids.

Our workflow will be to first migrate the main dashboard page. This will be PR'd and can be landed in staging. Then we will incrementally convert the rest of the dashboard pages. The theory is that having completed the most complex page first, other subsequent pages will be simple.

This does mean that staging, and potentially production, will have a period where pages may be slightly inconsistent. For example the navigation in the top bar will be implemented in v4 on some pages and in v3 on others making it slightly different. This would be temporary however.

This effort will additionally:

* Change bootstrap 4 to be consumed via npm instead of via a Ruby gem.
* Introduce new breakpoints at more reasonable and modern sizes.
* Add mobile responsiveness to pages as we migrate them.
* Introduce a new typographic and layout grid.

This effort will *not*:

* Change the dashboard background image. This would be too jarring going between 3 and 4 during the transition.
* Change button colors.

**Comment by ayumi** [comment]
sgtm!

just a note to consider the eventual merge resolution between this and `staging2` / #452 Multi-chan

**Comment by ayumi** [comment]
closing as the foundations of this work have been implemented with #490 

further steps to transition off of bootstrap 3 will be tracked with https://github.com/brave-intl/publishers/labels/epic%20%2F%20Style%20refactor
