### ISSUE TITLE
A way to create referral promo, channel-specific codes

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#466]
(Please base this off of #452 (`lgebhardt:multichannel`) / or `staging2` once it's merged)

We'd like to ask Publishers to refer users to download and use Brave. This will be attributed via a special, channel-specific download link the Publishers share with their audience. This special link contains a unique code generated when Publishers opt into the referral program.

## High level spec:
- Publishers (owners) land on the promo page which explains things and has an Activate button.
- Owners press the button and they are taken to a page with codes for each other channel (URLs eventually -- let's leave it as codes for the scope of this issue).
- When owners return to the promo page they'll see the codes.

## Publishers data model changes:
Persisted state:
- Owner's opt into the promo -- one time per Owner.
  - Owner `#promo_enabled_2018q1`
- Per-channel referral codes -- one per Channel, stored right after we create them via the Promo API
  - Channel has_one ChannelPromoDetails (could be has_many in the future)
  - ChannelPromoDetail
    - #channel_id
    - #promo_id -- all of them `2018q1` or whatever promo ID we decide on (configurable / TBD)
    - #referral_code -- via Promo API

## Publishers and Promo API interactions:
```js
// Publishers -- Promo API communication

// "promo": a string referring to the promo. (e.g. "free-bats-2018q1")
// Promo API generates promos out of band.
// Publishers is configured with the promo code.

// Publishers creates a channel-specific referral code
POST {promo-api}/api/1/promo/publishers/
{
  "promo": "free-bats-2018q1",
  "channelId": "youtube#channel:#{youtube_channel_id}" // or for websites "example.com". "channelId" matches API access between Publishers -> Eyeshade.,
  "channelName": "Bats are cool"
}

// Response
{
  "referralCode": "BATS-732" // random unique code. suggested to be {first 4 of channelName}{random number 0-999}
}

GET {promo-api}/api/1/promo/publishers/{channelId}
// Response
[
  {
    "promo": "free-bats-2018q1",
    "referralCode": "BATS-732",
  },
  // ...
]

// Orthogonal to Publishers:
// When people visit the Download Brave referral, they will see the associated Channel name via the Promo API:
GET {promo-api}/api/1/promo/referralCodes/{referralCode}
//Response
{ "channelName": "Bats are cool" }
```

**Comment by nvonpentz** [comment]
Implemented by #489
