### ISSUE TITLE
Owners should receive an email that lets them opt into referral promo

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#467]
Depends on #466 

Owners will receive 1 email notifying them of the Referral promo (#466).
This email contains a private link which authorizes them to visit the active promo pages only.
They will be able to activate the promo. If they're already activated they see their channels and the referral codes and URLs.

The private link works only while the promo is active.
The link does not authorize them to interact with any other aspect of the Owner account.

To implement the link, we can add a promo_2018q1_token to Owners, and generate random tokens for every owner.

**Comment by nvonpentz** [comment]
Implemented by #489
