### ISSUE TITLE
[WIP] Email - Uphold preferred currency

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#468]
Conditions :
A publisher is verified and has an uphold account but they have not designated a preferred currency in uphold.

Frequency :
Once

Subject :
Please choose a currency for <property>

Body :

Paragraph :
Thanks for verifying! 

You have one quick choice to make. You're preferred currency! 

Don't worry, you're still being paid in BAT, but this will just make it easier for you to see the value in a currency you are familiar with.
Please visit https://publishers.basicattentiontoken.org/ to set a preferred currency.

Call to Action :
Choose a Currency

Post-Script :
Got questions? Need help? Let us know how we can help!
publishers@basicattentiontoken.org

Didn’t sign up for this or feel like this email was sent to you by mistake?
Feel free to cancel the verification process by Unsubscribing

**Comment by nvonpentz** [comment]
This email will be sent out if a publisher has an Uphold account but does not have any cards, thus there is no default currency set on publishers.  Uphold accounts come with 4 cards upon account creation (3 for NY residents, no BTC), so something must have gone wrong for them, or they deleted the cards at some point.

> Don't worry, you're still being paid in BAT, but this will just make it easier for you to see the value in a currency you are familiar with.

I don't think this is correct.  When they create a card, it will become their default deposit currency.  If they create multiple cards, they will have to select their preferred currency on the publishers dashboard.

> Please choose a currency for

@alexwykoff Did you mean "Please choose a currency for Uphold.com"?  We might also consider "Please choose your deposit currency" or something similar.

Refs #462 
cc @mrose17

**Comment by ayumi** [comment]
It sounds like the email body is substantially different than this issue, so I created #479 to track the notification endpoint and email.
