### ISSUE TITLE
Owners, after opting into Referral promo, should receive an email confirmation

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#469]
Depends on #466 

After owners opt into the Referral promo, they should receive an email listing the referral URLs for each of their channels. This will give owners an easy way to reference the URLs.

**Comment by alexwykoff** [comment]
Is there a unique URL / referral code per each publisher? If so, we should be certain to include it in the email.

**Comment by ayumi** [comment]
@alexwykoff 1 code per channel; so for someone with 3 YouTube channels this email would include 3 referral URLs.

**Comment by nvonpentz** [comment]
Implemented by #489
