### ISSUE TITLE
Cleanup abandoned site Channels where a verification method was not selected

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#476]
There's a case where an Owner adds a Channel, specifies the domain name then stops before choosing a verification method. If you now leave Publishers and return, you can't resume verifying that Channel. However the Channel record still exists. Over time there there might be many such abandoned Channels.

Let's add a rake task which checks for abandoned channels (currently just site Channels whose verification_method is nil) and destroys them. We can run it once a day.

**Comment by lgebhardt** [comment]
Would this be better as a background job like CleanStaleUpholdDataJob? That way it's not a chore to run.

**Comment by ayumi** [comment]
yes, that would be good
