### ISSUE TITLE
Migrate Publishers and YoutubeChannels to Owners, Channels and ChannelDetails

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#477]
Currently we have Publishers and YoutubeChannels, and we'd like to migrate them to the new model: Owners with multiple Channels.

Publishers -> Owner + (Channel / Site + details)
YoutubeChannels -> Channel / Youtube + details

In multi-chan, email is now a unique key on Owner.
Previously a logical person who owned many websites might many Publisher records, each with the same email.
In that case we should merge all Publisher records sharing the same email, creating a single Owner record and assigning itall the corresponding Site and Youtube channels.

This would probably be a rake task. It would be good to be tested, and a bonus if we had Dry Run mode. We should also take a backup of the database before migrating.

Related to #273 and #452

**Comment by nvonpentz** [comment]
Can I expect this will be completed before the referral promo goes into QA on Friday, January 19th?

For the referral promo, we need at add a column `Owner#promo_enabled_2018q1` (described #466), which is blocked by this.

**Comment by dgeb** [comment]
@ayumi I think this can be closed.
