### ISSUE TITLE
For zoomed viewports: Login TOTP entry textbox looks funny

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#486]
In Brave, Zoom 125%

![publishers-totp-login-funny-20180116](https://user-images.githubusercontent.com/521861/35016950-b764cc52-fb12-11e7-9356-ed265ded60c6.png)

cc @nvonpentz who noted this earlier. I started using 125% zoom by default so I see it now.

**Comment by nvonpentz** [comment]
This is no longer reproducible
