### ISSUE TITLE
Add twitter and facebook share buttons for publisher referral links

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#498]
Providing an easy way for a publisher to tweet/share their referral links could increase the reach of the referral promo, so we should consider adding these buttons, one for each of the referral links provided to the publisher.

Twitter - [dev.twitter.com/web/tweet-button](https://dev.twitter.com/web/tweet-button)

These buttons may require us to include third party javascripts which has security implications.  We should find out whether it is possible without javascript.  If not, we need to decide it if it worth it.

cc @jenn-rhim @ayumi

**Comment by nvonpentz** [comment]
@ayumi @jenn-rhim We could do something like this without third party js: https://sharingbuttons.io/.

### Twitter
We can pre-populate a tweet (we can customize for each user), and the user can tweet it out. 

ex. [Share on Twitter](https://twitter.com/intent/tweet/?text=Contribute%20to%20my%20youtube%20channel%20by%20downloading%20brave!&url=http%3A%2F%2Fpublishers.basicattentiontoken.org)

### Facebook
We cannot pre-populate the message like with Twitter, but we do have control over the open graph meta tags which determines what the image, title, and description of the link will look like. 

ex. [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fpublishers.basicattentiontoken.org).  

Regardless of whether we include the Facebook share buttons for the referral promo, I think we should add an image the open graph meta tags for publishers.basicattentiontoken.org, so it is more inviting to click when shared.  Brave.com has the image of the lion, for example:

[Share Brave.com on Facebook!](https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fbrave.com)

[Open Graph Protocol](http://ogp.me/)

I will use this method for the Twitter buttons first, then consider we can Facebook.

**Comment by ayumi** [comment]
+1 Twitter share buttons with "intent" links

**Comment by nvonpentz** [comment]
Implemented by #489
