### ISSUE TITLE
Multi-channel migration verification checklist

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#500]
A checklist to help us verify the PR #494 which implements issue #477.

- Publisher, website verified, Uphold connected
- Publisher, YouTube connected, Uphold connected
- Publisher, website verified, no Uphold
- Publisher, YouTube connected, no Uphold
- Publisher, website verified, TOTP enabled

### merging

- 2 Publishers, same emails, websites verified, Upholds connected
- 2 Publishers, same emails, YouTubes verified, Upholds connected
- 2 Publishers, same emails, 1 website 1 YouTube, Upholds connected

To address Uphold being set to only 1 of the legacy publishers, it might be important to implment https://github.com/brave-intl/publishers/issues/133. so the user can see the attached uphold, detach and reattach it.

**Comment by dgeb** [comment]
@ayumi I think this can be closed.
