### ISSUE TITLE
Erroneous error message instructing users to verify a channel at attempting to login

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#507]
Verification process is now subordinated to the account so we should not see this message at login.

![screen shot 2018-01-22 at 3 38 11 pm](https://user-images.githubusercontent.com/4369856/35250261-8bf0ef5c-ff8a-11e7-83e9-e1a87f2af687.png)

**Comment by mixonic** [comment]
@jenn-rhim can this be closed in favor of https://github.com/brave-intl/publishers/issues/508 ?
