### ISSUE TITLE
Add the 2fa confirmation screen instead of the set up screen for smooth transition.

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#509]
@mixonic 

For the first time 2fa setup, user will be doing this as part of the sign up process, not by going to the Account page. 

The attached screen seems more appropriate and also provides clear direction to the dashboard. If it's easier, a full page rather than an overlay is fine by me as long as 'Close' button takes the user to the dashboard. 

- Current screen
![screen shot 2018-01-22 at 3 52 31 pm](https://user-images.githubusercontent.com/4369856/35251506-546b549a-ff90-11e7-9e23-0a433fac1c61.png)

- Proposing content change
![2fa-confirm](https://user-images.githubusercontent.com/4369856/35251524-6627021a-ff90-11e7-8f2b-47b44a5d98bc.png)

**Comment by mixonic** [comment]
@jenn-rhim this is only for first-time setups, correct?

**Comment by jenn-rhim** [comment]
@mixonic yep, correct.  the user would feel lost as to what to do next given that they just signed up.

**Comment by mixonic** [comment]
For reference the initial implementation of this feature was in https://github.com/brave-intl/publishers/pull/457/files
