### ISSUE TITLE
when to use 'Unavailable' vs '0' (zero) BAT Balance on Pub Dashboard

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#531]
Currently, when you have no channels added to your account, the contribution balance is indicated as 'Unavailable' very loudly (as it's taking the same font size for the > 0 balance). Although I understand why we did this, it's very disheartening to see this so big as I first signed up and got here. :) I'd like to make some distinction here:

1. I'd propose to use 'Unavailable' only when we have a problem retrieving the actual balance. 
2. Let's display '0' if their brave wallet is empty, whatever conditions there are that contribute to that balance: perhaps no channel that collects contribution, no one has contributed, just got emptied, etc. 

![screen shot 2018-01-25 at 12 34 31 pm](https://user-images.githubusercontent.com/4369856/35411504-dc9e6192-01cd-11e8-940c-34fee47e82c2.png)

@ayumi @mrose17   let me know what you think.

**Comment by ayumi** [comment]
I believe everything you've described is the case currently, and the error was transient (due to publishers and eyeshade not communicating correctly).

Currently a fresh account on staging now shows as 0 BAT.
