### ISSUE TITLE
need to define background color for the email

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#533]
background color: #EFF2F5
Current:
![screen shot 2018-01-25 at 4 02 50 pm](https://user-images.githubusercontent.com/4369856/35418802-60c8d8e2-01e9-11e8-93b2-154826cdf0cb.png)

Expected:
![image](https://user-images.githubusercontent.com/4369856/35418900-de5fb1ea-01e9-11e8-8c22-e120b8e71aa9.png)

**Comment by nvonpentz** [comment]
Upon checking the email in staging, the fix in #717 did not resolve the problem by using inline css.  We should try using the other method, wrapping the body in a table.

**Comment by corymcdonald** [comment]
Closing this issue for now due to the fact that @rossmoody has taken care of an email re-design
