### ISSUE TITLE
Channel creation in-page notification banner should not be persistent

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#535]
once finish adding the channel, user returns to the dashboard and they see the banner at the top of the page, 'channel created' -- this is fine for now (heads-up: new design pattern coming).  but it should fade out or get collapsed after a few sec (3?).  keeping it up until a page refresh makes it seem the system is not too snappy. 

![screen shot 2018-01-25 at 12 56 07 pm](https://user-images.githubusercontent.com/4369856/35419244-bdb5b0d2-01eb-11e8-8f2d-7b6434f49cab.png)

**Comment by jenn-rhim** [comment]
btw, i think it'd be consistent if we say 'Channel added' instead of 'Ch annel created'

**Comment by ayumi** [comment]
I don't think notifications should fade away, because if you tab out or look away you might miss it.

it's also not a common pattern, except in cases where you might receive many notifications simultaneously on the same view like system notifications.

**Comment by jenn-rhim** [comment]
the real confirmation / proof of the task complete is right there on the dashboard as an added channel. this alert bar is just a user friendly way of delivering/communicating the system response -- in a way redundant but i prefer having it as a pattern because it humanizes the interaction.  

with that said, i don't think it should be stale/persistent as its effectiveness is no longer good as soon as the user sees the artifact (channel added). if we were to make it persistent, we should have 'x' close button --  i prefer making it go away.

**Comment by yachtcaptain23** [comment]
I agree with Jenn.

**Comment by tsmartt** [comment]
Closing as stale.
