### ISSUE TITLE
in-page notification/alert message needs to be event specific

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#536]
someone 'channel created' message is stuck, being displayed at the wrong time. see below the screenshot after removing a channel. should be 'Channel removed.' 

![screen shot 2018-01-25 at 4 34 03 pm](https://user-images.githubusercontent.com/4369856/35419774-cef21a90-01ee-11e8-9f96-5c04a4efbd4f.png)

**Comment by ayumi** [comment]
Let's review after multi-chan to see if it changes

**Comment by nvonpentz** [comment]
@jenn-rhim @ayumi I've never experienced this; is this still happening?

**Comment by hahmed** [comment]
To reproduce:

Create a twitch account and the notification "Channel created" appears at the top.

*Do not refresh the page* 

Then click *Remove Channel* link next to the linked twitch account and the notification remains at the top of the page. 

Looks like the notification is persisting from whatever the last action, if you refresh the page - notification disappears.

**Comment by nvonpentz** [comment]
Thanks @hahmed I'm able to reproduce it now.  Would you like to take this issue?
