### ISSUE TITLE
Need the global nav on 2FA pages

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#538]
Global nav is meant to be persistent

Current 2FA pages:
![screen shot 2018-01-25 at 4 53 29 pm](https://user-images.githubusercontent.com/4369856/35420176-e771331a-01f0-11e8-8733-9d3ea40d0bd2.png)

Should be:
![image](https://user-images.githubusercontent.com/4369856/35420159-cc25326e-01f0-11e8-91fc-ac769ae62706.png)

**Comment by nvonpentz** [comment]
I think this would be best addressed when we port the dashboard to bootstrap 4

**Comment by yachtcaptain23** [comment]
Users can work around. Going to get rid of as we realistically won't ever get to this and there's a straight forward workaround for the user.
