### ISSUE TITLE
Security key feature is not shown on Chrome in 2FA

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#539]
i logged in using Chrome, expected to see Security Key option in our 2FA below authenticator app, but not there: same as I logged in using Brave. 

![image](https://user-images.githubusercontent.com/4369856/35420247-4a464098-01f1-11e8-85cd-d047f96aad53.png)

**Comment by ayumi** [comment]
this is dark launched because we didn't want to give Brave users an odd UX.

add ?u2f=1 to the URL to show it.
