### ISSUE TITLE
Uphold balance and statements

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#542]
Edited by Al Wang:

Action Items:
- [x] Add Settlements (DONE)
- [ ] See if eyeshade API's are done for charts
- [ ] Add still loading while the information is being fetched
- [ ] Render charts
- [ ] Fetch statements during the service

**Comment by ayumi** [comment]
more info needed

**Comment by ayumi** [comment]
Possibly fixed by #567

**Comment by nvonpentz** [comment]
Related to #265

@jenn-rhim What needs to be done here?

**Comment by jenn-rhim** [comment]
This one requires a bit of work (initially intended to be part of second half of Pub 2.0 design, of which we only finished Account model change + multi-channel support).

Here are the key screens involving Statements 
1. Dashboard main (I'm not proposing that we make this change for the time being)/
2. Blankslate of Statements page
3. Statements page: **This is where we need to add "**Promo**" parameter


![1-dash-2](https://user-images.githubusercontent.com/4369856/37498549-3a92e514-287c-11e8-9b42-9597507d5d49.png)

![2-statement-blankslate](https://user-images.githubusercontent.com/4369856/37498553-3f130eca-287c-11e8-94da-1ee36e7e7583.png)

![3-2statement-long](https://user-images.githubusercontent.com/4369856/37498563-435466d2-287c-11e8-8327-517927402be6.png)

**Comment by jenn-rhim** [comment]
@nvonpentz  Ideally, I’d like to see at least 3 dimensions that the user can use to filter the data records: 1. Channels (‘All’ by default), 2. Promotion, 3. Time period. Promotion has its own time period that may not coincide with the regular settlement cycle, choosing a specific promotion (e.g. February Referral Promo) would override the Time Period parameter.

Minimally, we transfer over the current time period dropdown, and allow user to generate the statement, and we include the promo results inside of that report if the time period overlaps.  
@mandar-brave

**Comment by dgeb** [comment]
@jenn-rhim @mandar-brave how would you like the "Deposit to Uphold" panel to appear when there is no Uphold wallet connected?

Currently this panel appears as:

![34235980-0e2fdd66-e5aa-11e7-8820-233a3336c43b](https://user-images.githubusercontent.com/29122/37914174-997c38da-30e4-11e8-9772-cd3767d6a0a1.png)

Also, where should the contact info / editing panel be moved? How about the marketing opt-in checkbox? Perhaps both should be moved to a new page entirely that's accessible from the user dropdown menu?

**Comment by jenn-rhim** [comment]
@dgeb  Uphold panel should look like the mockup you attached when the account is not connected. So the current implementation looks good.

We are not moving the contact info nor the marketing opt-out for the time being. It won't be until we get to 'the progress data viz' that will replace this area, which I assume will be a while. @ayumi and @nvonpentz have done some research on this as far as which JS library for data viz we might go with.

- However, we need to fix the status message under the Statement, corresponding to the Uphold connection status. See below...
![screen shot 2018-03-26 at 7 06 49 pm](https://user-images.githubusercontent.com/4369856/37942892-2be279a6-312a-11e8-9802-40b285858d7a.png)

- Here is the change in the status when the Uphold is connected and the deposits have been made.
![screen shot 2018-03-26 at 7 02 54 pm](https://user-images.githubusercontent.com/4369856/37942523-57dbdb26-3128-11e8-92b9-9e7e5c79c02a.png)

**Comment by lgebhardt** [comment]
In #377 we're allowing transfers of channels. In addition removing a channel should be accounted for in the statement functionality. We do not want to lose statements for channels that have been removed or transferred.

**Comment by yachtcaptain23** [comment]
Spoke with Mandar, showing Uphold balance is not a priority atm.

**Comment by yachtcaptain23** [comment]
Progress update on action items:

- [ ] Add still loading while the information is being fetched
- [ ] Fetch statements during the service

**Comment by yachtcaptain23** [comment]
Stale issue. Closing
