### ISSUE TITLE
'Update' button in Contact edit unstable

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#543]
As I was changing the contact info a few consecutive times to check different data type, it got hung up and not changing its state to enabled, so can't update.

![screen shot 2018-01-25 at 5 09 06 pm](https://user-images.githubusercontent.com/4369856/35420498-a6ab000c-01f2-11e8-9f03-bb5105d8c56d.png)

**Comment by dgeb** [comment]
Good catch. I can reproduce and will work on a fix.

**Comment by mixonic** [comment]
@dgeb we do this elsewhere, ala https://github.com/brave-intl/publishers/blob/staging/app/javascript/u2f/authenticationPage.js#L44-L48

I encourage you to try and add a test for the button being reset. We landed a regression of that functionality at least once.

**Comment by dgeb** [comment]
@mixonic thanks for the link! I've pushed a fix (and tests) in https://github.com/brave-intl/publishers/pull/556
