### ISSUE TITLE
Now verifying your domain...

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#550]
The "Now verifying your domain..." page:

![screen shot 2018-01-29 at 10 33 06 am](https://user-images.githubusercontent.com/29154/35518842-a9ada9a8-04e0-11e8-9376-c918aaed654e.png)

is accessed after the user selects the verify button. 
![screen shot 2018-01-29 at 10 40 27 am](https://user-images.githubusercontent.com/29154/35518911-dc5a0d38-04e0-11e8-8077-76482618356f.png)

When the "Now verifying your domain..." page is displayed a background job is running to verify the site with eyeshade. If the domain is verified eyeshade will call the publisher api, which will send an email and update the channel. However the page with the spinner will not automatically close. The page does not currently provide an obvious link to return to the dashboard (though cancel does lead there).

This page is a carry-over from single channel. I wonder if it's still relevant. If we wish to keep it, I propose we:
* remove the Cancel button, since at this point it can't cancel the verify or the channel addition
* provide a link back to the dashboard
* have this page poll the channel to see if it's verified so it automatically returns to the dashboard when verification is complete

Or we could redirect the user back to dashboard after pressing Verify. A flash message could provide the same information as the "Now verifying your domain..." page. We could then poll from the dashboard to see if verification is complete.

@jenn-rhim what are your thoughts?

**Comment by jenn-rhim** [comment]
@lgebhardt  looks great.  thanks!

**Comment by lgebhardt** [comment]
@jenn-rhim do you have an opinion on polling from the dashboard or polling from the "Now verifying your domain..." page?
