### ISSUE TITLE
Sentry handle_standard_error needs change for multichannel

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#553]
The `handle_standard_error` in lib/error_handler.rb still uses `publisher.publisher.brave_publisher_id`. Replace with publisher.email.

https://github.com/brave-intl/publishers/blob/9daf295b4ab5ca25b07f0c03a2fb0e1124346e11/lib/error_handler.rb#L25

**Comment by ayumi** [comment]
closed by #554
