### ISSUE TITLE
Changing email to email used by another account leads to error

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#558]
From the dashboard, you can attempt to change your contact email to an email associated with another account. You receive a confirmation email, however when confirming it fails and shows a blank screen (500 error).

I don't think it's urgent as you can't change email due to Publisher model validation.
However we should figure out the best flow for handling this.

**Comment by nvonpentz** [comment]
Potentially a duplicate of #664 

This has been resolved by #702
