### ISSUE TITLE
Add static maintenance pages

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#564]
## Description
The creators website needs to show a temporary maintenance page while it's being worked on. Similar to:
![inspo](https://user-images.githubusercontent.com/2388823/55661286-e4c50d00-57bf-11e9-8f20-cde8d78fad98.png)

![Screen Shot 2019-04-05 at 4 29 20 PM](https://user-images.githubusercontent.com/2388823/55661300-fad2cd80-57bf-11e9-92cb-7ae81ff577b1.png)

From Ayumi who submitted the original issue:
> To be uploaded to S3 for use with Heroku's maintenance mode.
> https://devcenter.heroku.com/articles/error-pages#customize-pages

The page should be implemented in static HTML and CSS, and link to https://status.brave.com/

## Designs
![mockup](https://user-images.githubusercontent.com/2388823/55661267-b9422280-57bf-11e9-95aa-b8b565306a61.png)

The new maintenance page should use the Creators website header with all the links and user actions removed. The illustration as well as text is confined to 650px width. If viewed through any viewport smaller than (650px +page margins), then the content should take up full width and scale responsively.

Grab the svg from this zipped folder: [svg.zip](https://github.com/brave-intl/publishers/files/3049945/svg.zip)

Heading 
> We’ll be back soon

Description
> This site is currently undergoing maintenance. We’re sorry for any inconveniences this may have caused. [Check for updates](https://status.brave.com/)

**Comment by dlipeles** [comment]
Working with @karenkliu on this 👍

**Comment by karenkliu** [comment]
@dlipeles Added my designs; ping me if you need any further guidance!

**Comment by dlipeles** [comment]
Looks okay to me @karenkliu I'll implement this and follow up with you. Thanks again for helping out here 🎨

**Comment by corymcdonald** [comment]
Completed :) 
MAINTENANCE_PAGE_URL=https://publishers-maintenance-nrfvq3lrh.now.sh/
