### ISSUE TITLE
marketing checkbox needs to be checked by default

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#575]
it's currently unchecked. we want this to be checked by default -- we assume/hope more users would be ok with this term than users who are not, hence conserving the labor for the majority.

![image](https://user-images.githubusercontent.com/4369856/35615746-f5a3a504-0627-11e8-93df-6f13d1a8d069.png)

**Comment by dgeb** [comment]
This setting is checked by default for new accounts. However, if your account existed prior to the multi-channel rollout then the previous setting will have been migrated.
