### ISSUE TITLE
inconsistent dialog style

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#576]
1. this dialog style is from the current browser. let's use the brave payments dialog style.
2. in the dialog content: the title should typically echo the action/operation the user invoked. in this case, 'Remove Channel' (see attached below for e.g.)

![image](https://user-images.githubusercontent.com/4369856/35616366-e7862684-0629-11e8-8a48-61f6f797672d.png)

![2fa-removekey-1](https://user-images.githubusercontent.com/4369856/35616600-9946d8be-062a-11e8-94e2-b1c919a2586b.png)

**Comment by mixonic** [comment]
This should be as simple as using the modal system documented in https://github.com/brave-intl/publishers/blob/staging/app/javascript/modal.js. I'll pick this up.
