### ISSUE TITLE
simplify the message

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#578]
1. we will always keep the wording to a minimum without loosing the essential content: 'You already have authentication code configured.' is not needed since the user clicked '**Re**configure'.  as a result, the critical message 'invalidating the current code' bit is obscured in the block.  --> keep only the second sentence and remove the first sentence.

2.  this falls under the message type 'warning' ('!' mark and yellow background), rather than 'info' with blue.

![image](https://user-images.githubusercontent.com/4369856/35618095-c404f8fc-062e-11e8-9876-bbceb4c24a34.png)

**Comment by mixonic** [comment]
I'll pick this up

**Comment by mixonic** [comment]
Actually I think @kpfefferle is already in here, perhaps this should be folded into that work.
