### ISSUE TITLE
Handle unverified site channels that have the same `brave_publisher_id` as a verified channel

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#579]
When two channels have the same `brave_publisher_id`, but one is verified, attempts to verify the second one return the channel_id for the verified channel. The current code raises an exception and this is caught by sentry. We have a large growing log of these exceptions.

We prevent new channels from being created if a verified dup exists, but do not prevent two owners from attempting to register the same `brave_publisher_id`. After one is verified we still allow the other to attempt to verify, and the `EnqueueSiteChannelVerifications` job actively tries to verify all recent channels once an hour.

Eyeshade is returning the channel id of the verified channel, which doesn't match the one we're trying to verify. We need to handle this case. I propose we delete the unverified channel and send an email to the owner explaining the situation.

One stop gap measure is to update Publishers to ignore these cases silently. It will still put extra load on eyeshade, but won't raise exceptions.

Another stop gap idea is to change eyeshade to only attempt to verify using tokens created for the specified owner, and fail if the channel is verified by another owner. This was the behavior I expected, but we probably don't need to change it since a fix could be made on Publishers.

**Comment by corymcdonald** [comment]
I don't think this is an issue anymore since we've introduced the channel transfer functionality.
