### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by luixxiul** [brave-intl/publishers#58]
Will this be done via Transifex too?

**Comment by luixxiul** [comment]
Considering that even I've got paid via my small website, the number of unverified payment would be quite large, especially in foreign contries. I would help translating in Japanese, whether it's via Transifex or not.

**Comment by ayumi** [comment]
We're using standard Rails localization and the current strings are all in https://github.com/brave/publishers/blob/master/config/locales/en.yml .
I think it'll be translated in Transifex eventually.

**Comment by luixxiul** [comment]
Both cryptcurrencies and YouTubers are a hot topic in Japan and BAT will definitely helps us to get more users here. I cannot wait working on localization 🦁

**Comment by mrose17** [comment]
copied from https://github.com/brave-intl/publishers/issues/256

We're introducing limited content into the stylesheets for the overlay text on the Publication Type chooser page (email_verified). These strings should be able to be translated, so the stylesheets need to support internationalization. In addition different languages may need different text (fonts, spacing, etc) styles and language specific images.

Based on very limited research I see we could handle this in several ways. Two are linked below, though others probably exist:

https://stackoverflow.com/questions/11577083/access-the-locale-in-ruby-in-css-files
https://stackoverflow.com/questions/9310044/rails-i18n-of-css-file

Let's examine the current and future needs before settling on a strategy.

**Comment by yachtcaptain23** [comment]
Re-prioritizing later when product team requests it.
