### ISSUE TITLE
Offer Wordpress plugin as website verification option

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#6]
WP is 26.9% of the internet [1], so for site ownership verification we should offer a simple happy WordPress way.

The plugin might live in a separate repo.

@jkup @mrose17 @BrendanEich 

[1] https://w3techs.com/technologies/details/cm-wordpress/all/all

**Comment by mrose17** [comment]
i am looking into the existing plugin to see if it can be verified using the current wordpress, etc.

**Comment by mrose17** [comment]
current repo: https://github.com/brave/wordpress-well-known

status: trying to get the author to merge the PR and update wordpress.org

**Comment by alexwykoff** [comment]
I think this is shipped now 😸

**Comment by mrose17** [comment]
INDEED!
