### ISSUE TITLE
Changes to wallet address should be delayed by 1 week

### ISSUE THREAD

**Issue by da2x** [brave-intl/publishers#60]
Expanding on issue #59.

Any changes to the publisher’s wallet address should take 7 days to affect. Payments should not be made to the old address during this lockdown window, but be put on pause until after the one week time window closes.

This gives publishers one week warning to take action after unauthorized changes to their wallet address. (It’s very common for changes to e.g. a PayPayl payout address to trigger such a lockdown period in publisher payments in affiliate programs and the like.)

**Comment by ayumi** [comment]
since we've moved to uphold, is this no longer needed?

**Comment by mrose17** [comment]
i think is OBE. so i am closing it.
