### ISSUE TITLE
Channel removal service

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#606]
service which can detach channels from Publishers (and Eyeshade) and delete them
to mimic the normal Remove Channel feature; for use by admins via console; and 

would be for fixing up YouTubers who did Google Login who were affected by multi-chan

please whitelist only YouTube Channel type. (should raise if running on SiteChannel, Twitch, etc)

**Comment by nvonpentz** [comment]
I achieved this with:
```ruby
publishers = Publisher.where("email ~* ?", 'pages.plusgoogle.com').where(uphold_verified: false)

publishers.each {|p| c = p.channels.first; PublisherChannelDeleter.new(publisher: p, channel_identifier: c.details.channel_identifier).perform; c.destroy!;}
```

I've been writing and using a SupportHelper module to aid in general support tasks.  As part of this I could write a `SupportHelper# delete_channel` method that is a wrapper for the above logic.

**Comment by yachtcaptain23** [comment]
Dup of the admin dashboard features.
