### ISSUE TITLE
set default UPHOLD_AUTHORIZATION_ENDPOINT to facilitate development

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#608]
This is the remaining env var so the app works out of the box, without README Step 8 (sourcing an additional dev file with env vars).
We should update the README accordingly.

UPHOLD_AUTHORIZATION_ENDPOINT="https://sandbox.uphold.com/authorize/<UPHOLD_CLIENT_ID>?scope=<UPHOLD_SCOPE>&intention=signup&state=<STATE>"

**Comment by ggladden** [comment]
I also had to add -

UPHOLD_CLIENT_ID
UPHOLD_SCOPE

I'd be happy to make the README changes and submit a pull request if you let me know what default values to use for the development environment.
