### ISSUE TITLE
API endpoint for in-process verification_tokens

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#615]
For the verification_tokens in process this will be the site channels that have a verification token, but have not yet been verified.

Waiting on details on as to the format and endpoint for this api. @mrose17 will provide.

**Comment by ayumi** [comment]
is this to show users who've inputted their token that "We are checking your token hang on"?

**Comment by lgebhardt** [comment]
Chatting with @mrose17 on Slack we're going to use the logic from the EnqueueSiteChannelVerifications job (SiteChannelDetails.recent_unverified_site_channels) to choose the site channels.
