### ISSUE TITLE
twitch channel support: allowing twitch publishers to receive Brave contributions 

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#632]
**Quick Summary**
The UX/UI for providing the ability for the user to verify their twitch channel is largely leveraged from the YT channel support as the verification process follows the same pattern: i.e. the third party (twitch) authorization of the user's channel ownership and sharing the channel meta data from our API call. 

**Key UI changes**
_Primarily 2 pieces for now. I'm sure we'll run into cases/errors we need to handle later..._

**1. Pick a channel** 
Allow our user to add & verify their twitch channel by providing the entry point: we're simply adding 'twitch' as the 3rd option on the 'Add Channel' dialog, prompted when the user clicks on Add Channel button from their dashboard.  (after which, the user goes through the screens served from twitch to authorize their channels before returning to our site). 
*note: the dialog is presented in an overlay format (compared to the full page format in the current version). 

![2-twitch-addch](https://user-images.githubusercontent.com/4369856/36451084-b83a91a0-1644-11e8-9bec-60c1d7e20340.png)
3rd box (on twitch) is in hover mode.

**2. Distinguish channels on the dashboard**
Indicate the channel type in the channel card on our dashboard once it's verified. The purpose of this is to distinguish channels that are hosted on different platforms but their attributes may be identical. 
*note: 1) by adding this, we're removing the attribution of the platform from the channel name on the card: i.e.   '[channel name] on YouTube'  --> it's simply '[channel name]' (see below)
2) unrelated but want to mention: channels are ordered reverse chronologically for now (newer on top).

![3-twitch-dash-added](https://user-images.githubusercontent.com/4369856/36451467-0727202a-1646-11e8-8af8-72741bdcbc06.png)

![image](https://user-images.githubusercontent.com/4369856/36451499-167bb554-1646-11e8-96c8-c888b3140071.png)

@mixonic @nvonpentz @ayumi @lgebhardt

**Comment by ayumi** [comment]
:+1: 
for channel specific balances, I'm not sure we can get that info yet. cc @mrose17

**Comment by mrose17** [comment]
@ayumi - we can use `GET /v2/publishers/{publisher}/balance` and `GET /v1/publishers/{publisher}/statement` !!

**Comment by mixonic** [comment]
I'd like to note that this design is going to require JavaScript be running for the modal to be implemented. We can make a fallback page for non-JavaScript users, but that of course increases the development workload. I'm raising this during the design phase in case we want to make adjustments to minimize the forking of user experience (I guess just keep them going to a new page as we do now).

**Comment by mrose17** [comment]
right. at this point, i think we're going to have to require javascript... @ayumi - your thoughts?

**Comment by ayumi** [comment]
@mixonic thanks for noticing this!

Personally I feel that too much of the internet requires that you run JavaScript. JS is pretty cool and lets you do lots of cool stuff. Unfortunately some of that stuff is Bad. Such as tracking you across websites and stealing your computing resources (cryptocoin miners).

Brave stands for user privacy and security on the web. I think requiring people to run JavaScript to participate in the BAT ecosystem is equivocal and contrary to our core values. How can we produce a web browser with shields configurable to block JS, yet run a website that demands you disable it? We know firsthand all the bad stuff you can do with JS. We should prove to the world that we can ship a top notch product that doesn't require JS.

When I wrote the first version of the Publishers website, I intentionally supported non-JavaScript users. In my opinion, it's the best way to run a compatible, performant and thoughtful website. However, it's been immensely difficult to communicate these motivations.

I've always tried really hard to make this project something we can all be proud of. In a lot of ways I think we are succeeding: Our test coverage is great, our security is good, we ship stuff quickly, and the UI is top notch. I am proud we have not needed JavaScript so far, and don't think adding a modal is a strong enough reason to change our current course.
