### ISSUE TITLE
Restore piwik/matomo stats

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#636]
We lost piwik stats on Jan 12th, 2018 and we don't why.

## Leads
https://matomo.org/faq/troubleshooting/#faq_58
### Piwik/Matoma release broke the stats
Piwik (now Matomo) 3.3.0 was released on Jan 12th, 2018, this could be related  https://matomo.org/changelog/.

Update: We have not updated piwik on analytics.brave.com to use 3.3.0, and brave.com piwik stats were unaffected, so this is probably not the problem.  I haven't found any other piwik users who have reported this.

### We broke the stats with Jan 12th release
We did a release on Jan 12th, 2018 which could be related https://github.com/brave-intl/publishers/pull/482

Update: There is _nothing_ in this PR that touches JS or Piwik or the html which triggers them.

### We failed to include analytics.js with webpacker update
We could not be including it in the bundled JS which was released late on Jan 11th https://github.com/brave-intl/publishers/pull/470. 
> @w0ts0n I've just done a bit of spelunking and from what I understand. For piwik to work, you need to envoke this JS https://github.com/brave-intl/publishers/blob/master/app/javascript/analytics.js and I can't see that being called anywhere on https://publishers.basicattentiontoken.org/
@ayumi perhaps with the webpack migration we failed to include it in the bundled JS

Update:  analytics.js is being included in application.js.  I've checked the staging branch locally and analytics.js _is_ loading and executing on every page. 

### We dropped the config var on the server
Update: The `PIWIK_HOST` config var has always been correctly set.  On production:
```
irb(main):002:0> Rails.application.secrets[:piwik_host]
=> "https://analytics.brave.com/"
```

### Tracking code on analytics.brave.com does not match publishers app
Update: Nope, it does, it's 6.

### Also
For some reason, we still [get 1-3 actions recorded every few days](https://analytics.brave.com/index.php?module=CoreHome&action=index&idSite=6&period=range&date=last7&updated=1#?idSite=6&period=range&date=2018-01-09,2018-01-25&category=General_Visitors&subcategory=VisitorInterest_Engagement), and I cannot explain why.

cc @alexwykoff @ayumi @mrose17 @w0ts0n @mandar-brave

**Comment by ayumi** [comment]
thanks for looking into this! i'm going to refer to piwik as matamo now

i think there's a plausible explanation for why the home and signup pages don't get events.
although we've got tracking tags there (e.g. home page Get Started button), we don't actually include analytics.js on those two pages.

We should include analytics.js on every page.

i saw also a case where we had the dashboard Update Contact button [tagged for tracking](https://github.com/brave-intl/publishers/blob/staging/app/views/publishers/home.html.slim#L117) however we bound a [click handler which did preventDefault and prevented bubbling](https://github.com/brave-intl/publishers/blob/staging/app/javascript/publishers/home.js#L166).

**Comment by w0ts0n** [comment]
I want to note, I will be upgrading pikwi > matamo this weekend
https://github.com/brave/internal/issues/211

But I 100% agree with Ayumi.

**Comment by nvonpentz** [comment]
@ayumi @w0ts0n Unfortunately, I've confirmed that analytics.js is loaded on the static homepage, sign up/login page and the dashboard.  I put in a `debugger` above [this line](https://github.com/brave-intl/publishers/blob/57cb5eaee5c9b4c5c9116295b15803073964f2cb/app/javascript/analytics.js#L19) and execution _is_ being halted for all pages.

I'm tending toward thinking the matomo update is the culprit.  Since we have different methods for sending matomo stats between brave.com and publishers, the fact that brave.com still has stats doesn't rule it out in my mind.

**Comment by nvonpentz** [comment]
Interesting, ^the above is true when I run an up-to-date copy of staging, but not true on the live production site.
