### ISSUE TITLE
Add support for backup TOTP codes

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#640]
Some users are locked out of their publisher accounts because they have lost TOTP codes.  In order to regain control of their account they must contact Brave and we must speak with them on the phone.  As the site grows this process will not be sustainable, so we should create backup TOTP codes as requested by @mrose17.

**Comment by ayumi** [comment]
we discussed this previously in https://github.com/brave-intl/publishers/issues/364#issuecomment-350075192

even with backups, most people will lose them.

> fallback will probably end up being phone/video call with support person who does some kind of identity verification (like using their on-file W9); we can just use this as the primary recovery strategy for now
> for advanced users, we could ask for a pgp public key and email them a recovery email encrypted to it (1st factor = email account ownership, 2nd factor = pgp private key)

**Comment by kjozwiak** [comment]
Agreed that most people will probably never even bother backing up their backup codes, but at least the option is there and we give more advanced users a chance to recover incase they get locked out. Having the option to recover your account on your own will probably cut down on support somewhat, which makes adding this worth it IMO 👍

**Comment by ayumi** [comment]
I'd like to suggest we discuss this at the next security meeting. cc @flamsmark

**Comment by flamsmark** [comment]
It's on the list. Next meeting is 2018-03-13.

**Comment by mrose17** [comment]
this is something that slack does. note that if you don't have your code, you can have it SMS a one-time code to your phone... i also noticed that some sites ask you to confirm your phone number every N logins in order to keep it current... perhaps a possibility?

<img width="705" alt="0" src="https://user-images.githubusercontent.com/400552/36763606-91d7c890-1bdd-11e8-84b1-ebc7f1682ca6.png">

**Comment by nvonpentz** [comment]
Another proposed solution is that we have publishers reverify their channels #377

**Comment by nvonpentz** [comment]
The consensus is to have publishers reverify their channels, this way the process to regain control of an account locked out via lost TOTP is the same as changes in domain ownership.

1.  A publisher requests to reverify the domains in their account (either for changes in ownership or for missing TOTP codes)
2. We send emails to the current owner alerting them the activity
3.  If the domains are successfully verified and there is no contest after a waiting period (3 days?), we allow them to reset TOTP codes, or claim ownership of the channel

**Comment by flamsmark** [comment]
Additional notes:
- If there *is* a contest we manually mediate.
- If this results in an account without any properties or pending BAT, the account is removed.

**Comment by nvonpentz** [comment]
Closing in favor of #377
