### ISSUE TITLE
Flappy test: LaunchPromoTest#test_generates_a_promo_token_and_sends_email_to_each_publisher

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#644]
bin/rails test --seed 11762 --verbose

PublisherSerializerTest#test_owners_are_serialized_as_JSON_and_include_owner_and_channel_details_rolled_up = 0.08 s = F

Failure:
PublisherSerializerTest#test_owners_are_serialized_as_JSON_and_include_owner_and_channel_details_rolled_up [/home/user/repos/github.com/brave-intl/publishers/test/serializers/publisher_serializer_test.rb:16]:
Expected false to be truthy

**Comment by ayumi** [comment]
can't repro with this seed anymore

**Comment by hahmed** [comment]
Found this issue still exist with another seed

`rails test --seed 60009`

```
PublisherSerializerTest#test_owners_are_serialized_as_JSON_and_include_owner_and_channel_details_rolled_up = 0.01 s = F

Failure:
PublisherSerializerTest#test_owners_are_serialized_as_JSON_and_include_owner_and_channel_details_rolled_up [/Users/haroon/Projects/publishers/test/serializers/publisher_serializer_test.rb:16]:
Expected false to be truthy.

bin/rails test test/serializers/publisher_serializer_test.rb:4
```

**Comment by hahmed** [comment]
Looks like the issue here is the channel would have been deleted by the integration test `features/publishers_home_test.rb'  in the test `test "verified channel can be removed after confirmation" do`.

To fix this, would we simple re-add the channel in the teardown method in `features/publishers_home_test.rb'?

```
def after_teardown
    super
    readd_removed_channels
end
```
