### ISSUE TITLE
changing username doesn't dynamically change the username in the dropdown

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#649]
When you change your username via the `Contact` section of the site, the dropdown name doesn't automatically change. Users need to refresh the website to see the change take affect. This isn't high priority, but would be nice if the name was automatically changed and didn't need a manual refresh.

STR:

* login onto Publishers
* once logged, change your name via `Edit Contact`
* change the name and select `Update`

You'll notice that the name under the menu isn't changed and requires a page refresh. We should probably change the name in the menu dynamically rather than requiring a refresh, example:

![contactname](https://user-images.githubusercontent.com/2602313/36570971-8aa64e72-1802-11e8-8068-762239edaccb.gif)

**Comment by dgeb** [comment]
Good catch. Thank you for reporting @kjozwiak!
