### ISSUE TITLE
making the "Now verifying your domain..." page more intuitive

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#650]
I think we need to make the `Now verifying your domain...` page a bit more intuitive as it's currently pretty confusing. The animation will keep going and going even though the page says that `You can leave this screen now.` However, there's no obvious way of returning to the dashboard.

I think we should:

* have a button that says `Back to dashboard` or something similar somewhere on the page.
* remove the animation, tell the user that they should receive an email within 24hrs and have them return to their dashboard where there will be more information on the verification process.

When I was going through this screen, I wasn't really sure what to do. The page was giving me mixed messages. The animation was telling me that verification is still going, but it was also telling me that I can leave the page but it didn't give me any obvious way to go back. I was a bit scared about leaving the page as I thought the verification process was still happening.

STR:

* login into the Publishers website
* select `Add Channel` -> `Site Operator`
* enter the domain you would like to add, I used `https://kjozwiak.github.io/`
* once you've added the needed info, click on `Verify`

You'll get the following verification page:

<img width="1675" alt="screen shot 2018-02-22 at 7 16 16 pm" src="https://user-images.githubusercontent.com/2602313/36573378-a043f1e2-180e-11e8-9bcb-5123dfad1663.png">

CC'ing @jenn-rhim

**Comment by dgeb** [comment]
@kjozwiak Again, please see #655 for @jenn-rhim's update to this design which eliminates the "Now verifying your domain..." page entirely. I think Jenn's design update makes this flow much more intuitive.

**Comment by ayumi** [comment]
let's track thoughts with site verification flow within #655 since it's the most complete of the issues.

**Comment by kjozwiak** [comment]
awesome, thanks @ayumi @dgeb.
