### ISSUE TITLE
removing/rename "Cancel" button from "Now verifying your domain..." page

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#651]
When you're verifying a website via the "Now verifying your domain..." page, you'll notice that there's a `Cancel` button located in the top right corner of the page. The `Cancel` button points to the following:

* `https://publishers.basicattentiontoken.org/publishers/home`

As a user, I would expect that pressing the `Cancel` button would completely cancel the process rather then returning me back to the dashboard.

Example of the `Cancel` button:

<img width="1145" alt="screen shot 2018-02-22 at 8 45 49 pm" src="https://user-images.githubusercontent.com/2602313/36574167-4da4a7b6-1812-11e8-9b25-c4b1453b43f1.png">

**Comment by dgeb** [comment]
@kjozwiak Please see #655 for @jenn-rhim's update to this design which eliminates the "Now verifying your domain..." page entirely. During the registration process, the "Cancel" button will simply delete any partially registered channel and return the user to the dashboard.

**Comment by kjozwiak** [comment]
sounds good, thanks @dgeb 👍
