### ISSUE TITLE
removing "Add Channel" text from "Now verifying your domain..." page

### ISSUE THREAD

**Issue by kjozwiak** [brave-intl/publishers#652]
When verifying a website, there's a `Add Channel` text in the top left corner of the screen. Do we really need that there? When I was initially adding my website, I though that the `Add Channel` part might be a link to go back to the dashboard as there's no obvious way of leaving the "Now verifying your domain..." page (#650).

I think it's pretty obvious that you're already adding a channel/website from the progress bar at the top of the page.

I might be wrong here, but I don't think we need it there. @jenn-rhim thoughts?

Example:

<img width="1331" alt="screen shot 2018-02-22 at 8 57 42 pm" src="https://user-images.githubusercontent.com/2602313/36574741-1dfd051e-1815-11e8-82ed-9f50850f9e9a.png">

**Comment by dgeb** [comment]
@kjozwiak Thanks for reporting this. Please see #655 for @jenn-rhim's update to this design which eliminates the "Now verifying your domain..." page entirely.

**Comment by kjozwiak** [comment]
sounds good, thanks @dgeb 👍
