### ISSUE TITLE
Twitch launch email

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#677]
This is blocked by #623.

The blacklisted emails can be found in https://github.com/brave-intl/internal/issues/24.  When we send this email is TBD.

#### Subject
Twitch Support is Here!
#### Body
We are so excited to announce that we now support Twitch channels in Brave Payments, making it easy for you to receive revenue from your fans. The only thing you need to do is to add your channel and verify it with us by logging into your account. You just need to be the owner of the channel to be able to add it to your account.

We hope this improvement will greatly increase earnings for the streamers in Twitch community.  Check it out and don’t forget to tell your friends and network so everyone can take advantage of Brave Payments!

The Brave Payments Team

**Comment by yachtcaptain23** [comment]
Larry brings up a good point that we should also include users from Sendgrid as part of this marketing campaign.

**Comment by mandar-brave** [comment]
@yachtcaptain23 please close this issue!
