### ISSUE TITLE
Need to use the official name 'Brave Payments' when making API call to Twitch

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#682]
currently we seem to be submitting 'BAT Publishers'.

![screen shot 2018-02-27 at 4 52 20 pm](https://user-images.githubusercontent.com/4369856/36764310-e1f34b58-1be0-11e8-822a-4875881dc9fd.png)

**Comment by mixonic** [comment]
The suggestion is to named the app "Brave Payments" instead of "BAT Publishers". This should be done on the Twitch admin dashboard.

**Comment by mandar-brave** [comment]
@ayumi i think you own the partner app account on twitch - ping me if you want to make above change or i am happy to do it. cheers!

**Comment by ayumi** [comment]
have updated
