### ISSUE TITLE
Need to provide navigable error screen to the user

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#683]
when the twitch oauth failed, i get this screen: there's no obvious way to return or proceed or know where I am. 

![screen shot 2018-02-27 at 4 52 20 pm](https://user-images.githubusercontent.com/4369856/36764407-56da8c60-1be1-11e8-9aa0-b0ff78c2baf9.png)

Use the same overlay as the one we use to notify the YT user that the channel has been claimed.

**Comment by nvonpentz** [comment]
Mostly addressed by #688
