### ISSUE TITLE
Active promo should be applied to any channels added during the period. 

### ISSUE THREAD

**Issue by jenn-rhim** [brave-intl/publishers#685]
It doesn't seem that the active promo is being applied to the new channel I just added on the dashboard. The channel container is missing the referral link, social media share functionality. 

![screen shot 2018-02-27 at 5 02 33 pm](https://user-images.githubusercontent.com/4369856/36764565-fe9b9fb6-1be1-11e8-8414-216ae79b7e68.png)

**Comment by nvonpentz** [comment]
This is expected since the promo server on production did not support twitch at the time when the above occurred
