### ISSUE TITLE
Remove {channel}.channel_id and use {channel}.details.channel_identifier in PromoRegistrar

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#691]
As the discussion in #673, we have two methods that return a channel's identifier:

`{channel}.channel_id`
`{channel}.details.channel_identifier`

The first method was created in error when the initial referral promo code was written, when I didn't realize second method was available. The only difference is that `{channel}.channel_id `does not include the `youtube#channel` or `twitch#channel:` prefix. ex:
```
irb(main):005:0> YoutubeChannelDetails.first.channel.channel_id
=> "UCXmw_D6tX85F0y3DcDws5Hg"
irb(main):006:0> YoutubeChannelDetails.first.channel_identifier
=> "youtube#channel:UCXmw_D6tX85F0y3DcDws5Hg"
```

We should remove `{channel}.channel_id` and use `{channel}.details.channel_identifier` instead in the `PromoRegistrar`.  However, since this method has been already used in production with promo services, we will need to update the promo services db to reflect this change for channels that have already been registered for the promo.

**Comment by yachtcaptain23** [comment]
Assigned to myself to figure out if this would break anything.

**Comment by corymcdonald** [comment]
Looks like this was already done 😄

**Comment by nvonpentz** [comment]
I think this probably should stay open, promo still doesn't use eyeshade naming conventions for channels
```
DATABASE=> select count(*) from publishers where channel like '%youtube#channel:%';
 count
-------
     0
(1 row)
```

**Comment by corymcdonald** [comment]
Looks like here is where we send the channel id and type - https://github.com/brave-intl/publishers/blob/staging/app/services/promo/publisher_channels_registrar.rb#L115

But the Promo server also [automatically converts this when sending over to Eyeshade](https://github.com/brave-intl/vault-promo-services/blob/33382ea5c38a3ec140033afdf0c81a0b6381c2d3/src/referral/payout.js#L54).

**Comment by nvonpentz** [comment]
I think it's this line - https://github.com/brave-intl/publishers/blob/a95106b245857832f0310651bcdae14dc274694e/app/services/promo/publisher_channels_registrar.rb#L113

@corymcdonald Yes, we should probably use the same identifier across all the databases.  Not a big priority since we have something that's functional, but feel like it's good to have this captured as a known issue

**Comment by tsmartt** [comment]
Closing as stale.
