### ISSUE TITLE
Change Uphold app name to Brave Payments

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#699]
Currently it is named "Basic Attention Token"
![image](https://user-images.githubusercontent.com/12549658/36923675-04dae026-1e3a-11e8-98d0-f31ba4a862d1.png)

cc @ayumi @w0ts0n @mrose17

**Comment by mrose17** [comment]
could we please use whatever name we use for the other oauth accounts??? let's be consistent.

**Comment by nvonpentz** [comment]
@mrose17 We want to change everything to "Brave Payments" if it has not been changed already

**Comment by mrose17** [comment]
ok. as long as we're consistent, that ought to be fine. keep in mind that on uphold, you aren't allowed to have spaces in the name, hence "BravePublishers" rather than "Brave Publishers".

**Comment by nvonpentz** [comment]
@mrose17 Is this a recent change?  It currently reads as "Basic Attention Token" -- with spaces.

**Comment by mrose17** [comment]
@nvonpentz - my bad. i was thinking about the account name at uphold, rather than the oauth2 app. so... _never mind!_ sorry for the confusion.

**Comment by nvonpentz** [comment]
@w0ts0n who can update this?

**Comment by w0ts0n** [comment]
@nvonpentz can you ping me on Slack so I can be bought up to speed. I'm not sure I know what this is.

**Comment by nvonpentz** [comment]
Resolved, thanks @w0ts0n!
