### ISSUE TITLE
Add email notifications endpoint for publisher messages

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#7]
When a publisher accrues a sufficient pending balance, we'll send them a notification email to {webmaster, hostmaster}@foo.example.com (per [RFC 2142](https://tools.ietf.org/html/rfc2142)) and also to WHOIS contacts*.
- publishers will provide a notifications endpoint
- eyeshade will detect pending balances and trigger welcome emails

Clarification needed:
- Which of the WHOIS contacts?

See also: [Brave Payments verification spec](https://gist.github.com/diracdeltas/7c1792a7484ca98ab016710467d1e729).

@mrose17 @diracdeltas

**Comment by diracdeltas** [comment]
reg-c and maybe tech-c contacts?

**Comment by mrose17** [comment]
yes, both of them, all of them you can find. the more, the better.

**Comment by ayumi** [comment]
`POST /publishers/{id}/notifications` has been added which sends an email to the publisher.

Right now it only sends "Payments fully activated and ready to go" emails.
This :gift: 's emails will be added in the future.

**Comment by alexwykoff** [comment]
mr : add an api call for message type and parameters  and second, define a template for each message type

aw : what about timed messages?

mr : all of that logic will be in eyeshade, not publishers

to summarize : add an api call per mr's directions above

**Comment by alexwykoff** [comment]
aw : do we need to do anything fancy to avoid spam lists?

mr : in short, no, @ayumi managed mailgun settings appropriately 😄

**Comment by kpfefferle** [comment]
I'm starting to take a look at addressing this now
