### ISSUE TITLE
Feature Request - Add support for subdomains

### ISSUE THREAD

**Issue by alexwykoff** [brave-intl/publishers#70]
A user in the field has asked for support for subdomains as they sell theirs.

**Comment by dogweather** [comment]
I also just posted a question about this to the subreddit:

The app is silent as to subdomains and verification. It seems that an 'apex' domain will verify for a `www.` site. But I use many subdomains: e.g., `www.public.law`, but also `newyork.public.law`, `texas.public.law`. 

How is the system intended to be used? How many "channels" should I create? Can / should I create just one for `public.law` — the apex domain, which isn't actually used for serving content?

**Comment by yachtcaptain23** [comment]
We'll be doing this in https://github.com/brave-intl/publishers/issues/817

**Comment by grq79** [comment]
So, it seems that creator channels by subdomains is dead in the water? Ideally, it would help to at least allow for each sub domain to have it's own way to see which subdomain gets tips so as to accurate track data on content. Are there any updates for this at all?
