### ISSUE TITLE
Adding Site Channel: No clear way to "pause" channel addition

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#710]
Prior to #655 pressing cancel during adding a site channel would put channel into a state where the user could come back to it. They would see a "One more step to complete..." message and the "Let's Finish" button:

![screen shot 2018-03-12 at 10 41 49 am](https://user-images.githubusercontent.com/29154/37290406-8212cf9a-25e2-11e8-8790-be99309c4ef1.png)

Now the `cancel` button deletes the channel and there isn't a clear way to get back to the dashboard to show the channel in the "One more step to complete..." state. Note, it is still possible by navigating to "/publishers/home", but there's no UI for this option.

There are legitimate use cases I can think of where a user is not prepared to click verify, but does not want to lose the verification token that results from pressing cancel. For example assigning the task of setting the token in the `.well-known` or dns TXT record to another person. Without a clear way to "pause" the process the user will be tempted to click "Cancel" and break the process.

I propose we add a new button such as "Continue later..." that takes them back to the dashboard. We could revert to the previous behavior (`cancel` does not delete the channel once a verification token was shown to the user), but this seems less clear and I suspect is why the change in #655 was made.

**Comment by nvonpentz** [comment]
@jenn-rhim can you please comment?

**Comment by jenn-rhim** [comment]
Thanks @lgebhardt  This is a good catch to cover that case we've been handling implicitly. 

I'm proposing '**Complete Verification Later**' as the wording with the ghost button treatment. See below in the mockup.

![instruction-action2](https://user-images.githubusercontent.com/4369856/37486475-ce5b6716-284b-11e8-88ba-bf1211beb36b.png)
