### ISSUE TITLE
Update Eyeshade when an unverified site channel is removed

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#715]
Currently when an unverified site channel is deleted, we do not inform Eyeshade.  We should do this in order to keep Publishers and Eyeshade in sync.

The usual endpoint to that notifies Eyeshade of a channel removal,
```
DELETE /v1/owners/#{owner_identifier}/#{channel_identifier}
```
will not work because that endpoint assumes the channel is verified.  This issue is blocked until we have a different endpoint to hit.

cc @mrose17 @lgebhardt

**Comment by mrose17** [comment]
this is addressed by https://github.com/brave-intl/bat-ledger/pull/159, which is under review.

the new endpoint is `DELETE /v1/owners/{owner}/verify/{publisher}`

**Comment by yachtcaptain23** [comment]
Closed this as we verify on Publishers now.
