### ISSUE TITLE
Allow multiple users to access same publisher account

### ISSUE THREAD

**Issue by realuser** [brave-intl/publishers#718]
Is there a way for multiple people to access a single publisher account?  Currently, it doesn't seem possible and especially with the email login system it's not even possible to share credentials (as a workaround).

Ideally there would be an option for read-only account access.  Another level of customization would be to allow users to see only certain properties within an account.

Main purpose would be to allow multiple users to view account earnings.  Simple example is two people working on a project both needing to see earnings.

**Comment by nvonpentz** [comment]
Hi, currently the only way to log in is with your email, so you could achieve this right now by using a shared email address.

In terms of adding this functionality in the future - this seems like a product decision, so let's hear from the product team @mandar-brave @jenn-rhim.

**Comment by nvonpentz** [comment]
This would be a nice feature, so let's revisit this sometime in the future.

**Comment by yachtcaptain23** [comment]
@realuser is it possible to share emails and your 2FA?

**Comment by realuser** [comment]
If you're referring to the 2FA on https://publishers.basicattentiontoken.org then I'm not sure how you would share that.

If you want to get businesses to become brave publishers you should consider supporting multiple users accessing a single account.  Imagine a large website like yahoo, are they going to have a single email address that they share to enable relevant people to access brave data?

**Comment by yachtcaptain23** [comment]
We're supporting this in our pull request to track `organizations` and `memberships` https://github.com/brave-intl/publishers/issues/1317

If you're representing a large organization, you can contact our business development team via our website
