### ISSUE TITLE
publisher dashboard should include link for contribution settlement statement

### ISSUE THREAD

**Issue by mrose17** [brave-intl/publishers#74]
when a contribution settlement occurs, the publisher should receive an email and the publisher dashboard should contain a link to download the statement.

**Comment by alexwykoff** [comment]
mr : @ayumi what is your take on the dashboard?

ay : i think we probably need only a single page with a few links. we probably don't need a framework per say. let's keep it simple & pragmatic

mr : i agree

bc : ditto

mr : i will close this and take action on #76 

to summarize : @mrose17 will handle

**Comment by mrose17** [comment]
the "ask": when a verified publisher is at https://publishers.brave.com/publishers/home, they will see something like this:
![0](https://user-images.githubusercontent.com/400552/29220407-cc003edc-7e6f-11e7-882e-2e53207d5f75.png)
in addition to what we see here, there should be a form for "Publisher Statements". it should include a "Time range" drop-down with these choices:
- Past 7 days
- Past 30 days
- Month-to-date
- Past month
- Year-to-date
- Last year
- All

there should also be an indicator as to whether the publisher is on on the "auto-exclude" list, and if so, a button that will open up a mailto: to discuss that.

so, first step is for @bradleyrichter to decide on the UI... then i'll put together the API summary.

**Comment by mrose17** [comment]
![0](https://user-images.githubusercontent.com/400552/29896472-fef9baa8-8d91-11e7-84be-349fc3a8123e.png)
![1](https://user-images.githubusercontent.com/400552/29896474-ff0291d2-8d91-11e7-8d2b-2e6d1b9dfc6c.png)
![2](https://user-images.githubusercontent.com/400552/29896473-fefb4724-8d91-11e7-8e73-8eb55d84d3aa.png)

**Comment by mrose17** [comment]
API changes:

1. when calling `publisher_token_requester.rb::perform` include a `query` parameter of `?show_verification_status=true|false`

2. to update `show_verification_status` use `PUT /v1/publishers/{publisher}` with a payload of `{ "show_verification_status": true|false }`

**Comment by dgeb** [comment]
@mrose17 A few questions:

> when calling `publisher_token_requester.rb::perform` include a `query` parameter of `?show_verification_status=true|false`

How does the additional query parameter affect the result? Currently just `{ token: value }` is returned. Will the addition of `?show_verification_status=true` also return a `show_verification_status` member as a sibling to `token`? Is `?show_verification_status=false` the same as not including any query params?

> you can also modify publisher_wallet_setter.rb::perform to use this endpoint as well (the /wallet suffix on the path is no longer needed

Is the `/v2/publishers/#{brave_publisher_id}/wallet` endpoint going away entirely then? So all publisher updates go through `PUT /v1/publishers/{brave_publisher_id}`? Still `v1`, right?

> Past month 

On August 15, should this include July 16 - August 15? Or July 1-31? If the latter, I suggest it be renamed to "Last month" to be consistent with the other option, "Last year".

**Comment by mrose17** [comment]
`show_verification_status` is the value associated with the checkbox at the bottom:
![0](https://user-images.githubusercontent.com/400552/30033842-a583a320-9152-11e7-94ca-ba99ef7b0f32.png)
the result will not be effected at all!

yes,exactly. send it to `/v1/...`

right you are: it should be "last month"...

thanks!

**Comment by dgeb** [comment]
@mrose17 thanks for the clarifications. A few more questions:

* The `publishers` table (in the publishers app) already has a `show_verification_status` field. Is it possible for this field to get out of sync with what's stored on eyeshade? I assume this is the case since you suggest calling `publisher_token_requester.rb::perform` with a query parameter of `show_verification_status=true`.

* When generating a publisher statement, is a link labeled `Save` appropriate? Perhaps a `Generate` button instead? If this setting is actually being "saved", should we add a column for tracking the most recently selected statement type in the publishers table. After clicking, should we hide or disable this button and show a spinner while polling the generated report URL as you describe?

* Is it necessary to provide all of this functionality with JS disabled? I imagine this would require a separate edit page for the contact person and the `show_verification_status` checkbox. Furthermore, the publisher statement generation process will be less dynamic and won't be able to use polling.

**Comment by mrose17** [comment]
@dgeb - and here are answers

- the "source of truth" for some of the data is publishers.brave.com. what that means is that eyeshade either expects to be updated when there's a change (e.g., with `show_verification_status`) or it will query publishers (e.g., to get an email address). for our purposes, what that means is `GET /v1/publishers/{publisher}/verifications/{verificationId}` has to include it as a query parameter, and when it changes via the settings page, then `PUT /v1/publishers/{publisher}` should be called.

- "Generate" is a better choice, thanks. i like the idea of having the ability to download. one thing though: the report disappears after ~24 hours, so a 404 could be "too soon" or "too late"

- the status page should require javascript. 

thanks!

**Comment by dgeb** [comment]
@mrose17 I was definitely not clear on the source of truth for `show_verification_status` and was trying to understand how it was to be _returned_ from eyeshade. But now I see that you want the _value_ to be sent to eyeshade via the query parameter. Thanks for the clarification!

**Comment by dgeb** [comment]
@mrose17 A couple questions about the `/v1/publishers/{publisher}/statement` endpoint:

* what is the `access_token` param that should be sent?
* what values should be used for `starting` and `ending` when the `All` statement period has been selected?

**Comment by mrose17** [comment]
Use the same access token as the other calls 

Don't send the starting/ending paymasters on 'all'

**Comment by alexwykoff** [comment]
Copying this comment as it pertains to our links to Uphold : https://github.com/brave/publishers/issues/50#issuecomment-329200004

**Comment by dgeb** [comment]
@mrose17 @alexwykoff I'll need the text for the email to send users when the publisher statement has been generated. I assume it should mention something along the lines of the statement only being available for 24 hours.

**Comment by alexwykoff** [comment]
![email](https://user-images.githubusercontent.com/1434040/31186815-636b1aee-a8f5-11e7-95d9-93b604b65858.png)

looking at our current verification email as a guide, here is what i would suggest for email copy : 

"Your Brave Payments publisher statement is now ready.  It will remain available for 24 hours. You can access it using the link below.

**Publisher statement access link:** 
((link goes here))
"

**Comment by mrose17** [comment]
Fixed.

**Comment by mrose17** [comment]
Oops, closed a little earlier than it should be...
