### ISSUE TITLE
Support Delete via Admin

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#751]
We frequently get requests to delete owner accounts for various reasons.  Some publishers have stopped using the app, signed up in error, and others would like to do some account shuffling.  We should allow owner accounts to be easily deleted.

Deleting an account requires some coordination with eyeshade in order to keep the databases in sync.  We will need a service similar to the `PublisherChannelDeleter` that hits an endpoint on Eyeshade and safely removes the owner account.

At a minimum we should enable this behavior for admins via the rails console, but we should also consider adding this functionality within the dashboard.

**Comment by yachtcaptain23** [comment]
Closed in favor of admin dashboard.

**Comment by yachtcaptain23** [comment]
Alternatively: We add a button to delete their account.

**Comment by yachtcaptain23** [comment]
Assigned to myself and Mandar to create an official internal documentation containing policy.
