### ISSUE TITLE
Provide user more info for failed public file site verification

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#757]
In #711, we discuss ways to provide more information to the user so they can resolve verifications issues themselves.  As a first step, we should should:

1.  Implement the modal when the publisher returns for the first time since a failed verification attempt
![image](https://user-images.githubusercontent.com/12549658/38103685-118c93ca-3355-11e8-90e0-f5415cfd139a.png)

2. Send an email when a verification attempt fails (only once)

Subject:
```
{channel.publication} Verification Failed
```
Body:
```
Hi {publisher.name},

We could not verify your channel, {channel.publication_title}.
Please make sure the verification file is in the .well-known folder, and the file name is **brave-payments-verification.txt**.

The Brave Payments Team
```

For now, let's only implement this with SiteChannelDetails whose `verification_method` is `public_file`, and save failed `dns` verifications for another time.

Something to consider:  the `EnqueueSiteChannelVerifications` job runs once every hour, and we want to avoid sending a 'verification failed' email every single time.

**Comment by yachtcaptain23** [comment]
Dup of #711.
