### ISSUE TITLE
When sharing the site, there should be a preview with an image

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#758]
We do not support [open graph tags](http://ogp.me/) or [twitter cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started), so when we share the website, the preview is bland.

![image](https://user-images.githubusercontent.com/12549658/38148574-0ea81bc2-3425-11e8-9b66-f58ae1b1646d.png)

Let's add support for open graph and twitter cards for a more professional presentation.

@jenn-rhim What image would you like us to use?

**Comment by jenn-rhim** [comment]
Let's use this one (attached below).
Here is the revised copy:
"Do you run a website or channels on YouTube or Twitch? If you’re interested in monetizing your content, verify your site and unlock your contributions!

basicattentiontoken.org"

Reference screenshot:
![screen shot 2018-03-30 at 4 43 01 pm](https://user-images.githubusercontent.com/4369856/38157893-3995416e-3440-11e8-9520-836a1a3f00a1.png)



![img-og-brave 1x](https://user-images.githubusercontent.com/4369856/38157871-067a8d34-3440-11e8-8ac4-cc4bd40dbccc.png)
![img-og-brave 2x](https://user-images.githubusercontent.com/4369856/38157872-0692afae-3440-11e8-8c02-d5884f9469e7.png)
![img-og-brave 3x](https://user-images.githubusercontent.com/4369856/38157873-06ab4b86-3440-11e8-97ba-3e521bf08ebe.png)
