### ISSUE TITLE
2fa confirm modal shows up twice

### ISSUE THREAD

**Issue by atsyed87** [brave-intl/publishers#769]
Steps to reproduce:

- create new account
- enable 2fa
- add new channel and go to login page for twitch/youtube/etc
- don't actually create channel
- instead, press back on browser
- 2fa notification message appears again

![image](https://user-images.githubusercontent.com/243423/38335347-daf5134c-3812-11e8-91bf-d37f34dd18eb.png)

**Comment by nvonpentz** [comment]
This is not reproducible in development, but it is on staging/production.

We may not be correctly clearing the session.  The modal appears no matter if 10 minutes has passed.

https://github.com/brave-intl/publishers/blob/3bc4c800015dd136e59322d905918779bfe45220/app/controllers/concerns/two_factor_registration.rb#L8-L16
