### ISSUE TITLE
PublisherNotifierUnverified service is not used anywhere and is missing tests

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#785]
The `PublisherNotifierUnverified` service used to be referenced in`API::PublishersController`, but was removed during multi channel, along with all of the tests. This is the original pull request https://github.com/brave-intl/publishers/pull/429.

The `PublisherNotifier` is used by the `API::ChannelsController`, so that's where the `PubisherNotifierUnverified` service should be used as well.

We should also consider changing the name of the service, since there is no notion of an unverified publisher.  Maybe `UnregisteredPublisherNotifier`?

Eyeshade has not implemented this yet.

Related to https://github.com/brave-intl/bat-ledger/pull/107

**Comment by yachtcaptain23** [comment]
Nick would you triage and see if this is still necessary?

**Comment by nvonpentz** [comment]
We will be removing the PublisherNotifierUnverified service since it has not been used in the past, will likely require use of sendgrid email unsubscribes, and because publishers (not eyeshade) will begin to kick off report generation.
