### ISSUE TITLE
Add the "Now verifying your domain.." modal to dashboard

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#787]
![image](https://user-images.githubusercontent.com/12549658/38701663-7412b1e2-3e6c-11e8-9e04-680ae4c5f073.png)

@dgeb Would this be better addressed as part of #786?

**Comment by dgeb** [comment]
The work in 923dde385e8089aaf2db581c12cee48bde99ab22 makes site verification synchronous and seems to eliminate the need for this modal.

Either we need to return to async verification and introduce this modal, or we should keep the status quo.

**Comment by nvonpentz** [comment]
Closed because we're doing this synchronously since PSoT!
