### ISSUE TITLE
Docker-compose dev environment?

### ISSUE THREAD

**Issue by dogweather** [brave-intl/publishers#793]
Hi,

Would you open to a PR with a Docker config, to make it easy to set up the dev environment? I might like to contribute, and that'd make it a lot easier. [Here's the configuration I use](https://github.com/dogweather/rails-docker-compose) for my Rails projects. If not Docker, a Vagrant config would be next-best.

The bottom line, with that config: one can create a new ready-to-go dev environment with one command ( `docker-compose up` ) on Mac or Linux.

**Comment by maikelmclauflin** [comment]
why was this closed @lgebhardt  @nvonpentz @dogweather ? i don't see a docker-compose file in the repo. was just about to make a task, assign to self and make one so that a monorepo could be created for e2e integration testing

**Comment by nvonpentz** [comment]
@maikelmclauflin it wasn't closed.  it would be sweet if you could create a monorepo!

**Comment by maikelmclauflin** [comment]
oh, my bad. looked at the wrong icon. thanks @nvonpentz
