### ISSUE TITLE
Run async the PublisherChannelSetter

### ISSUE THREAD

**Issue by ayumi** [brave-intl/publishers#842]
This job syncs the state of verified channels from Publishers to Eyeshade. Currently it runs synchronously after adding channels.
To improve resiliency for API access, we should run the service and on failure retry asynchronously.

**Comment by yachtcaptain23** [comment]
Assigning @lgebhardt to see if this issue should be closed.

**Comment by lgebhardt** [comment]
I think this is still a valid issue, assuming we still need to register verified channels with eyeshade. @evq Can you confirm that we still need to notify eyeshade about all verified channels through the `/v2/owners` endpoint?

**Comment by evq** [comment]
Closing since we'll remove this in https://github.com/brave-intl/publishers/issues/903
