### ISSUE TITLE
The channel details association on the Publisher model are broken

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#847]
When testing out the active admin gem for #839, I was prompted with errors that revealed our associations for `site_channel_details` and `youtube_channel_details` on the publisher model are broken.

You can reproduce this yourself by running
```
publisher.site_channel_details
```
for some publisher in the rails console.

**Comment by yachtcaptain23** [comment]
I think it has to deal with our models being plural rather than singular. It's probably a refactoring we'd have to do which could be minor.

**Comment by nvonpentz** [comment]
@yachtcaptain23 take a look at my solution in #848

**Comment by dgeb** [comment]
If these relationships have been broken and it's not been noticed because they are unused, should we just remove them (for now)? If they'll be immediately useful in an admin console then I'd say fixing them would be worthwhile.

**Comment by nvonpentz** [comment]
@dgeb I think this would be useful to quickly check the breakdown of channels for a given publisher.  I could do 
```ruby
publisher.youtube_channel_details.count
```
instead of having to iterate through all the channels and sum via the `details_type`.

It'd also be required if we wanted to use activeadmin or railsadmin (which is still tbd).

**Comment by dgeb** [comment]
@nvonpentz ok, seems useful, even if just from the console :+1:
