### ISSUE TITLE
Investigate use of `v3/timestamp` and migrate over if necessary

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#861]
I'll be updating this issue on the fly as I communicate more with @NejcZdovc . I'm going to update this issue as the primary issue across `Ledger` and `Publishers`

Implementation on browser is done: 
https://github.com/brave-intl/bat-client/blob/master/index.js#L618

**Comment by nvonpentz** [comment]
@yachtcaptain23 I see this is assigned to me in Asana.  I don't know what v3/timestamp does.  Could you provide more information on what the purpose of the endpoint is - or is that the point of the issue?

**Comment by yachtcaptain23** [comment]
@nvonpentz https://github.com/brave-intl/bat-ledger/blob/61f85ed34c68d8ce9786e64c00d71696be41211e/ledger/controllers/publisher.js#L499
