### ISSUE TITLE
Publishers using zoho as email host do not receive login link

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#864]
A few publishers have reported that they are unable to receive login links despite that the mailgun logs say the email has been delivered.  All of these publishers are using zoho as their email host.

I believe this could be related to our [DMARC policy on publishers](https://mxtoolbox.com/SuperTool.aspx?action=dmarc%3apublishers.basicattentiontoken.org&run=toolpage) which we have set to `quarantine`.

An example log mailgun log:

```json
{
    "tags": [],
    "delivery-status": {
        "tls": true,
        "mx-host": "mx.zoho.com",
        "attempt-no": 1,
        "description": "",
        "session-seconds": 1.2638728618621826,
        "code": 250,
        "message": "OK",
        "certificate-verified": true
    },
    "storage": {
        "url": "https://sw.api.mailgun.net/v3/domains/publishers.basicattentiontoken.org/messages/eyJwIjpmYWxzZSwiayI6IjAyMzYyNzQxLTA1OWEtNGY4OC1iOWM4LWViMTcxZTA2Y2UwNCIsInMiOiJhMjdkMjUzNDcwIiwiYyI6InRhbmtiIn0=",
        "key": "eyJwIjpmYWxzZSwiayI6IjAyMzYyNzQxLTA1OWEtNGY4OC1iOWM4LWViMTcxZTA2Y2UwNCIsInMiOiJhMjdkMjUzNDcwIiwiYyI6InRhbmtiIn0="
    },
    "log-level": "info",
    "id": "Om_aps6URNO8BbzO1zYwQA",
    "campaigns": [],
    "user-variables": {},
    "flags": {
        "is-routed": false,
        "is-authenticated": true,
        "is-system-test": false,
        "is-test-mode": false
    },
    "recipient-domain": "redacted",
    "timestamp": 1526268739.058543,
    "envelope": {
        "transport": "smtp",
        "sender": "support+publishers@basicattentiontoken.org",
        "sending-ip": "159.135.237.224",
        "targets": "redacted"
    },
    "message": {
        "headers": {
            "to": "redacted",
            "message-id": "5af903408eb75_4339f2941143db@18087d72-91f6-4dbf-b3df-6d772550f803.mail",
            "from": "Brave Payments <support+publishers@basicattentiontoken.org>",
            "subject": "Log In to Brave Payments"
        },
        "attachments": [],
        "size": 79434
    },
    "recipient": "redacted",
    "event": "delivered"
}
```

**Comment by nvonpentz** [comment]
Thanks @ayumi.  The publisher is not getting the email in their spam, and they have also whitelisted our email address.  I'd ask them to retrieve the logs, but since they aren't receiving the emails, I'm not sure how that's possible.

**Comment by rjpeterson** [comment]
I had this problem previously and since started receiving login emails again.  The steps I took were:

1. Disable uBlock Origin Chrome extension on Brave Payments login screen
2. Verify SPF Authentication in Zoho Control Panel (mailadmin.zoho.com/cpanel)
3. Set SPF "Fail" and "Soft Fail" to "Allow Email" in Zoho Control Panel
4. Whitelist both "support@basicattentiontoken.org" and "basicattentiontoken.org" in Zoho Control Panel (mailadmin.zoho.com/cpanel)
5. Whitelist both "support@basicattentiontoken.org" and "basicattentiontoken.org" in Zoho Mail (mail.zoho.com)

I doubt that all of these steps are necessary, but it worked for me.

**Comment by yachtcaptain23** [comment]
I will create an account and test this.

**Comment by yachtcaptain23** [comment]
![image](https://user-images.githubusercontent.com/8647607/41393318-0581f9e4-6f5a-11e8-97d3-90a216137f3f.png)

The message got delivered to my spam folder. I'm leaning towards marking this as a non-issue.

**Comment by yachtcaptain23** [comment]
Closed after discussion with Nick.

**Comment by jaredkotoff** [comment]
I tried everything @rjpeterson and emails still aren't coming through.
@nvonpentz Zoho users can see the emails in the Quarantine section under Spam control.
I can send the full email with headers to anyone who wants them.
