### ISSUE TITLE
Provide instructions link for how to withdraw funds

### ISSUE THREAD

**Issue by bbondy** [brave-intl/publishers#868]
It'd be good to have a link on the BAT publisher site which explains how to transfer funds out from Uphold.   In that answer we could also even give steps for how to transfer funds to the Brave BAT wallet.

**Comment by yachtcaptain23** [comment]
Assigning to myself to get this forced through.

**Comment by bbondy** [comment]
Making sure users can get funds out of their account and flow to other places like their Brave wallet is important.  It can be as simple as perhaps linking to some Uphold documentation for now or FAQ.  We also mentioned that we will improve this here:
https://www.reddit.com/r/BATProject/comments/8jh3aa/i_would_love_to_hear_responses_to_this_review/

**Comment by atsyed87** [comment]
Added a short FAQ along with a link to Uphold's withdrawals help desk section.
