### ISSUE TITLE
Finish markup + CSS modernization

### ISSUE THREAD

**Issue by dgeb** [brave-intl/publishers#880]
For the sake of expediency and to avoid blocking other work, I skipped some cleanup and modernization chores in #878 as part of the Bootstrap 4 upgrade. This is a tracking issue for the remaining work:

- [ ] Use `$spacer` var as a basis for all margins + padding. Many styles on the dashboard continue to use px.
- [x] Centralize the modal dialog styles + markup. A unique approach is used by the `channel_taken` dialog, which should be brought inline with the other modals.
- [ ] Derive more base panel classes, similar to `single-panel`, to be used on the dashboard in multi-panel arrangements.
- [ ] Eliminate use of explicit `float-left` and `float-right` classes. Floats are better defined in other classes.
- [ ] Delete unused fonts - OpenSans?

**Comment by yachtcaptain23** [comment]
Spoke with Ross, this no longer seems relevant in the current state. We'll be making adjustments to the UI ad hoc. 

Closing.
