### ISSUE TITLE
Have publishers calculate total publisher balance from channel balances

### ISSUE THREAD

**Issue by evq** [brave-intl/publishers#902]
Eyeshade's underlying accounting will switch from taking into account which channels belong to an owner, so the owner endpoint will no longer include the sum over all channel balances. Currently publishers already requests all individual channel balances so it should be easy to have publishers sum instead.

**Comment by yachtcaptain23** [comment]
ETA when Eyeshade is ready is June 15.

**Comment by yachtcaptain23** [comment]
I believe we can close this since `b4cc244a0fccc5f0b20f6ae8d75a5011b17ae62d` is merged

**Comment by evq** [comment]
agreed
