### ISSUE TITLE
Security review for PublicSuffix

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#913]
https://rubygems.org/gems/public_suffix/versions/3.0.2

Ledger uses TLD.js to get the [PublicSuffix](https://publicsuffix.org/), which is a non-algorithmic way to get subdomains. The gem `public_suffix` is on their approved list of libraries to obtain the subdomain/domain for a url:

```
2.3.7 :001 > PublicSuffix.domain("m.reddit.com")
 => "reddit.com"
2.3.7 :002 > PublicSuffix.domain("helloworld.github.io")
 => "helloworld.github.io"
2.3.7 :003 > PublicSuffix.domain("hello.blogspot.com")
 => "hello.blogspot.com"
```

**Comment by evq** [comment]
looks good to me, it's recommended by mozilla: https://publicsuffix.org/learn/
