### ISSUE TITLE
N+1 query for api/owners#index

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#914]
This causes > 5 seconds to load. PM me for details on New Relic if you don't have access.

**Comment by evq** [comment]
Confirmed that this is called by eyeshade in it's sanity function. Since this will go away once we disable synchronization I think we should downgrade this to P3 @yachtcaptain23

**Comment by yachtcaptain23** [comment]
Un-assigning this from Dan and assigning to me to followup on eyeshade.

**Comment by yachtcaptain23** [comment]
API No longer used.
