### ISSUE TITLE
"Add channel" is too prominent when modal is active

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#925]
![image](https://user-images.githubusercontent.com/12549658/40791048-838cd61a-64c4-11e8-8e0f-eef2a1870cb5.png)

**Comment by dgeb** [comment]
I believe this is only an issue for the "Channel taken" modal, but not the "Add channel" modal. I'd recommend fixing this by switching the "Channel taken" modal over to the new style of modals.

This work could be completed as part of #922 or after #922 lands.
