### ISSUE TITLE
Publishers should always have names

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#958]
It is possible to not supply a `name` when signing up.  As a result, some publishers are not addressed by name in the app emails.  We should add validations to the Publisher model and database constraints to prevent this.

**Comment by lgebhardt** [comment]
On SendGrid we have a custom field for Name, in addition to the default FirstName and LastName. Publishers has a combined name. Does it make sense to rework Publishers to use two name fields? We could do a rudimentary split with a name splitter gem. This would allow sending of less formal emails that address the user by their first name. It would also allow better compatibility with the SendGrid service.

**Comment by yachtcaptain23** [comment]
- [ ] Default: 'Brave Publisher'
- [ ] Backfilling
- [ ] Add a modal to ask for name later

**Comment by corymcdonald** [comment]
We're seeing this as a problem during payout report 

https://sentry.io/organizations/brave-software/issues/913482729/events/47862452685/
