### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#962]
- [ ] Use the same UI as settlements
- [ ] Database for storing question + answer, which will then interface with Admin. Questions should fall under a type (e.g. Payment).
- [ ] Part of the dropdown on the top-right side of the dashboard, which will be a link to FAQ.

**Comment by nvonpentz** [comment]
We do have a Brave Payments FAQ on brave.com https://brave.com/faq-payments/
