### ISSUE TITLE
ADMIN_IP_WHITELIST must always run in production

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#986]

**Comment by nvonpentz** [comment]
@yachtcaptain23 @evq I noticed this might be a problem, but kept it for consistency.  We're doing the same thing for the `API_IP_WHITELIST` and the `API_AUTH_TOKEN`

https://github.com/brave-intl/publishers/blob/staging/app/controllers/api/base_controller.rb#L30

I'll update all three for this issue.
