### ISSUE TITLE
Check both DNS and public file for every site verification verification attempt

### ISSUE THREAD

**Issue by lgebhardt** [brave-intl/publishers#987]
Update:  Doing so would reduce bugs when the wrong verification method is set.

--- 

Site channels will attempt verification both when he user clicks `verify` and when the `EnqueueSiteChannelVerifications` background job processes them. Before moving the verification process over to Publishers eyeshade would attempt to verify using both the file and dns txt record methods irregardless of the `verification_method` set on the SiteChannelDetails. Now the `SiteChannelVerifier` will only use the method set in `verification_method` https://github.com/brave-intl/publishers/blob/854b913394d34f8bb390a6fe674c9ba26d283849/app/services/site_channel_verifier.rb#L83). This opens the possibility for a user to inadvertently change the verification method by navigating to a new page (see https://github.com/brave-intl/publishers/blob/854b913394d34f8bb390a6fe674c9ba26d283849/app/controllers/site_channels_controller.rb#L147). Since the other methods are not checked the channel will never auto verify using the EnqueueSiteChannelVerifications job.

Note, this is an edge case that requires the synchronous `verify` call to fail for some transient reason and for the user to re-enter the channel but not re-click `verify`.

A better approach might be to go back to the method of attempting both file and dns methods each time we try to verify.

**Comment by yachtcaptain23** [comment]
@nvonpentz do you know if this is still relevant?

**Comment by nvonpentz** [comment]
@yachtcaptain23 Yes.  I will update the issue.

**Comment by tsmartt** [comment]
Closing as stale.
